### ISSUE TITLE
SSD1306 display issues (ACROBOTIC_SSD1306 library)

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#103]
**Example is taken from**: https://github.com/acrobotic/Ai_Ardulib_SSD1306
**Example**: https://github.com/acrobotic/Ai_Ardulib_SSD1306/tree/master/examples/HelloOLED

Problem: The code loads only the first character from the end of the display (expected to load from the top of the display). bets stuck soon after updating one character. 

**Project link here**: https://wokwi.com/arduino/projects/300623911739982344

**Comment by urish** [comment]
Note: seems like removing the call to `oled.clearDisplay();` improves the situation.

Needs further investigation.

**Comment by urish** [comment]
Fixed! Thanks for reporting :-)
