### ISSUE TITLE
LiquidMenu with LiquidCrystal_I2C

### ISSUE THREAD

**Issue by ArnoldasM** [wokwi/wokwi-features#105]
LiquidMenu doesn't work with I2C lcd screens. 

Sample wokwi.com project: [Wokwi.com](https://wokwi.com/arduino/projects/300833732015686154)

Best regards, 
Arnold

**Comment by urish** [comment]
Seems like LiquidMenu does not work with I2C screens out of the box, and the solution is to edit the configuration file:

https://github.com/VaSe7u/LiquidMenu/issues/36

**Comment by urish** [comment]
Once #229 will be done, you'll be able to upload a custom version of LiquidMenu with the required configuration changes.
