### ISSUE TITLE
OLED_I2C Library

### ISSUE THREAD

**Issue by oorazgeldiyeva** [wokwi/wokwi-features#106]
@urish 
Hello!
I have a request. Could you, please, add library "OLED_I2C.h". 
I can do my project without it too, but I find it a bit complicated.
 
I think, it is possible to add it by the link below:
http://robotchip.ru/download/library/OLED_I2C.zip

Thank you in advance!
Best regards,
oorazgeldiyeva

**Comment by urish** [comment]
Closing as we now have [custom library support](https://docs.wokwi.com/guides/libraries#uploading-custom-libraries)
