### ISSUE TITLE
DALLAS DS18B20 

### ISSUE THREAD

**Issue by pol-122** [wokwi/wokwi-features#110]
Hello!
I need DALLAS DS18B20, it is temperature chip. Could you add it? And if it is possible its library DallasTemperature.h too

**Comment by urish** [comment]
Library added! I'll look into adding the sensor  itself over the next couple of days.

What project are you working on?

**Comment by pol-122** [comment]
Oh, thank you!
It is just a simple project, which will show temperature on oled or lcd display.

If I know, there is not OLED_I2C library. So maybe I will use LCD I2C.

One more request. Could you add stepper? Its library exist, but sensor itself not

**Comment by urish** [comment]
> One more request. Could you add stepper? Its library exist, but sensor itself not

Mind opening a new issue for the stepper?

**Comment by urish** [comment]
> Library added! I'll look into adding the sensor itself over the next couple of days.

It'll take a while until I get to implementing OneWire simulation...

**Comment by AleksSteckie** [comment]
Hey! I also need the DS18B20 sensor for a uni project :) I was wondering if you've added it yet? I only found an analog temperature sensor and unfortunately it's not exactly what I'm looking for. Thanks!

**Comment by urish** [comment]
Hey @AleksandraStecka! 

It's currently [open for votes](https://wokwi.com/features#feature-916171688). The more votes it gets, the sooner we can get to work on it.

Are there any other parts you need for your uni project?

**Comment by flixmyswitch** [comment]
> 

Hi have been looking through the sensor but cant see this, so not sure if it has been created.  I see if way down the pecking order in the votes, sad face

**Comment by urish** [comment]
@flixmyswitch not yet. It did get 2 votes, which is a good starting point :)

**Comment by urish** [comment]
Good pointer from facebook discussion:  https://github.com/orgua/OneWireHub

**Comment by nikdevel** [comment]
Hello! I also really need the ability to simulate a DS18B20 sensor. This is a very useful addition in my opinion!

**Comment by urish** [comment]
@bonnyr started working on [an implementation](https://github.com/bonnyr/wokwi-ds1820-custom-chip/) using the Custom Chip API.

**Comment by bonnyr** [comment]
Implementation (first pass, intended to be generalised when I have time)

Repo for source is here: https://github.com/bonnyr/wokwi-ds1820-custom-chip 

The `README.md` should point to an example project I used for testing (https://wokwi.com/projects/349898396478210642)

This makes use of @urish addition of pulling custom chips from GitHub (kudos :) )

**Comment by urish** [comment]
Now available in the purple Add Part menu, as a beta feature:

![image](https://user-images.githubusercontent.com/892318/221411239-5653f70f-b6d5-4925-a191-bb7cd083d7df.png)
