### ISSUE TITLE
option to disable system dark mode/default in simulator window

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#111]
I would like to have a daylight switch button in the simulator as well. I would love to take simulation pictures in the white background as the parts really standout with the white background. 
![image](https://user-images.githubusercontent.com/68117142/121481231-8f14cc80-c9e9-11eb-8e9f-7d8c4f7361e8.png)

**Comment by urish** [comment]
For the time being: you can add ?dark=0 to the end of any project page link to disable the dark mode

**Comment by matititam** [comment]
This is sufficient for now. Thanks. Closing.
