### ISSUE TITLE
Change ATtiny85 clock to 16MHz

### ISSUE THREAD

**Issue by arcostasi** [wokwi/wokwi-features#114]
Please, I would like to create ATtiny85 simulations with wokwi-tv ​​and I need a internal clock of 16MHz or higher. Thanks

**Comment by urish** [comment]
You can now change the frequency by setting the "frequency" attr on the microcontroller (also works for all the other AVR chips, i.e. nano/uno/mega):

https://docs.wokwi.com/parts/wokwi-attiny85#attributes
