### ISSUE TITLE
Embedding the simulator in the web page - frame moves up after serial Tx

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#115]
https://arduino-simulator.blogspot.com/2021/06/arduino-simulator-examples-blink-led.html

the above link works fine as it doesn't have serial communication involved.

https://arduino-simulator.blogspot.com/2021/06/arduino-simulator-examples-pitch.html

The above link has a serial Tx involved and it makes the whole page jump to a level where only the latest Serial Tx can be seen. I believe this to be serial terminal related

same behaviour in both Firefox and Chrome browser.

**Comment by urish** [comment]
Thanks for reporting, Fixed!
