### ISSUE TITLE
Export project

### ISSUE THREAD

**Issue by arcostasi** [wokwi/wokwi-features#116]
Add an option to export the project files into a zip file. I think it can be done in the Save pop-up menu just below the Save a copy.

**Comment by urish** [comment]
Done!

I added it to the file drop down menu (where you can create new files, rename, delete, etc.), but I'm not sure it's the best place - should we move it to the save popup menu?

![image](https://user-images.githubusercontent.com/892318/122483254-d64b2080-cfda-11eb-91a7-42ec4ed0e20f.png)

**Comment by arcostasi** [comment]
I believe so @urish, maybe beginners or even visitors don't find this feature easy in projects.

**Comment by urish** [comment]
How about now?

![image](https://user-images.githubusercontent.com/892318/122655996-9feade00-d15f-11eb-80d3-fc22bfd9efcc.png)

**Comment by arcostasi** [comment]
Perfect @urish, I believe will give users more confidence in having a save option. Thank you very much
