### ISSUE TITLE
left scroll is not working as expected

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#117]
project link: https://wokwi.com/arduino/projects/301543301987697165

lcd.scrollDisplayLeft();

![RTC on wokwi Arduino Simulatori](https://user-images.githubusercontent.com/68117142/122349225-aa438700-cf69-11eb-9306-0bb8e9c0b32b.gif)

**Comment by urish** [comment]
Thanks for reporting!

Can you please attach a reference video of how the same code works on the physical hardware?

**Comment by matititam** [comment]
I do not have a 2004 display. I have 1602 displays with me. the issue is there with 1602 as well. I will check it on real hardware and share the reference by end of this week.

**Comment by urish** [comment]
Thank you!

Also, if you have an example of a 1602 code that behaves differently in the sim v.s. real life that would be helpful!

**Comment by urish** [comment]
Any updates?

**Comment by matititam** [comment]
Link for **Right** scroll example: https://wokwi.com/arduino/projects/302803492608672266
how it looks on the simulator (below image)
![RTC on wokwi Arduino Simulatori](https://user-images.githubusercontent.com/68117142/123913475-e4664d00-d99b-11eb-8aa2-c65ca971783a.gif)

How it works on the actual hardware: (link to the video)
Scrolling the text right - lcdsetCursor(0,1) to bring the text one row down (https://drive.google.com/file/d/1T5wpCTJ9QczeRr2UA6UsaSspVN9cBZe1/view?usp=sharing)

---------
Scrolling the text left: (https://drive.google.com/file/d/1ca0ADUZPBbO-d-dswR4W0QOdlRYKUXQD/view?usp=sharing)


if not, the text will scroll in the first row

**Comment by urish** [comment]
Alright, fixed!

Thanks for the detailed bug report :)
