### ISSUE TITLE
I need the library  "AccelStepper"  thanks

### ISSUE THREAD

**Issue by fedonga** [wokwi/wokwi-features#118]

**Comment by urish** [comment]
Hello! I can add the library, but we currently don't have a stepper motor. Would the library still be useful for you without the stepper motor simulation?

**Comment by urish** [comment]
Library added!

**Comment by fedonga** [comment]
Yes, thanks.

Best regards
Giovanni

Il ven 18 giu 2021, 01:45 Uri Shaked ***@***.***> ha scritto:
