### ISSUE TITLE
Logging into Wokwi using EMail address

### ISSUE THREAD

**Issue by leftCoast** [wokwi/wokwi-features#121]
Can we have an eMail kind of login? I don't trust other apps for logging into things. When one is hakced (Always the eaisest target) you get everything hacked. I think its just a bad idea all around. In fact, I get all worked up about it.

**Comment by urish** [comment]
And it's ready!

![image](https://user-images.githubusercontent.com/892318/123946050-72940080-d9a7-11eb-8af5-b1968d200945.png)

Anything we should improve?

**Comment by leftCoast** [comment]
Its a little odd not having a password..

Otherwise? Its extremely nice to be able to save and retrieve projects!
