### ISSUE TITLE
The pins wont activate (for routing) if I change number of LEDs in the Ring

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#124]
**Project link**: https://wokwi.com/arduino/projects/302135681537278473

1. Add a LED Ring in the simulator window
2. Make sure the pins are active for routing using the mouse
3. Change the number of LEDs to other than 16 (example: 12)
4. check the pins now. the active connections won't appear
5. below image for reference

![Wokwi Pi Pico simulator-missing connection pins](https://user-images.githubusercontent.com/68117142/123203275-b6809480-d4d3-11eb-9d9d-31a2ea25ffde.gif)

**Comment by urish** [comment]
Thanks for reporting!

**Comment by drf5n** [comment]
Since wokwi-led-ring was mentioned here, I thought I'd paste the json used in that sketch:

```
    {
      "type": "wokwi-led-ring",
      "id": "ring1",
      "top": 11.33,
      "left": -182,
      "rotate": 0,
      "hide": false,
      "attrs": { "pixels": "16" }
    }
```

It woks fine for "pixels": "160"
