### ISSUE TITLE
Simulate potentiometer ADC noise

### ISSUE THREAD

**Issue by costyn** [wokwi/wokwi-features#126]
In real world potentiometers, when reading them using analogread(), they are pretty noisy. Some Googling shows I'm not the only one. 

To make sure people aren't unpleasantly surprised when they recreate their Wokwi simulation in the real world, it would be cool to be able to simulate noisy potentiometer data.

On an ESP32 using a RV09 10kOhm potentiometer, hooked up to gnd, 3.3v and pin 23 I took readings for 10 seconds each, at 20ms intervals.

Google sheet with result:
https://docs.google.com/spreadsheets/d/1bSxzNHYO1Apk_BwC_P-bzPaNh49s2wPMZvvurYpLAi0/edit?usp=sharing

See also discussion in DIscord: https://discord.com/channels/787627282663211009/787630013658824707/858047646928207882

**Comment by urish** [comment]
Closing as it is now possible to simulate ADC noise using [custom chips](https://docs.wokwi.com/chips-api/getting-started)
