### ISSUE TITLE
Request to add the PID Library

### ISSUE THREAD

**Issue by daVinci2793** [wokwi/wokwi-features#131]
Hello, 

I am making this request to respectfully request that you add the PIDLibrary to WOKWI. The Arduino.cc page can be found [here ](https://playground.arduino.cc/Code/PIDLibrary/)

I would also appreciate the addition of a PWM DC motor/fan to be added to the components list. 

Thank you very much!

**Comment by urish** [comment]
PID Library added!

About the PWM DC motor, mind opening a separate issue for it?

**Comment by daVinci2793** [comment]
Thank you for the incredibly quick response! I can and would love to make another issue for the second request.
