### ISSUE TITLE
Serial monitor moves off-screen when scrolling

### ISSUE THREAD

**Issue by sutaburosu** [wokwi/wokwi-features#134]
I'm seeing this in both Chromium and Firefox. The height of browser window affects how many lines must be printed to trigger this problem.

![ser_mon](https://user-images.githubusercontent.com/20606/124387855-059aa680-dcd8-11eb-9508-3f4892c7a0a7.gif)

**Comment by urish** [comment]
Thanks for reporting, should be fixed now!

**Comment by sutaburosu** [comment]
That's perfect.  Thanks.
