### ISSUE TITLE
Slider switch bug

### ISSUE THREAD

**Issue by costyn** [wokwi/wokwi-features#135]
As discussed before on Discord, there is something funny going on with the the slide switch, the short circuit detection is firing as seen in JS Console, even when using a resistor.

Example project where it goes wrong: https://wokwi.com/arduino/projects/302764935759266314
Also: https://wokwi.com/arduino/projects/292033853022798344  (green flashes, but red doesnt)

Discord: https://discord.com/channels/787627282663211009/787630013658824707/860234287302574140

**Comment by urish** [comment]
Thank you so much for reporting. Fixed!
