### ISSUE TITLE
LED pin doesn't allow the connection to be made-sometimes

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#139]
Sometimes, the connection cannot be straightforward. here is a glimpse
![scroll rightq](https://user-images.githubusercontent.com/68117142/124604223-59e48880-de88-11eb-9b84-3315eaa1efe1.gif)

**Comment by urish** [comment]
Thanks for reporting! Which browser is this?

Can you send a link to the relevant project so I can reproduce it here?

**Comment by matititam** [comment]
Link here: https://wokwi.com/arduino/projects/303372512437207617
Browser: Firefox
unable to recreate - will report soon if I found a way

**Comment by matititam** [comment]
I just found a way to recreate it. I hope the below videos gives the hint!
![scroll right12](https://user-images.githubusercontent.com/68117142/124714105-f78a9700-df1e-11eb-9e1b-e92944629091.gif)

I guess when an area of one device overlap with others, it will come up ( the thin green rectangle blocks/covers teh adjacet LED's Pins)

If I move the LED away, the problem will nto appear. Keeping LEDs closer was the root cause. I guess

**Comment by urish** [comment]
> Keeping LEDs closer was the root cause

Indeed. Thanks for reporting, fixed!
