### ISSUE TITLE
PWM seems to not work on all the pins of Arduino Mega board

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#141]
Example code: https://wokwi.com/arduino/projects/303469685534360130 
Ref.: 
https://www.arduino.cc/reference/en/language/functions/analog-io/analogwrite/
![scroll right123](https://user-images.githubusercontent.com/68117142/124785567-97b6df00-df64-11eb-8054-1d1a740e09ac.gif)

**Comment by urish** [comment]
So pins 3, 7, and 13 are broken?

What about 44, 45, 46, are they functional?

**Comment by matititam** [comment]
on the board, we have pins 1 and 2. 
Pin 1 is broken. Pin 0 is okay

![image](https://user-images.githubusercontent.com/68117142/124794880-1d3e8d00-df6d-11eb-9a06-f49f1535a8ac.png)
![image](https://user-images.githubusercontent.com/68117142/124795883-2da33780-df6e-11eb-9701-e7adab1cba55.png)

**Comment by urish** [comment]
Seems like we're missing a output compare unit in the 16-bit timers, so I opened an AVR8js issue to track this: wokwi/avr8js#96

**Comment by urish** [comment]
Fixed!
