### ISSUE TITLE
Ghost connection points appears while moving the component to the new place

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#144]
Steps to recreate

1. Open Arduino empty project (https://wokwi.com/arduino/new?template=arduino-uno)
2. Add any part (LED)
3. Now pick the LED using mouse and try to place it around its old place itself but do not release the mouse
4. small video attached below
![Wokwi Pi Pico simulator6](https://user-images.githubusercontent.com/68117142/125641343-ed23fe71-d453-42c9-aebc-e5178a0fdd09.gif)

**Comment by urish** [comment]
Fixed, thanks for reporting!
