### ISSUE TITLE
UX: Let user retry another file name on name error

### ISSUE THREAD

**Issue by hllhll** [wokwi/wokwi-features#147]
When a user attempts to use bad file name, InputBox closes and doesn't let the user try again
I think it should close, let the user know, and let him try again, starting with the previous(bad) value.

**Comment by urish** [comment]
Done!

Now you also get immediate feedback as you type the file name:

![rename](https://user-images.githubusercontent.com/892318/126066031-51fd75e4-d58f-436d-8cdf-2fe3bce2f16d.gif)

Thanks for coming up with the suggestion :-)
