### ISSUE TITLE
Can you add this library?

### ISSUE THREAD

**Issue by CreamieOppai** [wokwi/wokwi-features#150]
[arduino-Max72xxPanel-master.zip](https://github.com/wokwi/wokwi-features/files/6836296/arduino-Max72xxPanel-master.zip)

**Comment by urish** [comment]
Is this library available on the Arduino Library manager?

**Comment by urish** [comment]
Closing - you can now add 3rd party libraries through [libraries.txt](https://docs.wokwi.com/guides/libraries)
