### ISSUE TITLE
Feature request: SpenceKonde's ATTinyCore

### ISSUE THREAD

**Issue by different55** [wokwi/wokwi-features#157]
Adds improved support for a lot of things (such as Wire) for the ATTiny85s. Should come in handy in supporting a lot of other things like #152 and honestly anything else that needs some I2C since it's drop-in compatible in my experience.

https://github.com/SpenceKonde/ATTinyCore

**Comment by urish** [comment]
Core added, you can activate it by setting the "env" attribute to "ATTinyCore" on the attiny85 part, e.g.:

```json
    {
      "type": "wokwi-attiny85",
      "id": "tiny",
      "top": 0,
      "left": 0,
      "attrs": { "env": "ATTinyCore" }
    },
```

Example:  https://wokwi.com/arduino/projects/306652924286599744

This also works with the Franzininho board.
