### ISSUE TITLE
Feature Request: basicMPU6050 library

### ISSUE THREAD

**Issue by different55** [wokwi/wokwi-features#158]
Not sure how far we wanna go down the rabbit hole of adding multiple libraries that more or less do the same thing, but outside of rolling your own code, this is the smallest (in terms of flash size) library I've found in the Library Manager for just pulling off raw accel/gyro values off the MPU6050. If desired, it also supports correcting for gyro drift through some fancy math.

**Comment by urish** [comment]
Library added!

**Comment by different55** [comment]
Thank you much!

**Comment by different55** [comment]
Just wanted to add that thanks to this library (and the others) being added, I was finally able to hunt down the last bug that's been keeping me from shrinking my Arduino project to ATTiny-scale, since the bug (missing call to Wire.begin in a library) that was plaguing me in the move to the ATTiny85 was also seen in the simulator, but *way* easier to pare down and isolate virtually. Thanks for helping me minimize the amount of hair pulling I was doing!

**Comment by urish** [comment]
Amazing!
