### ISSUE TITLE
unsaved project will be lost if I click on homepage or docs link

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#167]
Assume, I am editing someone else's project on Wokwi. If I do some changes but not save the code) and try to leave the Wokwi site, (hitting the back button or enter another site in the address bar) a warning pop up will be shown. This enables me to save the changes I did before navigating away.

But, if I click on the links on our site itself, it will not show any warnings

to recreate: 
1. Edit a project
2. Do not save
3. Click on the Wokwi homepage icon
4. I expect a warning to be thrown

**Comment by urish** [comment]
Can you please check again now?

**Comment by matititam** [comment]
It is working now. 💯
