### ISSUE TITLE
Filename option for the ZIP file download of Arduino project

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#168]
Currently, when one downloads the ZIP file, the browser will give the default name as `project` to the zip file. It will be nice if the site names the zip file according to the `ino` name of the project or something on that line. 
![Wokwi Arduino simulator - project name](https://user-images.githubusercontent.com/68117142/131227806-4f56063f-f7af-4857-9e20-97aaf34c82c8.gif)

**Comment by urish** [comment]
Done!
