### ISSUE TITLE
Code share feature pops error when clicked on Share button

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#17]
https://wokwi.com/share

steps:
1. Open https://wokwi.com/share
2. Type some dummy lines
3. Click on the Share button in the bottom

![image](https://user-images.githubusercontent.com/68117142/97796732-c5ac8c80-1c3b-11eb-9089-103df07454f8.png)

**Comment by urish** [comment]
Fixed!
