### ISSUE TITLE
Small UX improvements

### ISSUE THREAD

**Issue by sutaburosu** [wokwi/wokwi-features#173]
These are just possibilities to make the editor behaviour closer to "native" apps.

- [x] When changing tabs in the text editor, give focus back to the editor if it had focus before.
- [x] After creating a new file, switch to the new tab and focus the editor.
- [ ] When maximising/restoring the Simulation pane, keep the centre of view centred.

**Comment by urish** [comment]
>  When maximising/restoring the Simulation pane, keep the centre of view centred.

How about when resizing the diagram? should we also keep the centre of the view centred?

i.e.

![resize](https://user-images.githubusercontent.com/892318/131746566-bb1c7af2-cf28-4f9b-9e15-5cb418a8454b.gif)

**Comment by urish** [comment]
First two items done!

**Comment by sutaburosu** [comment]
Nice!  Thanks.  Yes, I think centreing when resizing would be a good addition too.

**Comment by urish** [comment]
And now also auto centring :-)
