### ISSUE TITLE
Neopixel matrix behaves strangely with an odd number of columns on serpentine layouts

### ISSUE THREAD

**Issue by sutaburosu** [wokwi/wokwi-features#179]
[This sketch](https://wokwi.com/arduino/projects/309448497790190146) should display a single vertical line moving to the right. When the matrix has an even number of columns, it works correctly.  For odd numbers of columns, part of the line is moving to the left instead.

**Comment by urish** [comment]
Thanks for reporting! Should be fixed now :)
