### ISSUE TITLE
The simulation window goes blank + The comments are not formatted

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#18]
I was playing with Arduino Mega simulation 

https://wokwi.com/arduino/libraries/demo/blink-mega

1. Changed the Mega to Nano (in the JSON file)
2. Simulation window updated to show Arduino Nano
3. Clicked on the blink-mega.ino file
4. The window in the right (simulation window) went blank (black)
below are the images

![image](https://user-images.githubusercontent.com/68117142/97799123-fe576080-1c51-11eb-858f-09719dbea491.png)
![image](https://user-images.githubusercontent.com/68117142/97799128-06af9b80-1c52-11eb-9eaf-b62482adc65f.png)

_________________________
Checks

1. The simulation window will also go blank if I miss punctuation. I am sure, I did not miss at that time (99%)
2. Even if I had missed it accidentally, the comments in the *.ino file won't be marked in red underlines.
3. to try out, I simply, made a punctuation mistake intentionally, and here is the screenshot (showing the comments being formatted properly) 
![image](https://user-images.githubusercontent.com/68117142/97799201-91909600-1c52-11eb-8994-fa38ad13fa0b.png)

![image](https://user-images.githubusercontent.com/68117142/97799204-98b7a400-1c52-11eb-8b43-38d6840370ca.png)

**Comment by urish** [comment]
Hi, I deployed a fix (also for #15) - can you please test again and report if the issue is gone?

**Comment by Puneethkumarsn** [comment]
it works :)
