### ISSUE TITLE
PIO wait pin instruction hangs in a MicroPython Project

### ISSUE THREAD

**Issue by jregier87** [wokwi/wokwi-features#182]
Using example code from here:
[](url)https://raw.githubusercontent.com/raspberrypi/pico-micropython-examples/master/pio/pio_pinchange.py

wait(0, pin, 0) 
wait(1, pin, 0)

These types of instructions only seem to work the first time they are encountered and only if the state of the pin is already set at startup. If I change the pin with switch the pio just hangs on the next wait pin instruction no matter what position the switch is in.

See:  [https://wokwi.com/arduino/projects/309993096270053952](url)  for an example

**Comment by urish** [comment]
Issue reproduced here

**Comment by urish** [comment]
Fixed! thanks for reporting :-)
