### ISSUE TITLE
ILI9341 0° and 180° display the same orientation. 

### ISSUE THREAD

**Issue by Trunik** [wokwi/wokwi-features#194]
The and 90° and 270° display orientations are also the same. Using RP2040 with SPI interface to the ILI9341.

https://wokwi.com/arduino/projects/310818024175174209

**Comment by urish** [comment]
Thanks for reporting! As far as I can tell, this is working correctly now.

```cpp
tft.setRotation(0);
```

![image](https://user-images.githubusercontent.com/892318/160273590-1d3b5fa2-13b3-4323-aee6-0a03fc7107f1.png)

```cpp
tft.setRotation(1);
```

![image](https://user-images.githubusercontent.com/892318/160273615-168fde0e-39b4-4b14-81b9-02fe6d2eb3f6.png)

```cpp
tft.setRotation(2);
```

![image](https://user-images.githubusercontent.com/892318/160273567-c6f95ad3-6aa1-437b-be94-a59a536ea3d2.png)


```cpp
tft.setRotation(3);
```

![image](https://user-images.githubusercontent.com/892318/160273632-4eb4fbe0-4258-4c72-a4ee-4c3d3c6dea2d.png)
