### ISSUE TITLE
We need a FT6206 simulated for the cap touch screen.

### ISSUE THREAD

**Issue by leftCoast** [wokwi/wokwi-features#197]
The Adafruit 1947 incorporates A TFT, capacitive touch and a SD card reader. Well, we have all the bits except the FT6206 touch chip. So, Lets add one of those in and we can really have some fun!

-jim lee

**Comment by urish** [comment]
* FT6206 datasheet: https://cdn-shop.adafruit.com/datasheets/FT6x06+Datasheet_V0.1_Preliminary_20120723.pdf
* FT6236 datasheet: https://focuslcds.com/content/FT6236.pdf
* FT6206 library (Adafruit): https://github.com/adafruit/Adafruit_FT6206_Library

**Comment by urish** [comment]
Update: there's a working prototype. Would you like a preview link to play with it or wait a day or two until it's ready?

**Comment by urish** [comment]
FT6206 demo: https://wokwi.com/arduino/projects/311598148845830720

Note that you need to add a custom board for this to work, see the instructions at the top of the file.

**Comment by leftCoast** [comment]
Uri, I may not be able to test this for a bit. At sea for a couple more
weeks. If I get near cell coverage I can at least do eMail (Today).

-jim

**Comment by urish** [comment]
No worries, whenever you are ready!

What are you doing at sea?

**Comment by leftCoast** [comment]
On a Holland America cruise ship going from Seattle to Florida via the
Panama canal. 3 weeks.

At this moment we are sitting dead in the water between Catalina island
(Off of Los Angeles) and San Diego. Its night time and wonder if the motor
broke? Oh well.. We'll see.


-jim lee

**Comment by urish** [comment]
Captain Jim Lee!

**Comment by urish** [comment]
Ahoy Captain! 

The Capacitive Touch Screen is ready for your command :-)

https://wokwi.com/arduino/projects/311598148845830720

**Comment by leftCoast** [comment]
Great! Give me some time I have some code to try on it.

**Comment by urish** [comment]
Lovely! Take as much time as you need :)

**Comment by Koepel** [comment]
There is a offset between the mouse and the pixels with Firefox 93.0 in Ubuntu linux, using the project mentioned above: https://wokwi.com/arduino/projects/311598148845830720
It does not happen with other browsers, it does not even happen with Firefox in an other linux distro (Manjaro) !

https://user-images.githubusercontent.com/12096541/140102285-4ded8685-d6c6-4ff4-9e7a-8900e2e17d67.mp4

I don't know why my specific setup causes this.

**Comment by Koepel** [comment]
With a Guest session I tried Firefox with its default settings in Ubuntu linux and there was no offset problem.
That means that my specific settings and add-on causes a offset for this display in Wokwi (and no where else).

**Comment by Koepel** [comment]
The add-on Font Fingerprint Defender is the cause of the offset: https://addons.mozilla.org/nl/firefox/addon/font-fingerprint-defender/

**Comment by urish** [comment]
Installing this extension reproduces the issue for me on Windows, but to a lesser extent. I guess the fingerprinting protection somehow interferes with some of the mouse pointer calculations.
