### ISSUE TITLE
seven segment display doesnt appear good when run at low speed

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#198]
Due to my PC limitation, the Seven segment display project (ESP32 Arduino core simulation) looks not so normal
![Wokwi-Arduino-BlinkLED-ESP32-Simulator-final-play2](https://user-images.githubusercontent.com/68117142/135884716-e75271c7-ac8e-4d1e-b89b-d03831dee2e2.gif)

Project link: https://wokwi.com/arduino/projects/305567166302782017

**Comment by urish** [comment]
Can you please check again now and report?

**Comment by matititam** [comment]
The fix is working! The display is now very smooth and natural

**Comment by urish** [comment]
Excellent, thanks for reporting!

**Comment by tumypv** [comment]
7 segment with Arduino still dosn't work properly on high speed.
https://wokwi.com/arduino/projects/323324789238268498

**Comment by urish** [comment]
> 7 segment with Arduino still dosn't work properly on high speed.

@tumypv thanks for reporting! Mind opening a new issue for this?
