### ISSUE TITLE
Add NLSF595

### ISSUE THREAD

**Issue by markjhughes** [wokwi/wokwi-features#199]
The NLSF595 is a serial Tri-color LED Driver that can control two RGB LEDs vai SPI protocol.  Two NLSF595 can control five RGB LEDs.  This is a feature for TeachMePCB.com's macro keypad.

**Comment by urish** [comment]
Datasheet: https://www.onsemi.com/pdf/datasheet/nlsf595-d.pdf

**Comment by urish** [comment]
Part added! 

- Usage example (with Arduino): https://wokwi.com/arduino/projects/315085666329297472
- Docs: https://docs.wokwi.com/parts/wokwi-nlsf595
