### ISSUE TITLE
Ability to 'probe' variables or signals to produce a graph of their value over time

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#20]
Feedback from Feedback from DeanIsMe/SevSeg#78:

> I think that some cool features for Wokwi would be:
> 
> - Control the rate of time movement
> - Ability to 'probe' variables or signals to produce a graph of their value over time

**Comment by urish** [comment]
Related: #34 - plotting data through serial port

**Comment by urish** [comment]
Closing as we now have both the [Serial Plotter](https://docs.wokwi.com/guides/serial-monitor#display) and [Logic Anaylzer](https://docs.wokwi.com/guides/logic-analyzer)
