### ISSUE TITLE
WiFi Support for ESP32 / ESP32-S2

### ISSUE THREAD

**Issue by urish** [wokwi/wokwi-features#202]
WiFi support will allow you to connect to various hosts on the internet using standard protocols and standards: MQTT, REST, WebSockets, etc.

**Comment by pixavier** [comment]
Using MQTT with libraries like PubSubClient.h would be great. It would allow the development of complete projects with digital twins of embedded systems, a significant advance in the democratization of teaching in schools.

**Comment by urish** [comment]
Once we have WiFi support in place, MQTT libraries should work. I noted to check PubSubClient in particular.

The WiFi features currently has [45 votes](https://wokwi.com/features#feature-1016828798).

**Comment by urish** [comment]
Some progress update: managed to establish a connection to an open WiFi network within the simulation!

https://twitter.com/WokwiMakes/status/1457805832977063936

There's still much to be done, but this is one milestone :-)

**Comment by pixavier** [comment]
Very ecouraging Wireshark screenshot !
Closer and closer to an MQTT message capture.

**Comment by urish** [comment]
One packet at a time :)

**Comment by urish** [comment]
Replying to @lzzy12's comments from another issue:

> Does that mean we will be able to run webservers and run standard IOT simulations?

Yes, that's the plan.

**Comment by urish** [comment]
MQTT works!

I managed to successfully connect to an MQTT server from within the simulation, send and receive messages, using MicroPython (+ umqttsimple):

![image](https://user-images.githubusercontent.com/892318/142434068-866f92ed-29c7-47da-96e8-69f5342aab82.png)

HTTP works too. SSL does not - we'd need the hardware-accelerated AES peripheral.

**Comment by pixavier** [comment]
Great !

**Comment by pixavier** [comment]
I'm trying to connect to WiFi to test the pubsubclient library (https://github.com/knolleary/pubsubclient/tree/master/src), but I'm not able to connect (https://wokwi.com/arduino/projects/315894638733951554).

**Comment by shivamdev-lgtm** [comment]
> I'm trying to connect to WiFi to test the pubsubclient library (https://github.com/knolleary/pubsubclient/tree/master/src), but I'm not able to connect (https://wokwi.com/arduino/projects/315894638733951554).

I think it's still in testing phase and not yet pushed to production

**Comment by pixavier** [comment]
> > I'm trying to connect to WiFi to test the pubsubclient library (https://github.com/knolleary/pubsubclient/tree/master/src), but I'm not able to connect (https://wokwi.com/arduino/projects/315894638733951554).
> 
> I think it's still in testing phase and not yet pushed to production

OK

**Comment by urish** [comment]
> I think it's still in testing phase and not yet pushed to production

Indeed - it will probably be in production in a few days. Meanwhile, I ran @pixavier's project, and it seems to work well in the testing environment:

![image](https://user-images.githubusercontent.com/892318/142945076-c7178a5a-ed39-4006-b9ed-5cc355142ce5.png)

**Comment by pixavier** [comment]
Wow !

**Comment by shivamdev-lgtm** [comment]
It's been few days, is it out yet?

**Comment by urish** [comment]
Partially. You can try connecting to Wokwi-GUEST, and hopefully get some internet access. Not thoroughly tested, no code examples and and no user interface indication yet, so your milage may vary..

**Comment by shivamdev-lgtm** [comment]
```
#include <WiFi.h>

const char* wifi_name = "Wokwi-GUEST"; //Your Wifi name
const char* wifi_pass = "";    //Your Wifi password

void setup()
{
    Serial.begin(115200);
 
    // Let's connect to wifi network 
    Serial.print("Connecting to ");
    Serial.print(wifi_name);
    WiFi.begin(wifi_name, wifi_pass);       //Connecting to wifi network

    while (WiFi.status() != WL_CONNECTED) { //Waiting for the responce of wifi network
        delay(500);
        Serial.print(".");
    }
    Serial.println("");
    Serial.println("Connection Successful");
    Serial.print("IP address: ");
    Serial.println(WiFi.localIP());         //Getting the IP address at which our webserver will be created
    Serial.println("Put the above IP address into a browser search bar");
}

```

I tried this but it seems it just gets stuck in the `while (WiFi.status() != WL_CONNECTED)` loop endlessly. 
Am I missing something?

**Comment by pixavier** [comment]
Izzy12, can you try again ?  It worked for me.

![image](http://xavierpi.com/dt/wokwi_wow.png)

**Comment by shivamdev-lgtm** [comment]
> Izzy12, can you try again ? It worked for me.
> 
> ![image](https://camo.githubusercontent.com/d9cfdbd73c169f92d5cf425211bde47580b91a7daed1c0eb0c0f89e49c93a895/687474703a2f2f78617669657270692e636f6d2f64742f776f6b77695f776f772e706e67)

Yeah It started working after I called the WiFi.mode() method. pretty weird.

**Comment by pixavier** [comment]
Closer and closer:   https://wokwi.com/arduino/projects/316434364352168512

After a few seconds, it stops receiving messages, and after a while, it loses the MQTT connection and cannot reconnect.
(Tested with Chrome on Windows 10. Extremely slow with Firefox)

![image](http://xavierpi.com/dt/wowki_closer.png)

**Comment by urish** [comment]
Thanks for checking it! 

There seems to be something iffy with the websocket proxy, I'll have to investigate why this happens. 

What is the performance difference you are observing between Firefox / Chrome? 

I see in your screen shot chrome gets around 9%. What do you get on Firefox?

Does adding `delay(10);` to `loop()` help?

**Comment by pixavier** [comment]
> Thanks for checking it!
> 
> There seems to be something iffy with the websocket proxy, I'll have to investigate why this happens.
> 
> What is the performance difference you are observing between Firefox / Chrome?
> 
> I see in your screen shot chrome gets around 9%. What do you get on Firefox?
> 
> Does adding `delay(10);` to `loop()` help?

Connection times:

        Chrome  Firefox
WiFi     16"     1'21"
MQTT  17"     1'23"

Firefox also 9%

delay(10) appeared to improve the situation, but MQTT does not connect anymore after some seconds, less than a minute.

Digital Twin (DT) link:
https://wokwi.com/arduino/projects/316434364352168512

Snap! based DT test environment:
http://www.xavierpi.com/snap/snap.html#open:http://www.xavierpi.com/dt/mqtt_esp32-text.xml

**Comment by pixavier** [comment]
Two days working with it. Fairly good for prototype development and testing purposes. Sometimes, after some minutes ([1, 10]), MQTT loses connection, but one can continue testing by restarting the simulation again.
Very, very interesting. Thanks a lot, Uri.

**Comment by shivamdev-lgtm** [comment]
We're not able to host our own webserver right now, are we? I'm not able to connect to the ip address after starting the webserver

**Comment by urish** [comment]
> Two days working with it. Fairly good for prototype development and testing purposes. Sometimes, after some minutes ([1, 10]), MQTT loses connection, but one can continue testing by restarting the simulation again.

Thanks for the feedback! I believe this is an infrastructure issue. Do you have a specific use case for this or are you just playing around to explore what's possible?

> We're not able to host our own webserver right now, are we? I'm not able to connect to the ip address after starting the webserver

Can you explain more about your setup? Where is the web server running and where are you trying to connect to it from?

**Comment by shivamdev-lgtm** [comment]
> Can you explain more about your setup? Where is the web server running and where are you trying to connect to it from?

I was just trying to follow a few lectures from my university. Here is an article with something similar I was trying to do: https://randomnerdtutorials.com/esp32-web-server-arduino-ide/

**Comment by pixavier** [comment]
>> Thanks for the feedback! I believe this is an infrastructure issue. Do you have a specific use case for this or are you just playing around to explore what's possible?
> 
> We are preparing sensors and actuators combined with Node-RED and MQTT4Snap! examples for teaching purposes. Many of them will be open, so I will inform you when they will be available online.

**Comment by urish** [comment]
Good news: WiFi support is now done for the ESP32!

You can check out the documentation, including code examples and explanation about how to connect it to the Internet:

https://docs.wokwi.com/guides/esp32-wifi

@lzzy12 - there's also a way to host your own webserver on the ESP32 using the [Private Wokwi IoT Gateway](https://docs.wokwi.com/guides/esp32-wifi#the-private-gateway). You can see it in action in this video:

https://user-images.githubusercontent.com/892318/152354817-aebcbace-3fc3-4dc6-b56e-8bea6c2241de.mp4

The ESP32-S2 is still missing some bits, so it doesn't have a functional WiFi at the moment. We'll continue working on it as we improve the ESP32-S2 simulation as part of #196.

Finally, I want to thank everyone who supported and helped testing this feature. As a token of appreciation - if anyone who participated in this thread wants to have access to the Private Wokwi IoT Gateway, just let me know (+ send me a link to one of your Wokwi projects so I can find your user id). For others - you are always invited to [join the club](https://wokwi.com/club) and help make Wokwi better.

**Comment by pixavier** [comment]
Hi Uri,

Thank you for your offer to access the Private Wokwi IoT Gateway as a
participant in the thread.
You can find my user id from the following project:
https://wokwi.com/arduino/projects/324549436880454228

All the best,

Xavier Pi
https://github.com/pixavier

**Comment by shivamdev-lgtm** [comment]
Mine is https://wokwi.com/arduino/projects/319226828692652627

GitHub.com/lzzy12
I underlooked the thread few days ago :)

**Comment by urish** [comment]
You both @pixavier and @lzzy12 should now have access to the Private IoT Wokwi Gateway when you are logged-in.

Here are the [full instructions](https://docs.wokwi.com/guides/esp32-wifi#the-private-gateway). Please check it it works for you and report back.

**Comment by joshuasi546** [comment]
is it possible if I want the simulated ESP32 device to connect to the same network as my computer for device discovery? I'm aware that it uses a virtual WiFi access point called Wokwi-GUEST, is there a way so that the simulated device uses my computer network instead?

**Comment by urish** [comment]
>  is there a way so that the simulated device uses my computer network instead?

The private IoT Gateway let's the simulated device to connect to your local network, but I'm not exactly sure what you mean by device discovery.

**Comment by joshuasi546** [comment]
> The private IoT Gateway let's the simulated device to connect to your local network,

correct me if I'm wrong but the private gateaway allows the simulated device to communicate with services run on my local computer but it is still running on an isolated virtual network by itself?

> but I'm not exactly sure what you mean by device discovery.

it's for SmartThing device registration where you need to be in the same WiFi connection to detect your device
