### ISSUE TITLE
Font colour difficult to read

### ISSUE THREAD

**Issue by terrypin999** [wokwi/wokwi-features#206]
First, I'm not sure how to add a suggestion when looking at an 'Issue'? So I ended up here, even though it's merely a constructive passing **comment**, not a 'new issue'! Is there perhaps a section I've missed somewhere within GitHub's dauntingly complicated interface for this sort of message by non-programmers?

Here's my comment, as a screenshot:

![GitHubVoteFont](https://user-images.githubusercontent.com/7612034/137096677-c02bdd58-41c9-4897-ab42-2c26383e2f56.jpg)

Terry

**Comment by urish** [comment]
Hi Terry!

First of all - yes, this is the right place to post this kind of feedback.

Regarding the font color - that's interesting, it's different from what I see here (Chrome 94 on Windows):

![image](https://user-images.githubusercontent.com/892318/137096997-137bedef-e373-4e79-b8ca-ec4fcb0919ea.png)

Which web browser are you using?

**Comment by terrypin999** [comment]
Thanks Urish, impressively fast reply!

Interesting indeed. In Help > About I read:
'Chrome is up to date
Version 94.0.4606.81 (Offcial Build) (64-bit)'

This is on my PC (Intel Core i7 6700K (4.0GHz), 32 GB, using built-in Intel HD Graphics 530) with a Dell U-2415 monitor, 1920 x 1200.  I've just tried the link
https://github.com/wokwi/wokwi-features/issues/206 
in Edge and it's the same unreadable colour.

Happy to provide any other info/screenshots to help resolve the puzzle.

Terry

**Comment by sutaburosu** [comment]
Perhaps changing the [colour theme](https://github.com/settings/appearance) used by Github would help?

**Comment by terrypin999** [comment]
I’ll try that when I get back to my PC (although at present most alternative themes are dark, which I avoid). But meanwhile here on my iPad using Safari the colours are fine.

**Comment by terrypin999** [comment]
Made no difference.
 I've tried Chrome, Edge and Waterfox. Same issue in all.

**Comment by terrypin999** [comment]
Also asked in the Win 10 forum and had this prompt response:

"In Google Chrome I see a Purple background with what seems to be Black text, although it is VERY VERY difficult to see and read. I tried on TWO Laptops and a Desktop for you."

Terry

**Comment by terrypin999** [comment]
Interestingly both Chrome and Edge now display correctly. Last night WU took me from build 19042.1237 to 1288, so I'll conclude that as the cause. Only the old versions of Waterfox (2021.01) and Firefox (56.02) still display the unreadable text.
