### ISSUE TITLE
Avoid accidental wire/component deletes

### ISSUE THREAD

**Issue by ghost** [wokwi/wokwi-features#210]
Sometimes when creating/wiring a new component I accidentally click and remove a previous wire. Maybe you can change how to delete a wire by requiring the backspace key instead of clicking, or add the ability to lock a wire or component when it's in its final state so that it has to be unlocked before it can be changed.

**Comment by urish** [comment]
Thanks for the suggestion! 

One solution (which will probably also apply for #188) - when you click on a wire, select it (just like you when you click on a part), then use the Backspace/Delete key to delete it. Ideally we should also have some kind of popup menu where you can delete the wire (for mobile devices where you don't have keys), or change its color.

**Comment by urish** [comment]
Wires are now deleted by double-click!
