### ISSUE TITLE
Translate Wokwi to Chinese

### ISSUE THREAD

**Issue by zhufree** [wokwi/wokwi-features#211]
I want to introduce the website to kids, website in full English may be hard for them to use, if there is a way to add translation I would like to do translation work.

**Comment by urish** [comment]
First of all, thank you for helping out! 

Which parts of the website do you think are most important to translate first?

**Comment by zhufree** [comment]
> First of all, thank you for helping out!
> 
> Which parts of the website do you think are most important to translate first?

Button text and the name of elements

**Comment by urish** [comment]
So these ones (marked with a red rectangle)? 

![image](https://user-images.githubusercontent.com/892318/138089373-e68e3ec4-bb57-4ce2-b245-0bb24384c0d5.png)

**Comment by zhufree** [comment]
> So these ones (marked with a red rectangle)?
> 
> ![image](https://user-images.githubusercontent.com/892318/138089373-e68e3ec4-bb57-4ce2-b245-0bb24384c0d5.png)

Yes, especially the element part, button is easy to explain

**Comment by urish** [comment]
So we can start with this list. Here's the English file, can you send a translated version?

```json
[
  {
    "label": "Arduino Uno",
    "type": "wokwi-arduino-uno"
  },
  {
    "label": "Arduino Mega 2560",
    "type": "wokwi-arduino-mega"
  },
  {
    "label": "Arduino Nano",
    "type": "wokwi-arduino-nano"
  },
  {
    "label": "Raspberry Pi Pico",
    "type": "wokwi-pi-pico"
  },
  {
    "label": "Arduino Nano RP2040 Connect",
    "type": "wokwi-nano-rp2040-connect"
  },
  {
    "label": "ATtiny85",
    "type": "wokwi-attiny85"
  },
  {
    "label": "LED",
    "type": "wokwi-led"
  },
  {
    "label": "Pushbutton",
    "type": "wokwi-pushbutton"
  },
  {
    "label": "Resistor",
    "type": "wokwi-resistor"
  },
  {
    "label": "Slide switch",
    "type": "wokwi-slide-switch"
  },
  {
    "label": "Keypad",
    "type": "wokwi-membrane-keypad"
  },
  {
    "label": "Logic Analyzer (8 channels)",
    "type": "wokwi-logic-analyzer"
  },
  {
    "label": "LED Dot Matrix (MAX7219)",
    "type": "wokwi-max7219-matrix"
  },
  {
    "label": "NeoPixel Ring",
    "type": "wokwi-led-ring"
  },
  {
    "label": "NeoPixel Meter",
    "type": "wokwi-neopixel-meter"
  },
  {
    "label": "Buzzer",
    "type": "wokwi-buzzer"
  },
  {
    "label": "DHT22",
    "type": "wokwi-dht22"
  },
  {
    "label": "Potentiometer",
    "type": "wokwi-potentiometer"
  },
  {
    "label": "Slide Potentiometer",
    "type": "wokwi-slide-potentiometer"
  },
  {
    "label": "LCD 16x2",
    "type": "wokwi-lcd1602"
  },
  {
    "label": "LCD 16x2 (I2C)",
    "type": "wokwi-lcd1602"
  },
  {
    "label": "LCD 20x4",
    "type": "wokwi-lcd2004"
  },
  {
    "label": "LCD 20x4 (I2C)",
    "type": "wokwi-lcd2004"
  },
  {
    "label": "Servo",
    "type": "wokwi-servo"
  },
  {
    "label": "Rotary Dialer",
    "type": "wokwi-rotary-dialer"
  },
  {
    "label": "SSD1306 OLED display",
    "type": "wokwi-ssd1306"
  },
  {
    "label": "DS1307 RTC",
    "type": "wokwi-ds1307"
  },
  {
    "label": "HC-SR04 Ultrasonic Distance Sensor",
    "type": "wokwi-hc-sr04"
  },
  {
    "label": "RGB LED",
    "type": "wokwi-rgb-led"
  },
  {
    "label": "Seven Segment Display",
    "type": "wokwi-7segment"
  },
  {
    "label": "Seven Segment Display (4 digits)",
    "type": "wokwi-7segment"
  },
  {
    "label": "LED Bar Graph",
    "type": "wokwi-led-bar-graph"
  },
  {
    "label": "Analog Joystick",
    "type": "wokwi-analog-joystick"
  },
  {
    "label": "IR Receiver",
    "type": "wokwi-ir-receiver"
  },
  {
    "label": "IR Remote",
    "type": "wokwi-ir-remote"
  },
  {
    "label": "PIR Motion Sensor",
    "type": "wokwi-pir-motion-sensor"
  },
  {
    "label": "Analog Temperature Sensor (NTC)",
    "type": "wokwi-ntc-temperature-sensor"
  },
  {
    "label": "74HC595 Shift Register",
    "type": "wokwi-74hc595"
  },
  {
    "label": "Franzininho",
    "type": "wokwi-franzininho"
  },
  {
    "label": "Photoresistor (LDR) Sensor",
    "type": "wokwi-photoresistor-sensor"
  },
  {
    "label": "KY-040 Rotary Encoder",
    "type": "wokwi-ky-040"
  },
  {
    "label": "MPU6050 Accelerometer + Gyroscope",
    "type": "wokwi-mpu6050"
  },
  {
    "label": "microSD card",
    "type": "wokwi-microsd-card"
  }
]
```

**Comment by zhufree** [comment]
> So we can start with this list. Here's the English file, can you send a translated version?
> 
> ```json
> [
>   {
>     "label": "Arduino Uno",
>     "type": "wokwi-arduino-uno"
>   },
>   {
>     "label": "Arduino Mega 2560",
>     "type": "wokwi-arduino-mega"
>   },
>   {
>     "label": "Arduino Nano",
>     "type": "wokwi-arduino-nano"
>   },
>   {
>     "label": "Raspberry Pi Pico",
>     "type": "wokwi-pi-pico"
>   },
>   {
>     "label": "Arduino Nano RP2040 Connect",
>     "type": "wokwi-nano-rp2040-connect"
>   },
>   {
>     "label": "ATtiny85",
>     "type": "wokwi-attiny85"
>   },
>   {
>     "label": "LED",
>     "type": "wokwi-led"
>   },
>   {
>     "label": "Pushbutton",
>     "type": "wokwi-pushbutton"
>   },
>   {
>     "label": "Resistor",
>     "type": "wokwi-resistor"
>   },
>   {
>     "label": "Slide switch",
>     "type": "wokwi-slide-switch"
>   },
>   {
>     "label": "Keypad",
>     "type": "wokwi-membrane-keypad"
>   },
>   {
>     "label": "Logic Analyzer (8 channels)",
>     "type": "wokwi-logic-analyzer"
>   },
>   {
>     "label": "LED Dot Matrix (MAX7219)",
>     "type": "wokwi-max7219-matrix"
>   },
>   {
>     "label": "NeoPixel Ring",
>     "type": "wokwi-led-ring"
>   },
>   {
>     "label": "NeoPixel Meter",
>     "type": "wokwi-neopixel-meter"
>   },
>   {
>     "label": "Buzzer",
>     "type": "wokwi-buzzer"
>   },
>   {
>     "label": "DHT22",
>     "type": "wokwi-dht22"
>   },
>   {
>     "label": "Potentiometer",
>     "type": "wokwi-potentiometer"
>   },
>   {
>     "label": "Slide Potentiometer",
>     "type": "wokwi-slide-potentiometer"
>   },
>   {
>     "label": "LCD 16x2",
>     "type": "wokwi-lcd1602"
>   },
>   {
>     "label": "LCD 16x2 (I2C)",
>     "type": "wokwi-lcd1602"
>   },
>   {
>     "label": "LCD 20x4",
>     "type": "wokwi-lcd2004"
>   },
>   {
>     "label": "LCD 20x4 (I2C)",
>     "type": "wokwi-lcd2004"
>   },
>   {
>     "label": "Servo",
>     "type": "wokwi-servo"
>   },
>   {
>     "label": "Rotary Dialer",
>     "type": "wokwi-rotary-dialer"
>   },
>   {
>     "label": "SSD1306 OLED display",
>     "type": "wokwi-ssd1306"
>   },
>   {
>     "label": "DS1307 RTC",
>     "type": "wokwi-ds1307"
>   },
>   {
>     "label": "HC-SR04 Ultrasonic Distance Sensor",
>     "type": "wokwi-hc-sr04"
>   },
>   {
>     "label": "RGB LED",
>     "type": "wokwi-rgb-led"
>   },
>   {
>     "label": "Seven Segment Display",
>     "type": "wokwi-7segment"
>   },
>   {
>     "label": "Seven Segment Display (4 digits)",
>     "type": "wokwi-7segment"
>   },
>   {
>     "label": "LED Bar Graph",
>     "type": "wokwi-led-bar-graph"
>   },
>   {
>     "label": "Analog Joystick",
>     "type": "wokwi-analog-joystick"
>   },
>   {
>     "label": "IR Receiver",
>     "type": "wokwi-ir-receiver"
>   },
>   {
>     "label": "IR Remote",
>     "type": "wokwi-ir-remote"
>   },
>   {
>     "label": "PIR Motion Sensor",
>     "type": "wokwi-pir-motion-sensor"
>   },
>   {
>     "label": "Analog Temperature Sensor (NTC)",
>     "type": "wokwi-ntc-temperature-sensor"
>   },
>   {
>     "label": "74HC595 Shift Register",
>     "type": "wokwi-74hc595"
>   },
>   {
>     "label": "Franzininho",
>     "type": "wokwi-franzininho"
>   },
>   {
>     "label": "Photoresistor (LDR) Sensor",
>     "type": "wokwi-photoresistor-sensor"
>   },
>   {
>     "label": "KY-040 Rotary Encoder",
>     "type": "wokwi-ky-040"
>   },
>   {
>     "label": "MPU6050 Accelerometer + Gyroscope",
>     "type": "wokwi-mpu6050"
>   },
>   {
>     "label": "microSD card",
>     "type": "wokwi-microsd-card"
>   }
> ]
> ```

Okay, I will give a Chinese version later

**Comment by zhufree** [comment]
```
[
  {
    "label": "Arduino Uno",
    "type": "wokwi-arduino-uno"
  },
  {
    "label": "Arduino Mega 2560",
    "type": "wokwi-arduino-mega"
  },
  {
    "label": "Arduino Nano",
    "type": "wokwi-arduino-nano"
  },
  {
    "label": "树莓派 Pi Pico",
    "type": "wokwi-pi-pico"
  },
  {
    "label": "Arduino Nano RP2040 Connect",
    "type": "wokwi-nano-rp2040-connect"
  },
  {
    "label": "ATtiny85芯片开发板",
    "type": "wokwi-attiny85"
  },
  {
    "label": "LED灯",
    "type": "wokwi-led"
  },
  {
    "label": "按钮",
    "type": "wokwi-pushbutton"
  },
  {
    "label": "电阻",
    "type": "wokwi-resistor"
  },
  {
    "label": "开关",
    "type": "wokwi-slide-switch"
  },
  {
    "label": "键盘",
    "type": "wokwi-membrane-keypad"
  },
  {
    "label": "逻辑分析仪（8通道）",
    "type": "wokwi-logic-analyzer"
  },
  {
    "label": "LED点阵屏 (MAX7219)",
    "type": "wokwi-max7219-matrix"
  },
  {
    "label": "NeoPixel环",
    "type": "wokwi-led-ring"
  },
  {
    "label": "NeoPixel表",
    "type": "wokwi-neopixel-meter"
  },
  {
    "label": "蜂鸣器",
    "type": "wokwi-buzzer"
  },
  {
    "label": "温湿度传感器DHT22",
    "type": "wokwi-dht22"
  },
  {
    "label": "电位器",
    "type": "wokwi-potentiometer"
  },
  {
    "label": "滑动电位器",
    "type": "wokwi-slide-potentiometer"
  },
  {
    "label": "LCD 16x2",
    "type": "wokwi-lcd1602"
  },
  {
    "label": "LCD 16x2 (I2C)",
    "type": "wokwi-lcd1602"
  },
  {
    "label": "LCD 20x4",
    "type": "wokwi-lcd2004"
  },
  {
    "label": "LCD 20x4 (I2C)",
    "type": "wokwi-lcd2004"
  },
  {
    "label": "舵机",
    "type": "wokwi-servo"
  },
  {
    "label": "旋转拨号器",
    "type": "wokwi-rotary-dialer"
  },
  {
    "label": "SSD1306 OLED显示器",
    "type": "wokwi-ssd1306"
  },
  {
    "label": "DS1307 时钟芯片",
    "type": "wokwi-ds1307"
  },
  {
    "label": "HC-SR04超声波传感器",
    "type": "wokwi-hc-sr04"
  },
  {
    "label": "三色灯",
    "type": "wokwi-rgb-led"
  },
  {
    "label": "七段数码管",
    "type": "wokwi-7segment"
  },
  {
    "label": "4位7段数码管",
    "type": "wokwi-7segment"
  },
  {
    "label": "LED条图显示器",
    "type": "wokwi-led-bar-graph"
  },
  {
    "label": "模拟操纵杆",
    "type": "wokwi-analog-joystick"
  },
  {
    "label": "红外接收器",
    "type": "wokwi-ir-receiver"
  },
  {
    "label": "红外遥控器",
    "type": "wokwi-ir-remote"
  },
  {
    "label": "PIR运动传感器",
    "type": "wokwi-pir-motion-sensor"
  },
  {
    "label": "模拟温度传感器 (NTC)",
    "type": "wokwi-ntc-temperature-sensor"
  },
  {
    "label": "74HC595 位移缓存器",
    "type": "wokwi-74hc595"
  },
  {
    "label": "Franzininho开发板",
    "type": "wokwi-franzininho"
  },
  {
    "label": "光敏电阻（LDR）传感器",
    "type": "wokwi-photoresistor-sensor"
  },
  {
    "label": "KY-040 旋转编码器",
    "type": "wokwi-ky-040"
  },
  {
    "label": "MPU6050 六轴传感器（加速度计+陀螺仪）",
    "type": "wokwi-mpu6050"
  },
  {
    "label": "microSD卡",
    "type": "wokwi-microsd-card"
  }
]
```

**Comment by urish** [comment]
Thank you! Here's a first preview with the new texts: https://wokwi.com/arduino/new?lang=zh

**Comment by zhufree** [comment]
> Thank you! Here's a first preview with the new texts: https://wokwi.com/arduino/new?lang=zh

Nice！

**Comment by zhufree** [comment]
Some translations for buttons:
```
save - 保存
save a copy - 另存为
Download project zip - 下载项目文件
share - 分享
simulation - 模拟
Rename - 重命名
New file - 新文件
Upload file(s) - 上传文件
```
and btw, why there are two 七段数码管
![image](https://user-images.githubusercontent.com/6095752/138195676-2f67f0d9-a683-4e22-a13d-2c010609658a.png)
```
{
    "label": "七段数码管",
    "type": "wokwi-7segment"
  },
  {
    "label": "4位7段数码管",
    "type": "wokwi-7segment"
  },
```
emm the second should be 4位七段数码管，not 7段

**Comment by urish** [comment]
Thanks! Added the new text and fixed the issue with two "七段数码管".

Here's the updated translations file, for reference. I changed the file format since the initial version: https://gist.github.com/urish/c59fe0e45fed189908e2bc292a252903

**Comment by urish** [comment]
Closing this issue for now - feel free to reopen (or open a new one) when you have new translation.

(You can follow #221 to get updates whenever we add new texts for translation)
