### ISSUE TITLE
VotePowers Log links to voting page have incorrect anchor URL

### ISSUE THREAD

**Issue by sutaburosu** [wokwi/wokwi-features#212]
**Description**
When clicking the `vote` button on the VotePowers Log, the page should scroll to the issue in question. The links are of the form `features#number`, but the individual issues don't have anchors in this format.

**To Reproduce**
Click any `vote` link. This requires scrolling down to find the voting link.  

**Expected behavior**
The `vote` link on the Log should link to `https://wokwi.com/features#feature-1002593625` rather than `https://wokwi.com/features#1002593625`

**Environment (please complete the following information):**
All

**Comment by urish** [comment]
Fixed! thanks for reporting :)
