### ISSUE TITLE
Copy/Pasting Components

### ISSUE THREAD

**Issue by ghost** [wokwi/wokwi-features#215]
It would be good to be able to highlight a component (or shift-click to highlight a set of components) and Ctrl+C / Ctrl+V it in the sim window.

**Comment by urish** [comment]
Thanks for the suggestion! I opened it for [voting](https://wokwi.com/features#feature-1033809342)

How about a "Duplicate" function? where you select a component (or perhaps several ones), and press some keyboard shortcut (e.g. Ctrl+D) to create a copy?

**Comment by ghost** [comment]
Yes, that would be just as helpful! Imagine having a button an LED and matching resistors set up correctly, then being able to highlight the set and just Ctrl+D them all and now you have 2, 3, 4, 5 of everything in a matter or a second or two. Saves clicking in the menus. 

For that matter, being able to shift-click to highlight several items and move them all together as a set would be just as helpful (maybe it needs a separate ticket?)

All the best, 
Steve

**Comment by urish** [comment]
Yes, a separate ticket for that would be best.

what I do when I want to quickly duplicate components is go to diagram.json and duplicate the relevant section. The [power editing keyboard shortcut](https://docs.wokwi.com/keyboard-shortcuts#power-editing-keys) are very useful for this, especially _Duplicate line below_. You'd still have to change the IDs of the duplicate element (e.g. from led1 to led2, led3, led4, etc.), but it's still a big time saver when you need to add many copies at once. But this is pretty advanced, I definitely see why new users will feel more comfortable with what you suggested.

**Comment by urish** [comment]
Closing as we now have the "D" keyboard shortcut for duplicating components. Thanks everyone who voted and supported this feature!

Regarding the multi-select, it's now tracked in #390 .
