### ISSUE TITLE
Simple Labels/Notes in the Sim Window

### ISSUE THREAD

**Issue by ghost** [wokwi/wokwi-features#216]
Sometimes with lots of LEDs/Buttons, it can get confusing to remember what buttons are meant to do what. It would be cool to be able to add a small note (like a resizable/minimisable sticky note) so you can label things like buttons or leave a small message explaining something.

**Comment by urish** [comment]
Thanks for the suggestion Steven!

We already have a similar request in #43, so closing this as duplicate.

Specifically for LEDs and Push buttons, you can already add a "label" attribute with some text to display below the LED/button. 

Some examples:
- [Bouncing vs non-bouncing buttons](https://wokwi.com/arduino/projects/288681423014986248) - each button has a label below it
- [Arduino Alarm Clock](https://wokwi.com/arduino/projects/297787059514376717) - the Hours / Minutes / Alarm buttons are labeled

**Comment by ghost** [comment]
Ah great! Apologies for not finding the existing one first! 

All the best, 
Steve
