### ISSUE TITLE
Firefox mobile version is not loading properly

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#219]
Since morning, the firefox mobile version (mobile devices, mobile view in desktop) doesn't load the page properly. An empty simulator window is shown. 
![Uploading IMG20211027153406.jpg…]()

**Comment by urish** [comment]
Fix is up - can you please test and report back?

**Comment by matititam** [comment]
Works wonderful now

**Comment by urish** [comment]
Thanks, then we can close this issue
