### ISSUE TITLE
Add Raspberry Pi 4 simulator

### ISSUE THREAD

**Issue by apage-pi** [wokwi/wokwi-features#230]
**Is your feature request related to a problem? Please describe.**
Sort of. I sometimes need to simulate the Raspberry Pi 4 when I'm coding (particularly Arduino).

**Describe the solution you'd like**
An RPi 4 simulator with the ability to run Python and control an Arduino UNO/MEGA or RPi Picoalongside it at the same time using their respective languages (Python for RPi 4 and Pico, Arduino IDE for Arduino UNO/MEGA).

Thanks,
    --Adam

**Comment by urish** [comment]
Hi Adam, thanks for the request!

Unfortunately, the Raspberry Pi 4 is too complex to accurately simulate in the browser while maintaining good user experience. It's currently out of scope for Wokwi.
