### ISSUE TITLE
Add ST NUCLEO64-F0/L0 board support

### ISSUE THREAD

**Issue by SebCanet** [wokwi/wokwi-features#235]
Thanks a lot for this great project!
To be a complete microcontroller simulator, I think you should add at leaste the 3 generic board from ST: nucleo32, nucleo64 & nucleo128.
Even if microcontroller is not exactly the same, at last it would be a starting point (and anybody could tweak to change few elements like memory size, etc) because pinout and features in same product range are similar.
Thanks.

**Comment by urish** [comment]
Hi Seb, thanks for the feature request!

If you had to choose one board, which one would you go with?

**Comment by SebCanet** [comment]
Even if ST is working on a board for education (https://www.st.com/en/evaluation-tools/p-nucleo-wb55.html), I think Nucleo64 is a good starting point as it's same pinout than Arduino Uno.

**Comment by urish** [comment]
Thanks! Do you know to tell anything about the popularity of the different Nucleo64 variants ([source](https://www.st.com/resource/en/user_manual/um1724-stm32-nucleo64-boards-mb1136-stmicroelectronics.pdf))?

<img width="423" alt="image" src="https://user-images.githubusercontent.com/892318/145004711-49a23cd3-840c-4ff0-8de1-e45f44777d88.png">

**Comment by SebCanet** [comment]
I think the L476RG is a good candidate., or F401RE.
Arduino IDE can compile to it now, with STM32Duino project: [https://github.com/stm32duino](https://github.com/stm32duino)

**Comment by urish** [comment]
How useful are the F0/L0 series (F030R8, L010RB, etc.)?

**Comment by SebCanet** [comment]
Not expert, I cannot answer...sorry.

**Comment by urish** [comment]
That's okay. I'm asking because F0/L0 are based on Cortex-M0 core, which is already implemented as part of the [RP2040 emulator](https://github.com/wokwi/rp2040js). So they will probably be faster to implement (weeks instead of months of work).

**Comment by SebCanet** [comment]
Good idea! That's a great starting point, many thanks!

**Comment by urish** [comment]
Alright, I opened this feature request for [public voting](https://wokwi.com/features#feature-1073107644). Let's see how it goes!

**Comment by urish** [comment]
Closing as this hasn't got any votes in the past 6 months.
