### ISSUE TITLE
Simulate LCD TFT 3.2" (SPI protocol)

### ISSUE THREAD

**Issue by jordelsonjunior** [wokwi/wokwi-features#239]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by urish** [comment]
Thanks for the request Jordel!

Do you have the exact LCD model number that you'd like to see?

We already have the ILI9341 ([docs](https://docs.wokwi.com/parts/wokwi-ili9341) / [docs in Portuguese](https://docs.wokwi.com/pt-BR/parts/wokwi-ili9341))

**Comment by jordelsonjunior** [comment]
Eu gostaria de testar a biblioteca TFT_eSPI library, disponível em https://github.com/Bodmer/TFT_eSPI, para esp32 e o LCD mencionado. Seria possível?

**Comment by urish** [comment]
We don't have SPI for the ESP32 yet, so I guess it won't work until we add the SPI. 

You can track the status of ESP32 peripherals (including SPI) here: https://docs.wokwi.com/guides/esp32#simulation-features

**Comment by urish** [comment]
We now have SPI on the ESP32!

Here's an example with TFT_eSPI: https://wokwi.com/projects/325427785333998162

**Comment by steve-barth** [comment]
That's great! Thanks!Steve. Uri Shaked ***@***.***> ezt írta (2022. márc. 27. 0:35):
We now have SPI on the ESP32!
Here's an example with TFT_eSPI: https://wokwi.com/projects/325427785333998162

**Comment by FernandoGarcia** [comment]
Hi @urish!

Thanks for your job!

Could you add "TFT_eWidget" library for this example?

**Comment by urish** [comment]
Hello, unfortunately, I do not have the bandwidth to create such example. You can try asking on the [Wokwi discord community chat](https://wokwi.com/discord), people are pretty helpful around there and perhaps someone will be able to take one of the "TFT_eWidget" library examples and run it in Wokwi.
