### ISSUE TITLE
Could you add a frozen glass effect for neopixel matrix

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#24]
Link reference: https://github.com/FastLED/FastLED/issues/1076

The request is below:

> 
> Some people make matrix-based table lamps and screens. Could you add a frozen glass (light scattering) effect on top of the matrix? It would help to see the light effect live, like on a lamp.
> 
> Our project in progress https://github.com/DmytroKorniienko/FireLamp_JeeUI/tree/dev
>

**Comment by urish** [comment]
Hello @kostyamat, can you please give a photo or more details of what you want to effect to look like?

We currently have an ability to blur. Compare this (pixelated):

![image](https://user-images.githubusercontent.com/892318/100556385-cf60f880-32aa-11eb-9633-7c609cfb9534.png)

vs this (blurry):

![image](https://user-images.githubusercontent.com/892318/100556393-ddaf1480-32aa-11eb-9981-c56666b215b8.png)

(demo from [this page](https://wokwi.com/arduino/libraries/FastLED/DigitalRain))

**Comment by kostyamat** [comment]
Hi. 
For example reworked "Fireworks" https://youtu.be/V-VqwKp6tXE, or any other on my YouTube channel.

**Comment by Puneethkumarsn** [comment]
voting to close this. Blue feature is sufficient and address 99% cases where a blur is needed
