### ISSUE TITLE
Add support for NeoPixels with other emitters mix

### ISSUE THREAD

**Issue by arduino12** [wokwi/wokwi-features#243]
**Is your feature request related to a problem? Please describe.**
NeoPixel elements only support RGB emitters (R=Red, G=Green, B=Blue),
But ther are many other **[LEDs](https://www.aliexpress.com/item/32550663121.html)** and [strips](https://www.aliexpress.com/item/1005001997801363.html) out there with RGBW, RGBWW, RGBNW, WW, CW, NW, WWA emitters!
W=ColdWhite(bluish), WW=WarmWhite(yellowish), NW=NatrualWhite, A=Amber(orange)

![image](https://user-images.githubusercontent.com/11454280/146656196-4068f6e6-2ea6-4f7b-aeef-66b61df0a4c6.png)

**Describe the solution you'd like**
Add a `type`/`colors`/`emitters` attribute to the NeoPixel LED and strip elements - the default will be RGB,
but the user can set it to RGBW for example -
(uses the SK6812 chipset that "takes" 32bits of color data instead of 24bits of the WS2812 - see the links above)
The letters order is also important - some NeoPixels have different RGB order.
Also adding NeoPixels to the [Docs page](https://docs.wokwi.com/parts/wokwi-rgb-led) will be useful :)

I have the RGBW and WWA LEDs and strip and they are very nice - the white looks much better than the WS2812 that have to combine RGB resulting in 3 separate shadows and poor mixed white color,
The slight disadvantage is that the blue emitter makes the white phosphor to glow a bit..

**Comment by urish** [comment]
Thanks for the detailed request, I opened this for [voting](https://wokwi.com/features)

**Comment by arduino12** [comment]
Closing this - lets merge it with the previous issue #240 - I renamed it to match the bigger general problem :)
