### ISSUE TITLE
Ability to move existing wires (dragging wire segments)

### ISSUE THREAD

**Issue by DiskDoctor** [wokwi/wokwi-features#244]
It would help organize diagrams if we could edit how the wires run by click and drag, similar to Visio allowing each segment to be moved.

Currently, when moving any component the wires reroute and may not be in the best locations for neatness and understanding. This requires a lot of wire delete, recreate, change color again in json.

Thank you.

**Comment by urish** [comment]
Great, I opened this for [voting](https://wokwi.com/features#feature-1086980412)

**Comment by leftCoast** [comment]
Can I add to this a color palette? Maybe a pop up or something? Just a few primary colors would do. Like maybe the resistor colors? Because once you can select them, you could do actions on them besides move them.

**Comment by urish** [comment]
> Can I add to this a color palette? Maybe a pop up or something? Just a few primary colors would do

That makes sense to me. Now let's hope this happens sometimes soon... :)

**Comment by urish** [comment]
This issue has been getting a lot of votes recently, so it's likely to make it to the top of the list soon!

**Comment by urish** [comment]
Initial version of selecting wires + user interface for setting colors is up!

![image](https://user-images.githubusercontent.com/892318/163889928-b1e9ba19-6d4a-4d59-b696-237c66cf3b64.png)

The numbers are keyboard shortcuts for the colors (so you can either use the mouse or the keyboard for the first ten colors), and the palette is based on the resistor colors, as suggested. The colors or design of the UI might change, based on the feedback I'll gather.

**Comment by urish** [comment]
Beta of wire dragging:

https://wokwi.com/projects/325427785333998162?__beta_dragwires=1

(it works with any project - just add ?__beta_dragwires=1 at the end of a URL)

when you select a wire, you'll see purple dragging handles. Click on them and move the mouse to drag the wire.

Currently missing: grid snapping. 

Also, wires with "\*" in the [wire placement instruction list](https://docs.wokwi.com/diagram-format#wire-placement-mini-language) may not drag correctly. But wires created with the UI never have "*" in their placement instruction list, so it should be less of a concern.

**Comment by djedu28** [comment]
> Initial version of selecting wires + user interface for setting colors is up!
> 
> ![image](https://user-images.githubusercontent.com/892318/163889928-b1e9ba19-6d4a-4d59-b696-237c66cf3b64.png)

Playing with an old project I saw this new functionality. It turned out great! Congratulations Urish. Thank you so much!!!!

**Comment by urish** [comment]
Grid snapping done!

Also improved support for paths with "\*", even though only the segments that come before the \"*\" are currently draggable.

**Comment by urish** [comment]
Thanks to @TimMathias, even connections with "*" should drag correctly.

**Comment by urish** [comment]
Wire dragging is now generally available.

**Comment by leftCoast** [comment]
Can we use the extra cash for this one to add a properties panel that EVERY part uses? I'd LOVE to ditch the entire edit jason thing.

**Comment by DiskDoctor** [comment]
> Wire dragging is now generally available.

SWEET! Thank you

**Comment by urish** [comment]
>  I'd LOVE to ditch the entire edit jason thing

I think, at least for resistors, LEDs, Push buttons - we should. They are very common.

**Comment by leftCoast** [comment]
Well, that's a good start. Is it reasonable to achieve?

**Comment by urish** [comment]
I believe so!

**Comment by urish** [comment]
LEDs:

![led-editor](https://user-images.githubusercontent.com/892318/174044380-ed915117-866d-466b-93fe-c4a22b8805f0.gif)

**Comment by leftCoast** [comment]
Love it!!

**Comment by leftCoast** [comment]
Looking at this, flip is a good addition! How about adding rotate?

**Comment by urish** [comment]
Thanks! Well, once COVID goes away from here :)

**Comment by leftCoast** [comment]
You guys still dealing with Covid? Sorry, I didn't know.

**Comment by MauriceDuteau** [comment]
I am still learning my way around your system but am very impressed. I have an open source building automation system called T3000, it is fairly active on github. We need many of the features you guys have and are working on.  I will learn more about your system and I am sure there will be some areas we can cooperate on. 

https://github.com/temcocontrols/T3000_Building_Automation_System

**Comment by AriellaE** [comment]
New interface for editing pushbuttons:

https://user-images.githubusercontent.com/35613240/177746341-5a4cc3b4-1bc5-435f-80b8-4e7c2678a4f4.mp4

**Comment by leftCoast** [comment]
That's great! Very handy!

Why are the number of colors to choose for buttons different than for LEDs?

**Comment by urish** [comment]
Update: it's now also possible to drag the first/last segments of the wires

**Comment by urish** [comment]
Closing, as the requested functionality has been implemented + some nice extras (wire editor, LED editor, push button editor).

**Comment by i-ymka** [comment]
Landed here looking for the same thing. Since Wokwi still has no built-in auto-router, I ended up building an open-source one: give it a Wokwi diagram (or a simple parts+wires spec) and it returns a clean, grid-aligned, overlap-free layout with no manual dragging. https://github.com/i-ymka/wokwi-autoroute — or `npx wokwi-autoroute board.json -w`. Leaving it here in case it helps others who find this issue.
