### ISSUE TITLE
Add the components in the current zoom window of the simulator instead of default (0,0)

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#246]
While adding components, it is comfortable to get the components added in the window of simulator which is in focus (viewable area). If not, I have to always zoom out, go to (0,0) drag the component from there to my current location in the simulator window
![Wokwi Arduino github](https://user-images.githubusercontent.com/68117142/147132612-e8ca2cb0-1daf-4956-af72-b323d1eb79d5.gif)

**Comment by DiskDoctor** [comment]
This would be an excellent enhancement

**Comment by urish** [comment]
Done! Parts are now added to the center (more or less)

**Comment by DiskDoctor** [comment]
Perfect! It works great! Thank you.

**Comment by leftCoast** [comment]
Wait! PLEASE stagger new items. I mean while your on this. Adding them one on top of the other makes people think nothing was added. IE try adding 5 LEDs in a row. Looks like you only got 1.

**Comment by urish** [comment]
Yes,  I hear your pain :)

How would you suggest to implement staggering algorithm?

Right now, when you add a new part, we are looking at the screen's center (X/Y), and set the "left" / "top" properties of the new part according to that.

**Comment by DiskDoctor** [comment]
> Wait! PLEASE stagger new items. I mean while your on this. Adding them one on top of the other makes people think nothing was added. IE try adding 5 LEDs in a row. Looks like you only got 1.

You better control that trigger finger ;)  But seriously, I've seen this issue with a number of WYSIWYG interfaces, including Visio. I don't think they figured out a simple way to do it, either. 

Unless there is some way to flash an item the moment it is added? That would be the visual cue that a new part was added.

**Comment by urish** [comment]
quoting from the discussion on Discord:

> when we add a new part, we currently have the following info:
> - all existing parts and their x/y positions (but not their sizes)
> - x/y positions of viewport (visible area)
>
> the previous algorithm was:
> `take the minimum of all existing parts x/y`
> so the part would always end up in the top-left corner of the diagram, regarding of your current viewport (visible area)
>
> the new algorithm is:
> `set the top/left to the center of the viewport (visible area)`
>
> how would you suggest to change it?

**Comment by DiskDoctor** [comment]
If you have x/y of all parts and visible area of viewport, perhaps you can find the top-est, left-est x/y of any part in the visible area, and any added item will be x+5, y-5 of that part? 

That would stagger any duplicate part added at the same time.

Downside is it will place new parts over top of your current diagram parts. Is that bad? (workaround is to move first part to top left and new parts would start there)

Caveat- if no parts in the visible area, would have to trap that condition and drop the first part in the middle.

What do you think?

**Comment by urish** [comment]
Alright, we now have staggering + as @matititam suggested, the parts start at the top left corner (rather than in the middle)

**Comment by leftCoast** [comment]
Lets try it and see how it goes.
