### ISSUE TITLE
wokwi-tv no longer works with wokwi-pi-pico

### ISSUE THREAD

**Issue by sutaburosu** [wokwi/wokwi-features#254]
[The tv-pong sketch on Pico](https://wokwi.com/arduino/projects/301402156123030026) used to work. Now it doesn't.

Projects using wokwi-tv on other microcontrollers continue to work fine.

In Firefox just a black screen is the result. In Chromium I get "error in diagram.json" and this in the console. ![image](https://user-images.githubusercontent.com/20606/147950172-8bb2a7e5-d4e8-4265-a8cd-32ea09fb2a6f.png)

**Comment by urish** [comment]
Thanks for reporting! It doesn't reproduce for me (tried both Chrome and Firefox). Are there any other projects where the issue reproduces for you?

**Comment by sutaburosu** [comment]
Adding a TV element to any Pico sketch triggers it for me [even without wiring it up](https://wokwi.com/arduino/projects/319829160639857235).

This only seems to affect Chromium v96. I can't reproduce it in Chrome v96. Very odd.

If I'm reading it correctly it's trying to assign 768 * 576 Uint32s to an array of 767 * 576 * 4 Uint8s, which indeed does not fit. The `width: 767` seems it may be relevant, but I don't know where that is coming from.
![image](https://user-images.githubusercontent.com/20606/148012950-f1520633-e4f8-4aa3-aad3-513783c86f46.png)

Ah! If I use the inspector to modify the TV's canvas to be 769 wide, no exceptions occur. So this is a bug in Chromium which is not present Chrome?

I've noticed [this Pico Pong project](https://wokwi.com/arduino/projects/304031382352429632) works flawlessly in Chromium. The ImageData from the canvas is the correct size. I'm even more puzzled now, and I don't know how to debug this further.

**Comment by sutaburosu** [comment]
I'm pretty sure this is caused by a bug in Chromium, so there's no need to have it cluttering up your issue tracker. I can always re-open it if I ever find evidence to implicate Wokwi. :)

**Comment by urish** [comment]
Thank you!
