### ISSUE TITLE
The :purple_heart: loved status of a project isn't shown when reloading the page

### ISSUE THREAD

**Issue by sutaburosu** [wokwi/wokwi-features#255]
**To Reproduce**
Load any project and press :purple_heart:. You can now see this heart on the makers' projects page. Reloading that project later still shows a white heart.

**Expected behaviour**
The heart should be purple, not white, when loading projects we loved previously.

**Comment by urish** [comment]
Thanks for reporting, I uploaded a fix. Can you please check now?

**Comment by sutaburosu** [comment]
Yes, that works. Thanks. :+1:
