### ISSUE TITLE
Share button should grab only relevant link to share the project with others

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#259]
When I try to share the project with others, especially when the address bar is not just Wokwi project path but also relevant tracking content, I feel it doesn't look good. 
Here is the image telling what I mean..

Can we cut the address to the relevant content only when we try to "share" the project?
Thanks
![Wokwi Arduino simulator 23](https://user-images.githubusercontent.com/68117142/148584621-c5281a5e-9d82-408e-bc29-244c62e0d434.gif)

**Comment by urish** [comment]
Should be fixed now. Can you please verify?
