### ISSUE TITLE
hard Refresh also doesn't load the complete project

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#26]
**Link**: https://wokwi.com/arduino/projects/283991385282970124

1. After doing minor changes in the digram.JSON file I saved it
2. I now clicked on the save button
3. Now, if I reload the page, all my changes were gone
4. I also tried `Ctrl` + `Shift` + `R`
5. If I open the same link in Stealth mode or on another browser, I can see all my latest changes

![image](https://user-images.githubusercontent.com/68117142/101182170-c6d63c80-3673-11eb-955c-c43ca5b709c1.png)

**Comment by Puneethkumarsn** [comment]
**Second update:**

1. I saved the design by clicking on the 'Save' button
2. And did `Ctrl` + `Shift` + `R`
3. Diagram.JSON file lost all the changes and loaded the old status/random old status contents

![image](https://user-images.githubusercontent.com/68117142/101183426-84adfa80-3675-11eb-811a-819578a5cb23.png)

**Comment by urish** [comment]
Thanks for reporting! I deployed a fix - it might need to refresh twice, but it should hopefully improve the situation. Can you please try and let me know?

**Comment by Puneethkumarsn** [comment]
It looks okay now 👍 I don't know why but the update indeed happened only with the second hard refresh.

**Comment by urish** [comment]
Yes, it happens because of stale cache. I hope to fix that in the future as well...
