### ISSUE TITLE
Code window loses horizontal scroll below about 50%

### ISSUE THREAD

**Issue by DiskDoctor** [wokwi/wokwi-features#261]
When split screen between code window and diagram window is changed by dragging vertical split to the left, as code window drops below a certain amount (50%?) or more, the horizontal scroll bar in the code window disappears.

Problem: Cannot scroll and see code in the window

**Comment by urish** [comment]
Doesn't reproduce for me. It could be that I do not understand the instructions very well.

What browser do you use?
Mind sharing a screen recording showing the issue in action?

**Comment by DiskDoctor** [comment]
Two screenshots. First has the horizontal scroll bar at bottom of code window.

Second shows scroll bar missing at the bottom of the code window. Appears when the vertical split is dragged left until the TABS at the top of the code window are wrapped, then the scroll bar disappears, too.
![hscroll_okay](https://user-images.githubusercontent.com/96539478/148633383-ac12655b-bd59-42ff-9c4d-b9e3a5652bb3.PNG)

Win 10 pro, Chrome
![hscroll_gone](https://user-images.githubusercontent.com/96539478/148633388-8bc517b2-6d4b-4a03-87f9-4bcba6bf0849.PNG)
.

**Comment by sutaburosu** [comment]
This happens in both Chromium and Firefox for me. The key to triggering it is to make the list of tabs span onto another line. I guess the scrollbar is scrolling off the bottom of the view port. Temporarily resizing the browser window brings the scrollbar back.

**Comment by DiskDoctor** [comment]
I agree. Resizing larger OR smaller brings back scrollbar. Can it be fixed?

**Comment by urish** [comment]
> The key to triggering it is to make the list of tabs span onto another line

Good catch. Now this reproduces for me!

**Comment by urish** [comment]
Uploaded a fix - can you please test and report back?

**Comment by sutaburosu** [comment]
Works great here for me. Thanks, Uri. :heart:

**Comment by urish** [comment]
Great, thanks for helping me figure this out!

**Comment by DiskDoctor** [comment]
Looks good here! Thanks
