### ISSUE TITLE
MicroPython examples for the Homepage

### ISSUE THREAD

**Issue by urish** [wokwi/wokwi-features#265]
Let's add a section with 3 MicroPython examples (e.g. https://wokwi.com/arduino/projects/300504213470839309)

**Comment by bhavesh-k** [comment]
Would you like to cross post my tutorials for this? I have been using Wokwi and Micropython on the Pico for this. Tutorials are currently on my website at https://bhave.sh. 

For e.g the first one https://bhave.sh/micropython-blink-led

Right now I have 4 tutorials published

**Comment by urish** [comment]
Closing as we now have https://wokwi.com/micropython
