### ISSUE TITLE
DHT22 is not working with ESP32

### ISSUE THREAD

**Issue by yepher** [wokwi/wokwi-features#266]
**Describe the bug**
DHT22 is producing data but ESP32 is not decoding it

**To Reproduce**

* [Sample Project](https://wokwi.com/arduino/projects/320219663593112146)

1. Create ESP32 project on Wokwi
2. Add a DHT22 and wire:
    * VCC->DHT VCC (pin1)
    * VCC->10KΩ resitor pullup to DHT Data (pin2)
    * DHT Data (pin2) -> D4
    * GND->DHT22 GND (pin3)
3. Copy sample code from [Adafruit DHT-sensor-library]( https://github.com/adafruit/DHT-sensor-library/tree/master/examples)
4. Run project and note output reports `Error reading...`

**Expected behavior**

Read data from the sensor and report to the console.

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser [chrome and safari]

**Additional context**

Looks like DHT22 is doing the right thing and that the ESP32 is not interpreting it properly

<img width="1683" alt="dht_logicAnalyzer" src="https://user-images.githubusercontent.com/1359331/148647153-0ddec710-80bb-447d-b9b9-cb48895623e3.png">

*diagram.json*

```
{
  "version": 1,
  "author": "Anonymous maker",
  "editor": "wokwi",
  "parts": [
    { "type": "wokwi-esp32-devkit-v1", "id": "esp", "top": 13.99, "left": -57.33, "attrs": {} },
    {
      "type": "wokwi-dht22",
      "id": "dht1",
      "top": -22.33,
      "left": 143.16,
      "attrs": { "temperature": "7.8" }
    },
    {
      "type": "wokwi-resistor",
      "id": "r1",
      "top": 187.23,
      "left": 89.58,
      "attrs": { "value": 10000 }
    },
    { "type": "wokwi-logic-analyzer", "id": "logic1", "top": -71.87, "left": 241, "attrs": {} }
  ],
  "connections": [
    [ "esp:TX0", "$serialMonitor:RX", "", [] ],
    [ "esp:RX0", "$serialMonitor:TX", "", [] ],
    [ "esp:GND.1", "dht1:GND", "black", [ "h0" ] ],
    [ "esp:3V3", "r1:1", "red", [ "v-0.0", "h33.91" ] ],
    [ "esp:D4", "dht1:SDA", "green", [ "h0" ] ],
    [ "logic1:GND", "esp:GND.1", "black", [ "h-25.88", "v146.12" ] ],
    [ "logic1:D0", "dht1:SDA", "green", [ "h0" ] ],
    [ "logic1:D1", "dht1:VCC", "green", [ "h0" ] ],
    [ "r1:2", "dht1:VCC", "green", [ "v0" ] ]
  ]
}
```

**Comment by yepher** [comment]
This comment in the DHT lib may provide a clue

Summary: use `digitalRead(_pin)` instead of `(*portInputRegister(_port) & _bit)`

```
// Otherwise fall back to using digitalRead (this seems to be necessary on
// ESP8266 right now, perhaps bugs in direct port access functions?).
```

[DHT.cpp#L378](https://github.com/adafruit/DHT-sensor-library/blob/master/DHT.cpp#L378]

**Comment by yepher** [comment]
I created this code to try and isolate the issue:

[DHT22 Hacked Demo](https://wokwi.com/arduino/projects/320228847292252754)

Mine failed at Failed: cycles[76]

```

Simulation
Max Timeout: 4294967295
pullTime: 55
maxCycles: 80000
Failed: cycles[76]

Cycles Dump

0x14 0xA 0x13 0xB 0x13 0xA 0x14 0xA 0x14 0xA 0x14 0xA 0x15 0xB 0x39
0xE 0xC 0x1C 0x14 0xA 0x14 0xA 0x13 0x1D 0x13 0xA 0x14 0xA 0x14 0xA 
0x14 0xA 0x14 0xA 0x13 0xC 0x2D 0x17 0x1F 0xA 0x14 0xA 0x13 0xB 0x13 
0xA 0x14 0xA 0x14 0x1A 0x7 0xB 0x13 0x1C 0x14 0x3C 0x1C 0x7 0x13 0xA 
0x13 0x1D 0x13 0x1D 0x13 0xA 0x14 0x1C 0x14 0x1C 0x14 0x1C 0x14 0x32 
0x26 0x6
```


<img width="1369" alt="Screen Shot 2022-01-08 at 9 39 22 AM" src="https://user-images.githubusercontent.com/1359331/148650355-09064493-1382-474b-839b-097c15058b62.png">


[DHT_FAIL_CYCLE_76.vcd.zip](https://github.com/wokwi/wokwi-features/files/7833478/DHT_FAIL_CYCLE_76.vcd.zip)

**Comment by yepher** [comment]
Added pulse in expect.

[Wokwi Project](https://wokwi.com/arduino/projects/320228847292252754)

Expect Logic:

```
uint32_t expectPulse(bool level) {

  uint32_t count = 0;

  digitalWrite(ESP_OUT_REF, HIGH);
  digitalWrite(ESP_OUT_REF, LOW);
  
  // Otherwise fall back to using digitalRead (this seems to be necessary on
  // ESP8266 right now, perhaps bugs in direct port access functions?).
  while (digitalRead(DHTPIN) == level) {
    if (count++ >= _maxcycles) {
      return TIMEOUT; // Exceeded timeout, fail.
    }
  }

  digitalWrite(ESP_OUT_REF, HIGH);
  digitalWrite(ESP_OUT_REF, LOW);

  return count;
}

```


```
Max Timeout: 4294967295
pullTime: 55
maxCycles: 80000
Failed: cycles[78]

Cycles Dump

0x10 0x7 0x10 0x7 0x10 0x7 0x10 0x7 0x10 0x6 0x11 0x6 0x12 0x8 0x36 
0xA 0x9 0x19 0x10 0x6 0x11 0x6 0x10 0x19 0x10 0x7 0x10 0x7 0x10 0x7 
0x10 0x7 0x10 0x6 0x11 0x8 0x29 0x14 0x1C 0x6 0x10 0x7 0x10 0x6 0x11 
0x6 0x10 0x7 0x10 0x19 0x10 0x7 0x10 0x7 0x10 0x19 0x10 0x38 0x19 0x4 
0x10 0x7 0x10 0x19 0x10 0x19 0x10 0x6 0x11 0x18 0x10 0x19 0x10 0x19 0x10 
0x2F 0x23 0x3
```


<img width="1854" alt="Screen Shot 2022-01-08 at 10 21 40 AM" src="https://user-images.githubusercontent.com/1359331/148651734-0c993d10-6546-4e35-8cd7-d98e3b2102f3.png">

[timeout_with_marker.zip](https://github.com/wokwi/wokwi-features/files/7833548/timeout_with_marker.zip)

**Comment by urish** [comment]
Thanks for digging into this! Seems like the code is misses some of the pulses from the DHT sensor - there are several spot where you can see some data on the DHT line, but the ESP Ref spot misses them.

**Comment by lazaroofarrill** [comment]
I've had lots of trouble using DHT library with an actual ESP32.
[This library](https://github.com/beegee-tokyo/DHTesp) solved it.

**Comment by urish** [comment]
Testing the DHT Unified Sensor library on an actual ESP32 with a DHT22 sensor:

![image](https://user-images.githubusercontent.com/892318/150654201-dcfd11a3-2378-4276-93b8-cb7b5fd527bf.png)

Test setup:

![image](https://user-images.githubusercontent.com/892318/150654223-deb0511e-f8b0-4f7b-99fd-255ad0a31b10.png)

This is still better than the simulation - in the simulation it always fails reading from the sensor, in real life about 10-15% of the time.

**Comment by urish** [comment]
Closing this is this seems to be a problem of the library, and not the simulator.

For anyone who is trying to use the DHT22 on the ESP32, here's the "DHT sensor library for ESPx" suggested by @lazaroofarrill that does work. Here's an example project (I'll also put the link in the docs):

https://wokwi.com/arduino/projects/322410731508073042
