### ISSUE TITLE
Arduino LED is not blinking

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#27]
Hi There

https://wokwi.com/arduino/projects/284084336653763080

I am not able to see the LED blinking in this particular simulation.

Thank you
Puneeth

**Comment by urish** [comment]
Seems like this happens when nothing is connected to pin 13 / GND, working on a fix

**Comment by urish** [comment]
Fix is on its way...

**Comment by urish** [comment]
Fixed! Thanks for reporting :-)
