### ISSUE TITLE
Missing German translations

### ISSUE THREAD

**Issue by lazyzero** [wokwi/wokwi-features#271]
project.shareDialog.title:
- source: Share Project
- translation: 

project.shareDialog.copyToClipboard:
- source: Copy to clipboard
- translation: In die Zwischenablage kopieren

project.shareDialog.pleaseSave:
- source: To share this project, please save it first:
- translation: Um diese Projekt zu teilen, bitte zuerst speichern:

project.shareDialog.saveButton:
- source: Save projet
- translation: Projekt speichern

project.shareDialog.closeButton:
- source: Close
- translation: Schliessen

**Comment by AriellaE** [comment]
Thank you @lazyzero!
No need to translate project.shareDialog.title: (source: Share Project)?

**Comment by lazyzero** [comment]
Ups, I missed it:

project.shareDialog.title:

source: Share Project
translation: Projekt teilen

**Comment by AriellaE** [comment]
Thank you!

**Comment by urish** [comment]
Translations updated. Thanks!
