### ISSUE TITLE
Multimeter or Amperometer and Voltmeter component

### ISSUE THREAD

**Issue by alessionossa** [wokwi/wokwi-features#273]
I want to check the current and voltage in my circuit but there is no Multimeter, Amperometer or Voltmeter.

**Describe the solution you'd like**
Add new component (or multiple components) to measure current and voltage

**Comment by urish** [comment]
Hi Alessio! 

Thanks for opening this request.

Wokwi simulator is digital, so there's no current / voltage simulated. I'm closing this issue, as these instruments (Multimeter, Ampermeter or Voltmeter) are not useful before we have full analog simulation. 

If you are interested, you can open a different request for Analog simulation (should also solve #203), and if it gets to the [top of the feature list](https://wokwi.com/features), we'll start working on it.
