### ISSUE TITLE
Sming Framework based applications

### ISSUE THREAD

**Issue by slaff** [wokwi/wokwi-features#274]
[Sming Framework](https://github.com/SmingHub/Sming) is a open source embedded C/C++ framework with Arduino compatibility.
It supports multiple architectures such as Esp32, Esp8266 and RP2040 among others. And it would be awesome if the Sming users and developers can design and test their work on Wokwi simulator before flashing it on their micro-controllers.

As far as I can see at the moment there are "templates", ex: https://wokwi.com/arduino/new?template=micropython-esp32, that describe the preinstalled software and emulator. Can you give us hints how to add Sming as a template?

**Comment by urish** [comment]
Hi Slaff,

Nice to meet you!

Can you please prepare a Wokwi project that uses Sming and you'd like to see as a new template?

**Comment by slaff** [comment]
Hi Uri

> Can you please prepare a Wokwi project that uses Sming and you'd like to see as a new template?

I would love to prepare such a project but I don't know how. Is there a documentation how to do this? We have an installer that is installing the needed tool-chain (compiler, SDK, build tools, etc) per architecture. Can we describe what needs to be installed, what ENV settings to put and so on? Something like Dockerfile ?

**Comment by urish** [comment]
Can one use the Arduino toolchain to build Sming projects? 

Or does it need a different setup?

**Comment by slaff** [comment]
> Can one use the Arduino toolchain to build Sming projects?

For all architectures Smings needs git to fetch libraries on demand.

For Esp32
-------------
Sming uses ESP-IDF v.4.3.1 and installs the same tools as the ESP-IDF installer for this version. In addition Sming needs python version >3.5. 
So back to your question  - if Arduino for ESP32 is using the same ESP-IDF version then things should work.

For Esp8266 
-----------------
Sming uses a GCC compiler similar to the one used in Arduino for ESP8266.  Sming requires NON-OS SDK 3.0.1 and as far as I know Arduino for ESP8266 is still using a 2.x SDK so here things will break :(

**Comment by urish** [comment]
Looking at the documentation (and your comments), it looks like Sming does need its own build environment - you can't build Sming projects only using the Arduino CLI. Is that correct?

**Comment by slaff** [comment]
>  Is that correct?

Yep, this is correct.

**Comment by urish** [comment]
Got it. The main issue is that the build server only supports the Arduino CLI at the moment. There's been some [interesting discussion on discord](https://discord.com/channels/787627282663211009/787630013658824707/926591631149383700) about adding support to third party build processes, with the two main points being security and performance.

What makes you interested in getting Wokwi to support Sming projects?

**Comment by slaff** [comment]
> What makes you interested in getting Wokwi to support Sming projects?

It looks like a great fit for designing and testing applications on Esp32's emulator. Should save development time,  spare the Flash memory on the real device and in addition make it easy to visually demonstrate and share a device or/and application. For development we have already a [Host emulator](https://sming.readthedocs.io/en/latest/arch/host/index.html) that can help the developer create and test their code. But it cannot help them test integration with sensors. And here is where your emulator shines :)

**Comment by urish** [comment]
Got it, thanks for the feedback (and the kind words). 

Right now, there's a possibility to load a pre-built binary file into the simulation: https://docs.wokwi.com/guides/esp32#custom-application-bin-file

Is this too complex/inconvenient for Sming users?

**Comment by slaff** [comment]
> Right now, there's a possibility to load a pre-built binary file into the simulation: https://docs.wokwi.com/guides/esp32#custom-application-bin-file

Ok, I tried it with the [Basic Blink](https://github.com/SmingHub/Sming/tree/develop/samples/Basic_Blink) sample and uploaded the generated [app.bin](https://github.com/wokwi/wokwi-features/files/7869377/app.bin.zip).  Interestingly enough the simulation is working :). See the image below and ignore the content in the editor window.

![image](https://user-images.githubusercontent.com/247452/149493017-e2fbf5e2-db48-464c-bc90-7ae1286c1517.png)

But some examples are more complex. For example here we have Spiffs ROMS and App Roms.

![image](https://user-images.githubusercontent.com/247452/149493819-1d962ab6-2bc0-4b16-8c49-177fe8e0fa44.png)

Will the emulator work if I pack them in one file with the appropriate offsets? What I mean is something like:
```
cat app.bin  \
     empty-480K.bin \
     user1.bin \
     user2.bin \
     spiffs0.bin \
     spiffs1.bin \
     spiffs2.bin \
     empty-24K.bin \
     partitions.bin  > flash.bin
```

If yes we, the Sming team, can think about adding tools to generate the flash.bin file for the wokwi emulator.

Slightly off-topic: It would be great if we can upload two mandatory things and one optional.
- Mandatory(hardware.json): Description of all used sensors, wiring and so on in one JSON or other proper format and the second. 
- Mandatory(flash.bin):  The complete flash memory WITH the bootloader config and WITHOUT WIFI and PHY settings. 
- Optional(ram.bin): RAM memory state (a snapshot that can get us started from where we have stopped).

If there is a possibility to add these files to a zip file with fixed names then wokwi has more or less everything needed to start/resume a simulation.

**Comment by urish** [comment]
> Interestingly enough the simulation is working :)

Happy to hear that!

> Will the emulator work if I pack them in one file with the appropriate offsets? What I mean is something like:

It might - the provided bin file is loaded at flash address 0x10000, unless the simulator detects there's a boot loader at the beginning, and then it's loaded at 0x0 or 0x10000. Worth giving it a shot.

> Slightly off-topic: It would be great if we can upload two mandatory things and one optional.

There's `diagram.json` file which specifies is the sensors, parts and connection. Is that what you mean?

As for ram.bin, how would that be generated? Can you tell me more about the use cases?

**Comment by urish** [comment]
@slaff have you lost interest?

**Comment by slaff** [comment]
> have you lost interest?

No, not at all. At the moment Sming binary firmware compiled on the PC could run on the web emulator. But it feels like second hand citizen. 

Can we help you build your docker image or whatever containers you are using so that your users can compile Sming applications directly in the browser? For a minimum compilation Sming will need a compiler(already available with ESP32 arduino), `make`, git and python 3 for some examples. The latter might also be optional. What differentiates Sming from Arduino for example in terms of compilation is that every library and Sming itself can be compiled with multiple different options and directives and that makes providing pre-compiled libraries for all library variants almost impossible.  
@mikee47 any ideas on providing a `minimum` Sming docker image?

**Comment by mikee47** [comment]
> ... @mikee47 any ideas on providing a `minimum` Sming docker image?

@slaff https://github.com/SmingHub/Sming/tree/develop/Tools/Docker/cli has the necessary

**Comment by urish** [comment]
Thanks! I'm looking into this now. The main challenges would probably be ensuring that:
1. The builds go fast. If a build takes more than a couple of seconds, it can be very frustrating for the users.
2. The builds environment is secure. We definitely do not want bad actors to run whatever stuff they want on our servers.

**Comment by urish** [comment]
Closing, as users can now use [Wokwi for VS Code](https://docs.wokwi.com/vscode/getting-started) to run their sming applications.

**Comment by slaff** [comment]
@urish we have integrated Wowki in Sming Framework. The documentation is here: https://sming.readthedocs.io/en/latest/experimental/wokwi.html.  It would be great if you can link this information to Wokwi's documentation: https://docs.wokwi.com/guides/esp32.

**Comment by urish** [comment]
Lovely, thank you! I added a link. Also, tried it - works great!

![image](https://github.com/wokwi/wokwi-features/assets/892318/f81af2c9-0201-47b5-9583-6dcfde87c2b3)

**Comment by urish** [comment]
One thing I noticed: in some cases, I had to run `make ide-vscode ENABLE_WOKWI=1 SMING_ARCH=Esp32` twice in order for the wokwi files to be generated

**Comment by slaff** [comment]
> in some cases, I had to run make ide-vscode ENABLE_WOKWI=1 SMING_ARCH=Esp32 twice

@urish thank you for reporting. I will investigate it...
