### ISSUE TITLE
TM1637 Support possible?

### ISSUE THREAD

**Issue by RandoSY** [wokwi/wokwi-features#279]
Would it be possible to implement TM1637 LED controller?
![open-smart-rich-shield-front](https://user-images.githubusercontent.com/609947/150221082-8478f4a8-1396-49f6-b036-259c34fd7a75.jpg)
![open-smart-rich-shield-back-696x696](https://user-images.githubusercontent.com/609947/150221130-7a6b1558-0ab0-43d3-ac31-682a49138466.jpg)

**Comment by urish** [comment]
Thanks for the suggestion! I opened it for [voting](https://wokwi.com/features?sort=newest#feature-1108603271)

**Comment by urish** [comment]
The TM1637 is now available in Wokwi.

- Documentation: https://docs.wokwi.com/parts/wokwi-tm1637-7segment
- Example: https://wokwi.com/projects/339227323398095442

**Comment by erichuang2013** [comment]
As https://wokwi.com/projects/339227323398095442 us "tm1637.h", do we have this file in repo? or refer to any other project in github?

**Comment by urish** [comment]
In the project you linked, the file comes from the Arduino library called "Grove 4-Digit Display" (see in the Library Manager tab). 

The sources for that Arduino library are hosted on GitHub: https://github.com/Seeed-Studio/Grove_4Digital_Display

**Comment by RandoSY** [comment]
So glad to see this implemented. Is there an issue with Decimal Point display? When I attempt to use libraries and examples that attempt them, the colon symbol is erroneously displayed on the screen. 

The TM1637 setup on the Open-Smart Rich Uno shield will do them OK, but I know there are issues with other modules ... 

Such a wonderful program, hard not to love ;)

**Comment by NewAbbreviations950** [comment]
Yeah I'm using the Pico SDK and the decimal points don't work. When sending the correct bytes to the tm1637 the bit corresponding to the dp segment doesn't seem to do anything.
