### ISSUE TITLE
Not a bug - Just a question

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#28]
is there any disadvantage or an issue if the code runs at a simulation speed higher than the real time?

![image](https://user-images.githubusercontent.com/68117142/101247655-c3f54d80-3740-11eb-8449-659913bc7b2c.png)

![image](https://user-images.githubusercontent.com/68117142/101247689-f30bbf00-3740-11eb-8adb-873b29536cc3.png)

**Comment by urish** [comment]
Not really - it might affect some programs (e.g. code the drive the buzzer). The code tries to keep the simulation speed at 100%, but achieving exactly 100% speed is impossible when you are running in a multi-tasking environment.

The ATtiny85 simulation runs at 8MHz, so it can run faster than Uno / MEGA
