### ISSUE TITLE
ILI9341 Seems to drag down the simulation a LOT.

### ISSUE THREAD

**Issue by leftCoast** [wokwi/wokwi-features#280]
**The issue**
ILI9341 Seems to drag down the simulation a LOT.

**You can see it here..**
When Drawing to the ILI9341 the simulation slows down and events are lost as it's spending much of its time seemly pushing pixels and not checking for "clicks" on the screen. Even trying to do simple animation drags it down really slow. To see this in action Open up the icon editor and try to do some "painting" Using a large brush. The % values drop typically to around 20% and updating dialog boxes can drop it down to around 10%.
https://wokwi.com/arduino/projects/320027251914572370

**Describe the solution you'd like**
I just want this to be Speedy Quick!

**Comment by urish** [comment]
Did some performance hunting today. Does it work any faster now?

**Comment by leftCoast** [comment]
It does seem faster. I can still see it refresh my pixels. (See that I'm doing a horrible job of optimizing the redraw.) :)

**Comment by urish** [comment]
Great. So we picked the low hanging fruits and got some performance gains already.

Shell we keep this open (for voting) or close as this is "good enough"?

**Comment by leftCoast** [comment]
Keep it open, its still kinda' painful for the icon editor. And it may end up being wrapped up in other streamlining stuff.

**Comment by leftCoast** [comment]
So I was playing with this today and it suddenly occurred to me. The slowdown I'm seeing now may NOT be the display, but the SD card. The example I gave is very SD card heavy in the code. The editing is done on the SD card not in RAM. SO there's a LOT of back and forth between the two.

**Comment by urish** [comment]
Closing as this got no votes in the past 6 months.
