### ISSUE TITLE
Tapping a components `?` link to docs doesn't work on mobile

### ISSUE THREAD

**Issue by sutaburosu** [wokwi/wokwi-features#281]
Tapping the `?` doesn't do anything. Connecting a Bluetooth mouse and clicking it works as expected. Could this simply be a missing touch event listener?

 - OS: Android 12L beta 2
 - Browser: Chrome 97

**Comment by urish** [comment]
How about now?

**Comment by sutaburosu** [comment]
Perfect! Thank you. :)
