### ISSUE TITLE
Speed up simulation for many individual Neopixels

### ISSUE THREAD

**Issue by WRPearse** [wokwi/wokwi-features#285]
I requested some advice on the discord server, and was suggested to open a feature request.
https://wokwi.com/arduino/projects/321405765995725394

I have a very large amount of individual neopixels (318 at this time). This causes the browser and simulation to run extremely slowly.

@urish indicated that this could be improved upon by optimizing for this use case.

**Comment by urish** [comment]
Open for voting: https://wokwi.com/features#feature-1111922510

**Comment by urish** [comment]
Closing, as this got no votes in the past six months.
