### ISSUE TITLE
Micropython simulator won't start.

### ISSUE THREAD

**Issue by apage-pi** [wokwi/wokwi-features#287]
The Micropython (Pi Pico) simulation will not startup

https://user-images.githubusercontent.com/72623953/151030663-23a8000a-f83e-4cb7-a44b-a3faceb55016.mp4

.

**Comment by urish** [comment]
Thanks for reporting!

Do other simulations work for you?

What browser/operating system are you using?

**Comment by sutaburosu** [comment]
@apage-pi Spamming the start button isn't going to help. Depending on the speed of your computer, internet connection and what is cached in your browser, it can actually harm things.
It would also be interesting to know what browser extensions you are using, and whether it works without any extensions enabled. An easy way to test a site without any extensions is to use Incognito/Private browsing mode.

**Comment by urish** [comment]
Closing as there is not enough information here to make this actionable.
