### ISSUE TITLE
Simulation issue: dipswitch prevents button from releasing.

### ISSUE THREAD

**Issue by jflamy** [wokwi/wokwi-features#292]
**Describe the bug**
Replacing a direct wire with a dipswitch prevents button from releasing.

**To Reproduce**

Project https://wokwi.com/arduino/projects/321969009680450132 is a subset of a documentation example. It uses a direct wire from a button to a pulled-up pin.  Works as expected (pressing the button shows pressed and released).

Project https://wokwi.com/arduino/projects/321962688253002322 adds a dipswitch -- but is otherwise identical.  This second project exhibits the bug.

Steps:
- start simulation
- click on dipswitch and type 8 to connect the button to the pin
- click on button
- observe that button is never released.

**Expected behavior**
Since the dipswitch is supposed to be a simple single throw switch, the switch should be the same as running a jumper.  The button should release.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome 97.0

**Additional context**
Putting the dipswitch between the button and the ground pin works.

**Comment by urish** [comment]
Thanks for reporting, fixed!
