### ISSUE TITLE
Project reappearing after being deleted

### ISSUE THREAD

**Issue by guillaume-dorczynski** [wokwi/wokwi-features#293]
Hello :)

**Describe the bug**
When I try to delete a project in My Projects page, the project disappears from the list, but reappears less than a second later (or sometimes when I refresh the page), I have to delete it one more time..! (and doing so, I think I've lost one or two projects deleted by mistake because I was confused)

**Expected behavior**
Of course it should be deleted once and for all

**Environment (please complete the following information):**
 - OS : Windows 10
 - Browsers : Chrome, Edge, Firefox
 - Version : Latest

**Additional context**
It's not a recent bug, I noticed it since I discovered Wokwi a few months ago

**Comment by sutaburosu** [comment]
I have noticed this too, but my understanding is that this is a temporary thing caused by caching. In my testing, if I delete a project and then reload the projects page twice, the deleted project no longer appears. Does this work for you too?

**Comment by urish** [comment]
Thanks for reporting, fixed!
