### ISSUE TITLE
SSD1306 on ESP32 - mirrored display?

### ISSUE THREAD

**Issue by kartben** [wokwi/wokwi-features#295]
**Describe the bug**
It would appear as if SSD1306 display is reversed on ESP32

![image](https://user-images.githubusercontent.com/128251/151842993-f035a68e-addd-4770-acf6-774fc40c888b.png)

**To Reproduce**

https://wokwi.com/arduino/projects/322316932640408148

**Comment by urish** [comment]
Looks like our SSD1306 implementation is missing the segment remapping feature:

![image](https://user-images.githubusercontent.com/892318/151844499-456a8c28-1db1-4fc4-bbd1-3913217e283e.png)

(from the [datasheet](https://cdn-shop.adafruit.com/datasheets/SSD1306.pdf))

**Comment by sutaburosu** [comment]
Another difference between this [beta library](https://github.com/ewertons/esp32-azureiotkit-sensors/blob/main/src/ssd1306.c#L268) and [Adafruit's SSD1306 library](https://github.com/adafruit/Adafruit_SSD1306/blob/master/Adafruit_SSD1306.h#L88-L89) is the row scan direction.

**Comment by urish** [comment]
Thanks @sutaburosu, I think you nailed it down. It wasn't the segment remapping, rather the row scan direction. Fix is up!

**Comment by kartben** [comment]
Wow that was fast. I can confirm the fix works (although not on the esp32.preview server yet, right?)

**Comment by urish** [comment]
Right, that one should update in roughly 5 minutes

**Comment by kartben** [comment]
aaand it works on the preview server too. Thanks again!

**Comment by v1d32** [comment]
I need mirrored how to make normal to mirrored?
