### ISSUE TITLE
MPU6050 does't work properly on ESP32 

### ISSUE THREAD

**Issue by kartben** [wokwi/wokwi-features#296]
**Describe the bug**

Running virtually any of the basic MPU6050 samples on ESP32 (using Adafruit-MPU6050) seems to show that the sensor is not properly working on the platform. Only accel_x seems to work

<img width="620" alt="image" src="https://user-images.githubusercontent.com/128251/151843581-bd831cec-291a-4588-aa85-d374dc020c07.png">

** Repro project **

https://esp32.preview.wokwi.com/arduino/projects/322322941068968530

**Additional context**

I have another app that is not using the Adafruit lib and that is also not behaving properly and it hangs when trying to initialize the sensor.

**Comment by urish** [comment]
Thanks for reporting! Can you please share a link to a project that reproduces the issue?

**Comment by kartben** [comment]
Sorry, I thought I had -- I have just updated the original bug desc

**Comment by kartben** [comment]
Maybe related: although the "loop()" in the repro project is only waiting for 10ms, and the simulation running at close to 100% speed, the traces on the serial console get updated only every 1sec or so, which is not the case using the exact same code in  an Arduino Uno AVR sim

**Comment by urish** [comment]
Turned out to be a bug in the ESP32 I2C Implementation. It wouldn't allow you to read more than 2 bytes in one go. 

Can you please test it again (against the esp32.preview branch)?

**Comment by urish** [comment]
Note: the preview branch has just been merged, so the fix should also be present on wokwi.com

**Comment by kartben** [comment]
That's much better, yes! Any idea about why the sensor reading is getting refreshed only every 1sec or so? Is there something with I2C on ESP32 being slower? This sample seems to demonstrate that I2C writes are indeed really slow: https://esp32.preview.wokwi.com/arduino/projects/322380195661087314

**Comment by kartben** [comment]
I just spotted another issue, that can be seen by running the same Adafruit lib sample as earlier (https://esp32.preview.wokwi.com/arduino/projects/322322941068968530):

```
  mpu.setAccelerometerRange(MPU6050_RANGE_8_G);
  Serial.print("Accelerometer range set to: ");
  switch (mpu.getAccelerometerRange()) {
  case MPU6050_RANGE_2_G:
    Serial.println("+-2G");
    break;
  case MPU6050_RANGE_4_G:
    Serial.println("+-4G");
    break;
  case MPU6050_RANGE_8_G:
    Serial.println("+-8G");
    break;
  case MPU6050_RANGE_16_G:
    Serial.println("+-16G");
    break;
  }```

does not work properly ("Accelerometer range set to: +-2G" where it should obviously say 8G). This works fine in the AVR sim.
I have no idea why is seems to work fine for the gyro range though, as they seem to have very similarly behaving registers.

**Comment by urish** [comment]
> This sample seems to demonstrate that I2C writes are indeed really slow:

The best way to look into it is hooking a [Logic Analyzer](https://docs.wokwi.com/guides/logic-analyzer).  Then you can actually see the time spend transmitting data over I2C.

In the first, faster example:

![image](https://user-images.githubusercontent.com/892318/151967321-7fede930-9e5b-455e-9ea3-706fc7efcd0f.png)

You can see each burst takes ~7ms.  Adding the 10 ms delay in your loop, you get about 17 milliseconds between updates (or about 60FPS). Also, the simulator is sleeping more than 50% of the time (in the delay loop), hence it can run the simulation faster.

However, looking at the slower example you'll see much more time is spent on the I2C communication:

![image](https://user-images.githubusercontent.com/892318/151967594-537b34dc-21f4-4742-b364-3bbc982c2137.png)

Here, each burst takes around ~60ms. So from the simulated time perspective, you should get a frame every 60 milliseconds (so around 16 FPS). However, this also means that simulator is busy most of the time (60 out of every 70 milliseconds), so the simulation runs slower and your actual FPS is way slower. The funny thing - if you bump the delay to let's say 100, the simulator speeds up and you still get the same result.

As far as I can tell, the reason for the slow down is that the ESP32 Arduino implementation busy waits for the I2C transmission to complete, so as long as data is transmitting, the simulated ESP32 is just busy burning CPU cycles. Unfortunately, there's not much we can do here in terms of performance.

**Comment by urish** [comment]
> I just spotted another issue, that can be seen by running the same Adafruit lib sample as earlier (https://esp32.preview.wokwi.com/arduino/projects/322322941068968530):

Reproduces, seems like some of the I2C writes are not going to the MPU-6050. Needs further investigation.

**Comment by urish** [comment]
After several hours of tedious debugging, I finally found the culprit: the acks for I2C read operations were inversed.

The datasheet says:

![image](https://user-images.githubusercontent.com/892318/152005645-53f97147-5652-4ec2-b18a-f11a41bfe579.png)

Which I interpreted: send ACK when ack_value is high, and NACK when ack_value is low. It turns out it works the opposite way. What they probably wanted to say is that the ack_value should be copied to the SDA line (I2C pulls it low when it wants to send an ACK, and leaves it high when it wants to send a NACK).

The MPU6050 library read from the register before updating it. As the read failed, it silently skipped the write.

Fix should be up on wokwi.com in a few minutes. 

Note: you can stop using the esp32.preview branch, as it has been merged and now available on wokwi.com. This branch is no longer receiving updates or bug fixes.

**Comment by kartben** [comment]
Super cool - thank you so much! It now works fine for me, and I've learnt a lot about the logic analyzer in the meanwhile. REALLY cool stuff :)

Thanks for the note/update regarding the now dead esp32.preview branch, too!

**Comment by urish** [comment]
Thank you for finding all those hidden bugs :)
