### ISSUE TITLE
"Save" button should become available after deleting a file tab 

### ISSUE THREAD

**Issue by jflamy** [wokwi/wokwi-features#297]
**Describe the bug**
In the code editor, deleting a tab does not remove it.

**To Reproduce**
Open a project, delete a tab.
Go away.
Reopen wokwi, go back to the project, the tab is back.
could be related to #293 

**Expected behavior**
Tabs should go away.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser Latest Chrome

**Additional context**
It would be nice to be able to mark tabs as "private". Things like keys and certificates could be hidden when sharing the project to ask for help.

**Comment by sutaburosu** [comment]
I can't reproduce this. Well, I can reproduce it by not saving the project after deleting a tab. But I wouldn't expect any changes to be permanent without clicking save. To my mind, this is working as intended. You may have to make some other change (add a blank line) to trigger the ability to save.

**Comment by jflamy** [comment]
Given that there is an explicit feedback ("This will remove tab xyx do you agree") which is normally used when an action takes place immediately and cannot be undone, and that the tab actually disappears AND that the save button does not get highlighted, this is not intuitive.
If removing a Tab requires a Save, then the Save button should become available.

**Comment by urish** [comment]
> If removing a Tab requires a Save, then the Save button should become available.

Agreed

**Comment by jflamy** [comment]
Also, renaming a Tab does cause "save" to become active.

**Comment by urish** [comment]
Fixed!
