### ISSUE TITLE
Default memory limits on build server seem too big

### ISSUE THREAD

**Issue by sutaburosu** [wokwi/wokwi-features#298]
Starting from a fresh project on Uno or Nano, I can use more RAM than the real-world boards actually have.

e.g. [This project](https://wokwi.com/arduino/projects/322331674560954962) uses over 16KiB of RAM, and builds fine. It doesn't run too well; a lot of the array seems to hold different values than I would expect.
```
Sketch uses 1802 bytes (5%) of program storage space. Maximum is 32256 bytes
Global variables use 16572 bytes of dynamic memory.
```

After adding `"attrs": {"__fakeRamSize": "2048"}` to the Uno, I get the expected build error:
```
Sketch uses 1802 bytes (5%) of program storage space. Maximum is 32256 bytes.
Global variables use 16572 bytes (809%) of dynamic memory, leaving -14524 bytes for local variables. Maximum is 2048 bytes.
Not enough memory
```

 - OS: Linux
 - Browser: Chromium v97

**Comment by urish** [comment]
Good spot! Can you give it another shot now?

**Comment by sutaburosu** [comment]
Perfect. Thank you. :+1:
