### ISSUE TITLE
Save as a copy - Option

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#3]
When I want to create two or three versions of the project, 
(example: a code that blinks LED at 100ms, second project at 200 ms and third at 500 ms). I cannot reuse the code.

I would like to tell the tool to create a link for me. I do not want to lose the contents of the first project. Neither I want to go to another browser or incognito mode so that the original file will not be overwritten

**Comment by urish** [comment]
Done, now we have a drop-down menu with "Save a copy" option:

![image](https://user-images.githubusercontent.com/892318/97172773-3107e180-1798-11eb-8f56-ed10c410c186.png)
