### ISSUE TITLE
naming a file as diagram.json locks out possibility to rename it again

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#30]
step 1:  Open https://wokwi.com/share
step 2: try to rename the sketch.ino to diagram.json (let us say accidentally)

![image](https://user-images.githubusercontent.com/68117142/102024717-b03d8d00-3db9-11eb-818b-bc54b7a9b8c9.png)

**Comment by urish** [comment]
Thanks for reporting, fixed!
