### ISSUE TITLE
Buzzer sound doesn't pause (keeps buzzing) when switched to other tab

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#307]
**Reference link:** 

https://wokwi.com/arduino/projects/310901229191430720?dark=0

Steps to recreate

Play the simulation and switch to another tab. If you switch to another tab while the buzzer was making sound, it will keep buzzing though we are in another tab. 

This will give the wrong impression of simulation running + also sound may annoy the user.

**Comment by urish** [comment]
Thanks for reporting, fixed!
