### ISSUE TITLE
feature request - how to make a project Readonly

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#31]
is there a possibility to make the project read only?

can we make it as an option or a feature?

background: 

I had created a project and had used it in some of the articles already online.

When I had to create a new project, I used the same project and updated the contents of the editor and hit SAVE button.

I was anticipating a new number (new link) for the new project, but (maybe due to the same PC, browser)

**Comment by urish** [comment]
Great suggestion! This is now available under the Save menu:

![image](https://user-images.githubusercontent.com/892318/102026745-508ab600-3da8-11eb-9cc9-1ea902b9181e.png)

When "Lock project" is enabled, the "Save" option is automatically disabled, and it's only possible to "Save a copy" until you disable "Lock project".

**Comment by Puneethkumarsn** [comment]
wow that was fast
