### ISSUE TITLE
INPUT_PULLUP  issues on ESP32-S2

### ISSUE THREAD

**Issue by jflamy** [wokwi/wokwi-features#310]
**Describe the bug**
INPUT_PULLUP not reliably working on a pin where it should

**To Reproduce**
Run project https://wokwi.com/arduino/projects/323311063005135444 and 
- click 4 times on the white button at the top, (wait 1sec between presses).
- click 4 times on the red button at the top (wait 1sec between presses).
- Download the logic analyzer trace.
- Pressing red first instead of white does not change the outcome (white events missed)

Logic Analyzer trace shows that the white button is not being pulled up reliably.
- D1 is the working red button
- D2 is the non-working white button
- D0 is the loop() timing (toggling HIGH-LOW on every iteration to create a square wave pattern)  - the loop is tight enough and the missed events are not caused by excessive delay() - the 5ms delay is fine)

![pk8TS3kQvv](https://user-images.githubusercontent.com/678663/153635483-a893b7bb-543c-4148-b4db-21d34ddcb361.png)

**Expected behavior**
According to this pinout for the Franzininho board, the pins used should behave the same
https://www.embarcados.com.br/franzininho-wifi-entrada-analogica-esp-idf/

I also observe the same kind of missing transitions on other pins (initial connections were to pins 2 and 3)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version  98.0.4758.82 (Official Build) (64-bit)

**Additional context**
The traces when running the application show the pins on which INPUT_PULLUP is applied, and which events are processed
The actual MQTT processing is turned off.

**Comment by jflamy** [comment]
Moving all the inputs to pins 3..8 shows that only one pin seems to be working correctly.
Pin order on the logic analyzer is 4, 3, 6, 5, 8, 7

![gFp3laP66f](https://user-images.githubusercontent.com/678663/153650986-20ec66bd-e07f-41fe-ac95-db7c6f7a461f.png)

**Comment by urish** [comment]
Thanks for the super-detailed bug report, it's really helpful!

I uploaded a fix, can you please try again and report back?

**Comment by jflamy** [comment]
Not quite.  Still erratic.
![image](https://user-images.githubusercontent.com/678663/153690449-380e395a-4aae-4c6a-8256-24a239f8135e.png)

And when using all the 6 input buttons, it's even more random.  You can see the sequence in which I pushed the buttons by spotting the small transitions to high at the beginning and end of the presses.  The project with the 6 buttons is https://wokwi.com/arduino/projects/323248259320513108 
![image](https://user-images.githubusercontent.com/678663/153690646-24e24aff-e7da-405a-a96d-b2be699fe642.png)

Also, regarding a comment on another issue - there is no TLS active (there is no #define TLS)

**Comment by urish** [comment]
Oopsie... Can you please give it another go now?

**Comment by jflamy** [comment]
Looks good now.
![image](https://user-images.githubusercontent.com/678663/153715204-9a63727b-d593-4e14-a109-564741ca74f8.png)

**Comment by urish** [comment]
Thanks again for the super-detailed bug report, it was really helpful!
