### ISSUE TITLE
Make a non-Arduino simulator for the RPi Pico 

### ISSUE THREAD

**Issue by eleciawhite** [wokwi/wokwi-features#311]
I want to use Wokwi for a remote-classroom. However, the Arduino IDE is one I'm trying to get the students away from.

Can you make an RPi Pico Project that is C/C++ based? It would still hook to the [Pico SDK](https://raspberrypi.github.io/pico-sdk-doxygen/modules.html) as it does now. Instead of setup() and loop(), the new Project type would show a main function like:

```
#include "pico/stdlib.h"

const uint LED_PIN = 2;

int main() {
  gpio_init(LED_PIN);
  gpio_set_dir(LED_PIN, GPIO_OUT);
  while (true) {
    gpio_put(LED_PIN, 1);
    sleep_ms(250);
    gpio_put(LED_PIN, 0);
    sleep_ms(250);
  }
}
```
I want to be able to give students PWM code for an LED and have them modify it to hear a buzzer in driven by PWM. I also want them to be able to construct final projects (your peripheral list is great!).

**Comment by urish** [comment]
Thanks Elecia! I just opened this request for [voting](https://wokwi.com/features?sort=newest#feature-1137946529)

**Comment by arcostasi** [comment]
It is possible to use many features of the Pico SDK with the [Arduino core (Pico SDK)](https://arduino-pico.readthedocs.io/en/latest/sdk.html). Here are some examples that may be useful until the oficial [Pico SDK](https://raspberrypi.github.io/pico-sdk-doxygen/modules.html) is available in Wokwi.

- [Blink](https://wokwi.com/arduino/projects/324525619626902098)
- [LCD i2c](https://wokwi.com/arduino/projects/324606785723826771)
- [UART](https://wokwi.com/arduino/projects/324606129408574036)

**Comment by urish** [comment]
First working prototype: https://wokwi.com/projects/new/pi-pico-sdk

It compiles against Pi Pico SDK 1.3.0. Only "main.c" is currently supported - you can add additional .h files and it'll probably work, but additional ".c" files won't get compiled.

@arcostasi Thanks for the comment! I did some testing and figured out that the Arduino core is missing some of the basic functionality (e.g. `stdio_init_all()` is missing), so now we're going to have native Pi Pico SDK builds.

**Comment by arcostasi** [comment]
Hooray, thanks @urish 
an alternative I found to add a file in c is instead of the ".h" was to include the ".c" as in the [vector example](https://wokwi.com/arduino/projects/324685778461393491)

**Comment by urish** [comment]
Cool workaround :) Thanks for sharing!

**Comment by urish** [comment]
Good news - multiple .c/.cpp source file are now supported!

Here's @arcostasi's example without the "include" workaround: https://wokwi.com/projects/325323976447361620

And our beloved blink: https://wokwi.com/projects/325324198971966034
