### ISSUE TITLE
I have an issue with Neopixel... 

### ISSUE THREAD

**Issue by ntmario** [wokwi/wokwi-features#316]
...when I insert more as 622 NeoPixel (Line 14) , the program not running anymore. Can you help me?

and  delay(wait); (line 50) not halt for the selected time...

https://wokwi.com/arduino/projects/324831261050798674

**Comment by urish** [comment]
Closing as this has already been addressed on discord. 

The Uno board does not have enough SRAM to handle so many NeoPixels. The solution was to switch to a more capable board: Arduino Mega, ESP32, etc.

Here's a working example with the ESP32: https://wokwi.com/arduino/projects/324886600507982420
