### ISSUE TITLE
Rust as C/C++ alternative

### ISSUE THREAD

**Issue by Chris2011** [wokwi/wokwi-features#318]
As I wanted to try rust on an arduino/esp32 afaik that is working, I thought how cool would it be to have support for rust in your wokwi online editor + simulator :). What do you think about that?

I didn't know whether this is the right repo for this issue, but I couldn't find another one. So I think it is, because you need to handover the written code into the your cloud build.

**Comment by urish** [comment]
Hi Chris!

There's an initial prototype for Rust + ESP32 on Wokwi:

* [Hello World](https://wokwi.com/arduino/projects/323155109094621778)
* [Blinky](https://wokwi.com/arduino/projects/323845300685898322)
* [LED PWM](https://wokwi.com/arduino/projects/323765044769718868)

These are still early days, and I'm working together with the team at Espressif to improve the experience.

Rust + Arduino is not on the roadmap for now.

I'm curious, how did you find out about the simulator?

**Comment by Chris2011** [comment]
Hey Urish,

thx for the fast reply. I'm sry I must have overseen it. Looks great. :).

I just googled for arduino simulator and I opened a lot of links and I think you have a direct organic search result at google and I think I found a website with some links and you were linked there.

I would like to say a big thank you for your great work and I'm looking forward what comes next :)

**Comment by Chris2011** [comment]
And just now I found an article at heise: https://www.heise.de/news/Online-Simulator-fuer-Arduino-Raspi-Pico-und-ESP32-6324290.html unfortunately it is in german. It is just a little review about your nice tool :)
