### ISSUE TITLE
Graphical way to select Arduino elements and connect them with the Arduino 

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#32]
We presently have 

https://wokwi.com/arduino/alpha-editor

New feature request is to make it 
1. graphical and easier in terms of drawing wires between the pins.
2. select Arduino UNO, Arduino Mega, Arduino Nano, ATtiny85 (and more when the new items are added)
3. select all the Wokwi elements (peripherals)
4. draw by connecting wires to choose the colours

**Comment by stevesigma** [comment]
I don't think so many requests in one is good to read what is done and what is unfinished.
1. and 4. are close and should be done in one shot.

**Comment by urish** [comment]
We now have the ability to drag components.

So I guess adding elements by selecting them from a list / drawing wires with the mouse will come next :)

**Comment by urish** [comment]
Mostly done! 

https://docs.wokwi.com/guides/diagram-editor
