### ISSUE TITLE
How does Wokwi allocate memory size for dynamic allocation?

### ISSUE THREAD

**Issue by techstudio-design** [wokwi/wokwi-features#323]
When I run an ESP32 simulation, I noticed that the free heap memory (calling `ESP.getFreeHeap()`) is around 360KB. 

The size of RAM on ESP32 is fixed at 512KB, roughly 200KB of which is used by IRAM cache/code sections, leaving around 320KB for program memory, half of which is available for dynamic allocation.

In another word, Wokwi does not match what's available in an actual device.

From ESP documentation [Heap Memory - Available Heap](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/mem_alloc.html#available-heap):

>Note
>
>Due to a technical limitation, the maximum statically allocated DRAM usage is 160KB. The remaining 160KB (for a total of 320KB of DRAM) can only be allocated at runtime as heap.

**Comment by urish** [comment]
Wokwi does not manage the dynamic allocation - it simulates the chip at a lower level, running the code instruction by instruction as it would run on the physical chip. So it's the runtime (ESP-IDF) which manages the memory allocation.

I tried running [this project](https://wokwi.com/projects/326364399101018706) on a physical ESP32 device, and got the following output:

```
Free heap:
347576
```

As far as I understand, what the docs state is that the full 320KB are available for dynamic allocation (but up to 160KB could be statically allocated). The actual amount available for dynamic allocation would then be (320KB - size of statically allocated memory).

I hope that this helps!
