### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by simonecable** [wokwi/wokwi-features#327]
[ita.zip](https://github.com/wokwi/wokwi-features/files/8308939/ita.zip)

**Comment by urish** [comment]
Thank you! I uploaded the translations, and you can see them live here: https://wokwi.com/projects/new?lang=it

Mind taking a look and reporting if you can spot any errors?

**Comment by urish** [comment]
Closing, feel free to open a new issue for any fixes / updates to the Italian translations
