### ISSUE TITLE
Add ability to add notes/annotations to a diagram

### ISSUE THREAD

**Issue by kartben** [wokwi/wokwi-features#328]
It'd be great to be able to include notes/annotations to a diagram. Having annotations can be really useful to help a user understand how a particular project is meant to work, what's the role of such or such part, ... and they can generally act as some kind of "README"... but for diagrams :)

![wokwi-annotation-example](https://user-images.githubusercontent.com/128251/159524535-52e101d9-0277-470b-9917-7eb7a5ce3224.png)

**Comment by kartben** [comment]
Could this one be opened for voting? 
FWIW I *think* it might make sense to allow connection between annotations and regular parts, but I am not sure how I'd feel about the `connections` section of `diagram.json` being "polluted" by things that are not corresponding to actual wire connections. 
Also, if we allow connections on annotations, it'd be great to support dotted lines (happy to open another issue :))

**Comment by urish** [comment]
Thanks @kartben! We have #43, which is similar - also discussing whether the text elements should be standalone or attached to diagram elements.
