### ISSUE TITLE
Arduino app for Android and iOS

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#33]
App which is nothing but a replacement for the browser. To reach more users.

**Comment by urish** [comment]
Good idea for the future. Android's play store has some nice feature called [TWA](https://css-tricks.com/how-to-get-a-progressive-web-app-into-the-google-play-store/) which may be useful here.

**Comment by Puneethkumarsn** [comment]
I wan to close this for now. browsers are okay and it is much easier
