### ISSUE TITLE
Change the README.md/Description tab colors

### ISSUE THREAD

**Issue by drf5n** [wokwi/wokwi-features#331]
The default colors on the Description tab / README.md file rendering are difficult to read:

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/2236516/160954622-73f8db91-a331-4081-96a5-2908c0172b44.png">

It would be nice to render the README.md file in a more readable color scheme.  For instance, like the left-hand code panel, with  the light background and differetn contrasting colors for the different sorts of text.  Maybe a slightly darker color background color for the code block.

(See https://github.com/wokwi/wokwi-features/issues/191 for the related wokwi-stepper-motor issue)

**Comment by urish** [comment]
How about now?

**Comment by drf5n** [comment]
<img width="1167" alt="image" src="https://user-images.githubusercontent.com/2236516/161287132-50614330-2d53-4433-9e3d-9aaddff905b4.png">


That is so much better! Thanks.
