### ISSUE TITLE
Delete File option is missing on some files in editor

### ISSUE THREAD

**Issue by drf5n** [wokwi/wokwi-features#332]
One should be able to delete mistaken uploads.

I uploaded a file to https://wokwi.com/projects/327748577668366932 and then tried to delete it.  The option was not present on the drop-down menu:

<img width="991" alt="image" src="https://user-images.githubusercontent.com/2236516/161287690-75368929-2771-4abe-aab5-1a196ac1f2fb.png">

I expected the delete file command that is present for other tabs to be present on the uploaded file. For instance, here's one on diagram.json:

<img width="590" alt="image" src="https://user-images.githubusercontent.com/2236516/161288196-ab3023c4-a118-47d3-b899-1e7b1762fffb.png">
 
**Environment (please complete the following information):**
 - OS: Mac OSX
 - Browser: Chrome
 - Version 99.0.4844.83 (Official Build) (x86_64)

**Comment by urish** [comment]
Thanks for reporting! Can you please check again?

**Comment by drf5n** [comment]
I cannot replicate.  It seems to be OK now.  

I uploaded an additional file to that project, and was able to delete it both before saving the project, after saving the project, and after reloading the project with the saved file.

**Comment by urish** [comment]
Thanks!
