### ISSUE TITLE
Add GLCD (KS0108) support 

### ISSUE THREAD

**Issue by minolmal** [wokwi/wokwi-features#333]
I really loved the ability to simulate SSD1306 OLED displays before I upload to MCU. Prevents a lot of unnecessary write to MCU due to trial and error procedures. 
I would like to see the same approach used with KS0108 based mono colored GLCDs. 

![Basic Structure of GLCD 128x64 Displays](https://user-images.githubusercontent.com/37414328/161936918-bb330d2b-8d51-4333-b341-4d8e2af099f5.PNG)
![1_GLCD_Block_Diagram](https://user-images.githubusercontent.com/37414328/161936965-63bba008-2502-4cd5-bbbe-7794eedb8427.PNG)

the very basic functionality should be described in here.
https://www.electronicwings.com/sensors-modules/glcd-128x64

**Comment by urish** [comment]
Thanks for the suggestion! I opened this request [for voting](https://wokwi.com/features?sort=newest#feature-1194296434)

**Comment by urish** [comment]
Closing as this didn't get any votes in the past 6 months. 

Note that you could still try to create this part yourself using the new custom chip API prototype - see #301 for details.
