### ISSUE TITLE
Potentiometer slider doesn;t appear until Simualtion is started

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#336]
To slider, won't appear in the potentiometer until I run the simulation

Link to the project here to reproduce: 
https://wokwi.com/projects/327381547863769683
![Stepper motor - won't load completely](https://user-images.githubusercontent.com/68117142/162631451-0ced5530-bc2a-46b1-a826-1aa8352c7fb5.gif)

Tio: seems to be that the attribute value should not be more than 1000. When a value less than 1000 is entered, the simulation reappears.

**Comment by urish** [comment]
Thanks for reporting! Can you please check now?

**Comment by eternaleclipse** [comment]
Works for me now in Firefox / Chrome (Firefox still has the slider moving bug (https://github.com/wokwi/wokwi-elements/issues/87) during simulation but it's not related).
