### ISSUE TITLE
Camera Module with webcam input

### ISSUE THREAD

**Issue by alislaboratory** [wokwi/wokwi-features#337]
I think it would be nice to have a webcam input from the computer that acts as an OV7670 in the simulator. Would love to see this for some projects that make it hard to implement it, so it can be tested especially with a convenient webcam input in the Wokwi sim.

Thanks

**Comment by urish** [comment]
Thanks for the request! I opened it for [voting](https://wokwi.com/features?sort=newest#feature-1200734547)

**Comment by urish** [comment]
Closing, as this hasn't received any votes in the last 6 months.
