### ISSUE TITLE
Simple relay module with indicator LEDs

### ISSUE THREAD

**Issue by eternaleclipse** [wokwi/wokwi-features#339]
It would be nice to have a simple relay module with indicator LEDs:
https://arduinogetstarted.com/tutorials/arduino-relay

There is currently an 8-pin [DPDT switch](https://docs.wokwi.com/parts/wokwi-ks2e-m-dc5), but for most circuits it's unintuitive / overkill, and doesn't provide visual indication of when it's on / off.

**Comment by urish** [comment]
Thanks! Opened for [voting](https://wokwi.com/features?sort=newest#feature-1203598486)

**Comment by arduino12** [comment]
Just voted for this!
1. Will be great to add ```channel_count``` attribute that will accept 1, 2, 4, 8, 16 like the **[common relay modules](https://www.aliexpress.com/item/1005001700441473.html)**.
2. Will be great to add ```active_polarity``` attribute that will accept a bool like set in those **[relay modules](https://www.aliexpress.com/item/1005002617199944.html)** jumpers.

Thanks @urish !

**Comment by scorninpc** [comment]
I've been used this as a simple led. Just change the layout to a relay will be nice! 

+1

**Comment by yanickrochon** [comment]
I have a project with relays, and having this component would greatly help!

**Comment by urish** [comment]
This is getting up the vote list, so we may start to work on it soon

**Comment by AriellaE** [comment]
Thanks to everyone who voted for this feature!

Here you go:
- [Sample project](https://wokwi.com/projects/347309345158988371)
- [Docs](https://docs.wokwi.com/parts/wokwi-relay-module)

Enjoy!
