### ISSUE TITLE
Serial plotter

### ISSUE THREAD

**Issue by urish** [wokwi/wokwi-features#34]
Similar to what Arduino IDE has - take values from the Serial console and plot them onto a graph

**Comment by sutaburosu** [comment]
After a sketch edit + restart, it would be great to keep all the history since the tab opened,  ideally with an indicator of when the restarts happened.

**Comment by urish** [comment]
Reference implementation: [Arduino IDE](https://github.com/arduino/Arduino/blob/master/app/src/processing/app/SerialPlotter.java#L408)

**Comment by urish** [comment]
Work-in-progress video: https://twitter.com/WokwiMakes/status/1345510126321610752

**Comment by urish** [comment]
We now have a working Serial Plotter!

Example: https://wokwi.com/arduino/projects/286653669554782732
