### ISSUE TITLE
arduino uno simulation doesent run as expected

### ISSUE THREAD

**Issue by AHCbc** [wokwi/wokwi-features#348]
**Describe the bug**
i have created code and simulated circuit to verify relay contacts closing. I am new to coding but could not see what was causing the behavior i was seeing. The relays to test are 24v coil, so i have set up a 5v coil relay (K3 in the sim) to be directly controlled by the UNO which then switches the 24v coil relays (K1 and K2 5v in the sim) K1 channel 2 common is fed from the 24v on the board, so a 24v coil relay  is used (K4) to switch the UNO input low, sim green led 2 and 3 show relay state for debugging.  While the relays are on i read the relative inputs D2 D3 D4 D6 outputting a result to the serial print :- SR_A good, SR_B good, SR_C good, SR_D good, and turning on the green led (1) if inputs are low. or 
SR_A bad
SR_B bad
SR_C bad
SR_D bad 
and turning on the red led on pin 12 if any of the inputs are high. The switches shown in the sim give me the ability to represent a failed relay contact.
The print of the "previousRelay_Millis" was for debugging this fault, if i didnt reset previousRelay_Millis i would get the effect at previousRelay_Millis value of  63000.
 all this works as expected except that when i run in the wokwi sim after 19 cycles i get a cycle of relay bad contact inputs and it repeats in a 19 pattern, i will hold my hand up and say it could be my code, but it the exact same code works as expected on tinkercad (sorry to be a traitor :-) )

**To Reproduce**
Load and start the sim 
[Test Rig For ESMC and SMC card safety relays.zip](https://github.com/wokwi/wokwi-features/files/8564106/Test.Rig.For.ESMC.and.SMC.card.safety.relays.zip)

https://wokwi.com/projects/330003708669592146

**Expected behavior**
If all the relay contacts stay closed  "SR_A good SR_B good SR_C good SR_D good" should be displayed if a switch is opened the relative input would be reported bad and the red led should stay lit to show fault condition.

**Environment (please complete the following information):**
wokwi arduino simulator

win 10

 chrome browser

**Additional context**

**Comment by urish** [comment]
Thanks for the detailed report! Looking into this.

**Comment by urish** [comment]
Fixed a bug with the relay, and it seems to work well now. 

Can you please test again and report?

**Comment by AHCbc** [comment]
Hi Uri sorry for the late reply. yes that works now thank you for your
quick response

**Comment by urish** [comment]
Thanks!
