### ISSUE TITLE
CAN NOT COPY + PASTE MULTIPLE COMPONENTS AT ONCE? HOW IS IT POSSIBLE??

### ISSUE THREAD

**Issue by boga94** [wokwi/wokwi-features#364]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by urish** [comment]
Currently, there are two ways to duplicate existing parts:

1. Selecting a single part and pressing D on the keyboard will create a copy of that part. It's possible to create multiple copies by repeatedly pressing D
2. Editing diagram.json directly, and copying several parts at once. Note that you'll have to change the "id" of the new parts, as each part needs to have a unique id for the simulator to work correctly.
