### ISSUE TITLE
LED Matrix component is missing

### ISSUE THREAD

**Issue by boga94** [wokwi/wokwi-features#365]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by urish** [comment]
Thanks for reporting. It is not yet available - we're tracking it on issue #240. I hope we'll be able to add it to the menu soon.

Meanwhile, it can be added by copying it from the [diagram.json file](https://docs.wokwi.com/diagram-format) of an existing project to your own diagram.json file.
