### ISSUE TITLE
Impossible to switch from Arduino to ESP32 mid project? Why?

### ISSUE THREAD

**Issue by boga94** [wokwi/wokwi-features#366]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by boga94** [comment]
I have a phisical project running on ESP32 + LED Matrix, which i was trying to recreate.
I found the led matrix component is missing.
I found a project with the led matrix in it, connected to arduino.
Cannot swap the arduino for ESP32.... BUMMER...
Cannot copy the matrix from one project to the other....     OK.
Cannot create a neopixel strip and copy/paste the whole strip to make a matrix.................
I want a refund.

**Comment by urish** [comment]
Thanks for the feedback!

The current way to swap microcontrollers in an existing project is by editing the [diagram.json file](https://docs.wokwi.com/diagram-format). Search for "wokwi-arduino-uno" and replace with "wokwi-esp32-devkit-v1" (you can find the full list of supported boards in the [documentation](https://docs.wokwi.com/diagram-format#parts)).
