### ISSUE TITLE
Take me to the error!

### ISSUE THREAD

**Issue by leftCoast** [wokwi/wokwi-features#369]
When discovering an error (Gasp!) in your code. The error window blocks your view, you can't scroll the code and you are left to your own devices to locate said error. 

There is the option of clicking F8 to take you to the first error.. But who would think of trying that if not told? How about when we click the close button in the error window it just automatically takes us to our first error?

**Comment by urish** [comment]
Thanks for the suggestion!

How about now?

**Comment by leftCoast** [comment]
Umm.. I can add LEDs and change their color. Can't edit any text.

**Comment by urish** [comment]
Can you post a screen shot?

**Comment by leftCoast** [comment]
Of not being able to type?  ok..
/Users/owner/Desktop/cantType.jpg

**Comment by leftCoast** [comment]
Hmm.. I suspect this is another one of those old Safari version things. Its not my usual computer I'm on here.
![cantType](https://user-images.githubusercontent.com/3913684/177818062-f9cdb9c8-84f9-4d5a-9f3b-5dc626f4b269.jpg)

**Comment by leftCoast** [comment]
OK, using Chrome. I put error in code. Try to run. Popup shows the error. I click close, and it doesn't take me anywhere.

**Comment by urish** [comment]
It should actually take you there before you click close (as soon as the error pops up):


https://user-images.githubusercontent.com/892318/177871402-09a31806-c474-453a-8cf0-a7a251757226.mp4


Do you get a different experience? Or does it work for you the same way, but it is not what you wanted?

**Comment by leftCoast** [comment]
Yes because I often use multiple files. It wont switch the file to locate the error. It does darken **_some_** of the tabs that have errors in them.

And the underlining is a bit.. Unreliable?
<img width="497" alt="Screen Shot 2022-07-07 at 3 42 58 PM" src="https://user-images.githubusercontent.com/3913684/177876437-82f72dc2-aaeb-4e18-aacf-51f61cc3a080.png">

**Comment by urish** [comment]
>  It does darken **some** of the tabs that have errors in them.

Can you share a link to a project where there some tabs with errors that are not marked?

> And the underlining is a bit.. Unreliable?

How can I reproduce this?

**Comment by leftCoast** [comment]
**Can you share a link to a project where there some tabs with errors that are not marked?** I don't think I can. All the tests I did tonight worked fine.

**And the underlining is a bit.. Unreliable?** Doesn't seem to do this anymore. Maybe what I saw was a fluke?

**Wait no! Typing it in exactly like I had it. It has the odd underlining** : https://wokwi.com/projects/337690058595238483

What I'm looking for is for it to, on close, take me to the tab that has the error then to the error itself.

**Comment by urish** [comment]
> Wait no! Typing it in exactly like I had it. It has the odd underlining : https://wokwi.com/projects/337690058595238483

Thanks for sharing the link!

Looking at the error message, it looks like the compiler says there's an error there, so Wokwi underlines it:

![image](https://user-images.githubusercontent.com/892318/179935979-02f30ecd-964b-4a06-85d9-617938ce8914.png)

**Comment by leftCoast** [comment]
OMG! You are 100% correct! Even the IDE fails on this one!

<img width="358" alt="error" src="https://user-images.githubusercontent.com/3913684/180063693-de38b1fb-e2eb-4bd0-9b82-b70116bdf148.png">

**Comment by urish** [comment]
Update: if the error is in a different file, the editor now automatically jumps to that tab.
