### ISSUE TITLE
serial plotter window - bigger screen if possible

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#37]
This is not important but an enhancement.

A bigger serial monitor will help to visualise the variables or the input signals at the analog inputs.

Thanks

![image](https://user-images.githubusercontent.com/68117142/103490219-51ab8200-4e40-11eb-993d-32c29bec4b86.png)

**Comment by atuline** [comment]
+1 for this request. A resizeable console window would do the trick.

**Comment by urish** [comment]
Done!
