### ISSUE TITLE
how to add EDA/GSR sensor and PPG sensor library, LoRa sx1276 to Wokwi on line simulator

### ISSUE THREAD

**Issue by 0921341259** [wokwi/wokwi-features#371]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by urish** [comment]
Hello, I'm not familiar with the EDR/GSR sensor, but you can try implementing them yourself using the custom chip API (see #301 for details - it's still in alpha stage).

As for the LoRa radio, there's already an [open feature request](https://wokwi.com/features#feature-1203975965) in #344, but it hasn't received any many votes yet.
