### ISSUE TITLE
No 'paste' in context menu.

### ISSUE THREAD

**Issue by MrToM528** [wokwi/wokwi-features#373]
I guess there is a good reason why it's missing but it's a right pain! 

CTRL+V works fine but it doesn't make sense to isolate just the one option.
Could it be added to the context menu so as to complete the standard cut/copy/paste trio of options?
Thanks.

**Comment by urish** [comment]
Thanks for the feedback, unfortunately, this is not something that is easy to fix. Browsers do not allow easy way to read the clipboard contents for security reasons: imagine you press on some link in a website, and the code then reads some secret information you have in your clipboard - credit card number, password, some text from a personal conversion, or a private image - and sends it to a server. 

Sorry for not being able to help with this!
