### ISSUE TITLE
Add different sizes of the breadboard element (for example half size, mini) and make the + and - rows on the top and bottom usable

### ISSUE THREAD

**Issue by MarcelDev** [wokwi/wokwi-features#375]
**Is your feature request related to a problem? Please describe.**
Yes, + and - rows dont do anything, infact they dont even have pins on them, also different breadboard sizes would be good.

**Describe the solution you'd like**
Make the + and - rows work on breadboards and also add different sizes.

**Comment by urish** [comment]
Thanks for the suggestion! We first need to complete wokwi/wokwi-features#434, so I added a comment there with reference to this.

In general, the [breadboard feature](https://wokwi.com/features#feature-650859885) got some votes already. If it keeps getting votes and climbing up the list, this will happen sooner.

**Comment by urish** [comment]
Half breadboard: https://wokwi.com/projects/349109488710582866
