### ISSUE TITLE
Allow zero-length Power Connections

### ISSUE THREAD

**Issue by Dlloydev** [wokwi/wokwi-features#376]
For example, here's a diagram with power connections:

![image](https://user-images.githubusercontent.com/63488701/177048759-bfff349e-845b-4262-a832-e3558e625b39.png)

If adding zero-length connections to VCC or GND could leave colored squares or circles on the pins, the diagram would look like this:

![image](https://user-images.githubusercontent.com/63488701/177048903-aa5485d9-1ca0-45cb-832e-3ee94d6f0951.png)

The effect would be similar to adding net names to reduce wiring in a schematic application.

**Comment by urish** [comment]
Thanks for the suggestion! 

There's (yet undocumented) `wokwi-gnd` and `wokwi-vcc`. Here's a quick example:

https://wokwi.com/projects/336518688534430290

![image](https://user-images.githubusercontent.com/892318/177748052-63cadf67-14fe-41ca-82d0-80ba6f7db802.png)

How about that?
