### ISSUE TITLE
il9163 program fails to compile

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#38]
Project:
https://wokwi.com/arduino/libraries/lcdgfx/il9163_demo

Error:
![image](https://user-images.githubusercontent.com/68117142/103490679-810fbe00-4e43-11eb-9002-c6a3d124f890.png)

Error text:
'class DisplayIL9163_128x128x16_SPI' has no member named 'negativeMode'

/home/hexi/Arduino/libraries/lcdgfx/src/v2/lcd/base/ssd1306_common.inl:702: 'class NanoDisplayOps<NanoDisplayOps16<InterfaceIL9163<PlatformSpi> >, InterfaceIL9163<PlatformSpi> >' has no member named 'positiveMode'

**Comment by urish** [comment]
Seems like the library code has recently changed:

https://github.com/lexus2k/lcdgfx/blob/master/examples/demos/il9163_demo/il9163_demo.ino

**Comment by urish** [comment]
Thanks for reporting, fixed!
