### ISSUE TITLE
Custom partitions for ESP32 project

### ISSUE THREAD

**Issue by Tech500** [wokwi/wokwi-features#380]
Sketch producing this error:  [Sketch Code](https://gist.github.com/Tech500/47a0383795b57a1642a3d8d9c40b0fc8)

E (6108) esp_littlefs: partition "spiffs" could not be found
E (6109) esp_littlefs: Failed to initialize LittleFS

Could WokWi create a "SPIFFS" partition to be able to use LittleFS or SPIFFS?

**Comment by urish** [comment]
You can now create custom ESP32 partitions by adding a partitions.csv file to your project. 

* Documentation: https://docs.wokwi.com/guides/esp32#custom-partition-table
* Quick example: https://wokwi.com/projects/337425600260080210
