### ISSUE TITLE
Missing pins on wokwi-7segment part with custom digits attribute

### ISSUE THREAD

**Issue by DurandA** [wokwi/wokwi-features#383]
**Describe the bug**
Creating a `wokwi-7segment` and setting its `digits` attribute to something else than 2 or 4 misses the DIG# pins.

**To Reproduce**
Add the following to `parts` in _diagram.json_:
```json
{
  "type": "wokwi-7segment",
  "id": "sevseg1",
  "attrs": { "digits": "3" }
}
```

**Expected behavior**
The 7 segments display should have some `DIG1`, `DIG2` and `DIG3` pins.

**Comment by urish** [comment]
Thanks for reporting! 

The pinout is defined here:

https://github.com/wokwi/wokwi-elements/blob/67c169dda3193d0f7baef5a6d60da6194268b98c/src/7segment-element.ts#L52-L103

Would you be interested in creating a pull-request to add the pin out for the 3-digit version (based on the pin out of the actual physical part)?

**Comment by DurandA** [comment]
> Would you be interested in creating a pull-request to add the pin out for the 3-digit version (based on the pin out of the actual physical part)?

Sure! I am however not sure how "standard" are 3-digits pinouts. Feel free to give me a reference if you want me to map it to a particular part.

Also, would it make sense to generate pins dynamically rather than relying on hard-coded pinouts for arbitrary digits?

**Comment by urish** [comment]
I don't think there's a standard - I'd just look for one popular option and go with it.

Perhaps down the road we'll have more pin out options, based on user-given part number. After all, what's the use case for simulating a pinout which does not correspond to a part you can actually buy?
