### ISSUE TITLE
Clear Display when recompling code

### ISSUE THREAD

**Issue by ithinkido** [wokwi/wokwi-features#384]
when using the SSD1306 display, if you make changes to your code and recompile, then the display shows the last displayed image. This can cause you to make changes that break the display code, but on recompiling , you will not see the change and you continue to think that the code may be working. 
Would it be possible to automatically clear the display when recompiling code ?

**Comment by urish** [comment]
Fixed - the display now automatically clears as soon as you stop the simulation.
