### ISSUE TITLE
commenting out a Serial.print changes value of subsequent Serial.print

### ISSUE THREAD

**Issue by galed3e3** [wokwi/wokwi-features#386]
**bug** The linked code in "reproduce" shows mx=1073449076 for all values of i, which is an error.  But if line 18 is commented out, then it shows mx=distCurrent for all values of i, which is correct.

**repro** https://wokwi.com/projects/337766540550079060
**expected** the linked code should show mx=distCurrent, for all values of i
**env** Windows 10 Enterprise w/ Firefox v.102.0.1 (64 bit)

Example of incorrect output:
  cur=500 mn=0 mx=1073449076
  cur=600 mn=0 mx=1073449076

Example of correct output (with line 18 commented out):
  cur=300 mx=300
  cur=400 mx=400
  cur=500 mx=500

**Comment by urish** [comment]
Thanks for sharing the link to the code!

The issue is that `mx` was not initialized, so it starts with a semi-random value. You can fix it by changing line 5 to

```cpp
  int seriesMax=0;
```

**Comment by galed3e3** [comment]
Ah. Right. Rookie mistake.  FWIW on a real ESP32, the Arduino IDE compiler gives a nice warning: 
cc1plus.exe: some warnings being treated as errors
exit status 1
'seriesMax' may be used uninitialized in this function [-Werror=maybe-uninitialized]

**Comment by urish** [comment]
Interesting, so does compilation fails on the Arduino IDE? Which version of the Arduino ESP32 Core do you have installed there?

**Comment by galed3e3** [comment]
Yes, compilation fails.  ESP32 core 2.0.4
