### ISSUE TITLE
Defect In Pi Pico MicroPython

### ISSUE THREAD

**Issue by mkudra** [wokwi/wokwi-features#388]
**Describe the bug**
Wokwi Pi Pico Rejects Correct MicroPython Code

**To Reproduce**
Enter the code shown in the attached Word document
Click Run/Restart

**Expected behavior**
OnBoard LED begins to blink

**Environment (please complete the following information):**
 - OS: Windows 10 64bit
 - Browser: FireFox
 - Version: 102.0.1 (64 bit)

**Additional context**

[Why does Running this code result in the displayed error.docx](https://github.com/wokwi/wokwi-features/files/9201190/Why.does.Running.this.code.result.in.the.displayed.error.docx)

**Comment by urish** [comment]
Hello, you can fix the code by changing line 6 to read:

```python
TFT_RST = Pin(0, Pin.OUT)
```

Here's the complete code after correcting the typo:

https://wokwi.com/projects/338372594584519251

Also, next time, please share the project link on Wokwi, as opening .docx files is not trivial for many people (including me).
