### ISSUE TITLE
Allow the selection of multiple components at once

### ISSUE THREAD

**Issue by adriancuadrado** [wokwi/wokwi-features#390]
So it's easier to move or delete or duplicate them. Even better if you can draw a rectangle to select all components inside that rectangle.

**Comment by urish** [comment]
Thanks for the suggestion! Opened this feature for [voting](https://wokwi.com/features?sort=newest#feature-1320475014)

**Comment by urish** [comment]
Update: you can now use the Shift key to select multiple components. Then you can move them all at once, use the "d" key to duplicate the selection, or use the delete key to delete them all at once. Example:

https://user-images.githubusercontent.com/892318/183777509-afba359a-7fa3-49cf-8bc9-cdd856172384.mp4
