### ISSUE TITLE
Button to switch langauges

### ISSUE THREAD

**Issue by urish** [wokwi/wokwi-features#391]
Create a user interface element that will allow users to switch the language of Wokwi. We already have several translations, but currently there is no way for users to select a different language.

**Comment by Marak123** [comment]
Is there maybe some repository with the source code for the wokwi website??

**Comment by urish** [comment]
The source code spans over several repositories, some are open - but the website itself is not open.

Why do you ask?

**Comment by Marak123** [comment]
I wanted to test with different language change combinations. No need to do this in devtools or page fetch.
Regarding the change of this language, do you want the code or the idea where could it be?

**Comment by AriellaE** [comment]
![Screen Shot 2022-08-11 at 15 21 05](https://user-images.githubusercontent.com/35613240/184132213-00fd9ecc-0d81-4937-b046-54f5938e5fec.png)
We added a button to switch language in the user menu.
