### ISSUE TITLE
chinese translation from English

### ISSUE THREAD

**Issue by irongu** [wokwi/wokwi-features#393]
I added some new translations for Chinese, except two places.
First is "Unlist project", I don't understand what this menu option mean, so I couldn't find an accurate translation for it.
Second is the "LCD 16x2", I believe that there is an mistake between the "LCD 16x2" and the "LCD 16x2 (I2C)". 
Below is a screenshot of the original file, I think the "source" word should switch places.
![image](https://user-images.githubusercontent.com/11158814/181765941-46bc4880-b439-4dff-9e46-cebd49d16903.png)
[zh.txt](https://github.com/wokwi/wokwi-features/files/9220122/zh.txt)

**Comment by urish** [comment]
Thank you very much! I updated the texts, can you [please have a look](https://wokwi.com/projects/new?lang=zh) and let me know if they are okay now?

About your questions:

> First is "Unlist project", I don't understand what this menu option mean, so I couldn't find an accurate translation for it.

It means - hide the project from the public web site, so only people who have the link can access it. It's similar to how "unlisted videos" on YouTube works.

> Second is the "LCD 16x2", I believe that there is an mistake between the "LCD 16x2" and the "LCD 16x2 (I2C)".

Yes, this was a mistake indeed. I fixed it now.

**Comment by irongu** [comment]
It works very well!

For the missing translate:
> It means - hide the project from the public web site, so only people who have the link can access it. It's similar to how "unlisted videos" on YouTube works.

So I think the translation should be like this:
```
project.menu.unlistProject:
- source: Unlist project
- translation: 私有化此项目
```

If there is any new texts need to be translated, I will continue to follow up. Thank you very much for this excellent project!

**Comment by urish** [comment]
updated, thank you! 

Closing this issue for now, but feel free to keep posting here new translations as there will be new texts (or open a new issue - both are fine)

**Comment by irongu** [comment]
I translated new content and optmized some old translations.

[zh.txt](https://github.com/wokwi/wokwi-features/files/10811424/zh.txt)

**Comment by urish** [comment]
Thanks! Translations updated

**Comment by irongu** [comment]
Chinese translations of new content

[zh.txt](https://github.com/wokwi/wokwi-features/files/12272580/zh.txt)

Besides, I noticed that not all wokwi-docs pages have Chinese translations, how can I help translate wokwi-docs?

**Comment by urish** [comment]
Thanks, updated!

To translate wokwi-docs:
1. Here is a quick guide for setting up a local environment for translating: https://github.com/wokwi/wokwi-docs/blob/main/translating.md. This is how @arcostasi (who is working on the Portuguese translation) works.
2. The README also contains links to quickly setup an online development environment (in the cloud): https://github.com/wokwi/wokwi-docs#online-development

And if you have any specific questions, feel free to open an issue on wokwi-docs
