### ISSUE TITLE
DC motor and motor driver component

### ISSUE THREAD

**Issue by normc812** [wokwi/wokwi-features#397]
hob

**Is your feature request related to a problem? Please describe.**
A clear and concise description of wyhat the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**

**Comment by urish** [comment]
Hello! Welcome to the fun world of Arduino (and Wokwi :-)

There's already an issue to track the DC motor + L298 (which is similar in function to the L293), #220. I'm closing this request as a duplicate, but feel free to add a comment on the other issue with your use case.
