### ISSUE TITLE
Failed with no messages

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#4]
The link is here: https://wokwi.com/arduino/projects/279890929738842636

It was working a day before. I had shared it over email. I had opened it in another PC to create some stunning GIFs.
When I tried to open it today, it is popping up an error. 

![image](https://user-images.githubusercontent.com/68117142/96893259-256e9f00-14a8-11eb-83b3-e99b86750b16.png)

I also tried to open the link in the incognito mode, it still popping the same error.

I tried using firefox too. It is not compiling

![image](https://user-images.githubusercontent.com/68117142/96893572-78485680-14a8-11eb-9312-a64ab9159830.png)

Also, blink standard code is not building. I believe some work is going on in the background :)

**Comment by urish** [comment]
Thanks for reporting! Fixed :-)
