### ISSUE TITLE
Joystick element for arduino

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#40]
Joystick element for arduino

**Comment by urish** [comment]
Can you please give a link to a reference device?

**Comment by Puneethkumarsn** [comment]
https://www.arduino.cc/en/Tutorial/BuiltInExamples/JoystickMouseControl

https://thestempedia.com/tutorials/what-is-joystick/

https://www.adafruit.com/product/512

**Comment by urish** [comment]
Tracked by wokwi/wokwi-elements#54
