### ISSUE TITLE
Manage wokwi club settings.

### ISSUE THREAD

**Issue by leftCoast** [wokwi/wokwi-features#400]
The creation of a wokwi club membership is easy and documented, as it should be. Editing your woki club setting or closing your club membership is not. This needs to be addressed.

We need a "Manage wokwi club" page that has these controls on it. AND have these controls added to the documentation. As far as I can tell, they are not.

**Comment by urish** [comment]
Hi Jim! Can you elaborate on which controls do you expect to find in the "Manage Wokwi Club" page?

**Comment by leftCoast** [comment]
Cost settings per month/per year 
Close account - To round out the user options.

**Comment by urish** [comment]
> Cost settings per month/per year

Actually, these custom options are now gone - users have only a single choice between monthly / yearly payment. 

> Close account - To round out the user options

👍

**Comment by leftCoast** [comment]
Amount per payment? Or is that fixed now as well?

**Comment by urish** [comment]
Fixed now. Simplifying things :)

**Comment by urish** [comment]
Done - https://wokwi.com/dashboard/subscriptions

also updated the [docs](https://docs.wokwi.com/getting-started/wokwi-club)
