### ISSUE TITLE
Support seting a different I2C address (different from the default 0x27) on character LCDs with PCF8574T (wokwi-lcd1602, wokwi-lcd2004)

### ISSUE THREAD

**Issue by Gjorgjevikj** [wokwi/wokwi-features#404]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by urish** [comment]
If I understand correctly, the range of valid addresses is 0x20 to 0x27.

What's the use case for changing the address?

**Comment by Gjorgjevikj** [comment]
Connecting multiple displays to the same I2C bus. Probably not a most common scenario, but can be usable in certain projects. It does exist as an option on the hardware modules, anyway.

**Comment by urish** [comment]
Apparently, it's already supported - use the "i2c-address" attribute to set the address, e.g.:

```json
    {
      "type": "wokwi-lcd2004",
      "id": "lcd2",
      "top": 276.63,
      "left": -16.62,
      "attrs": { "pins": "i2c", "i2c-address": "0x20" }
    }
```

docs: https://docs.wokwi.com/parts/wokwi-lcd1602#attributes

**Comment by Gjorgjevikj** [comment]
Probably my bad. I did search for that but did not find it on 

https://docs.wokwi.com/parts/wokwi-lcd1602#i2c-configuration

 

Thanks, anyway.

 

BTW, 

although not so common, LCDs with the same Hitachi driver and same connections with different geometries also exist 

8x1, 16x4, 24x2, 40x2, …

Probably it is not to hard to add some of them… just a thought...

**Comment by urish** [comment]
> Probably my bad. I did search for that but did not find it on
> https://docs.wokwi.com/parts/wokwi-lcd1602#i2c-configuration

Added a note there!
