### ISSUE TITLE
Simulator Schematic usability: drag to select multiple items

### ISSUE THREAD

**Issue by toybuilder** [wokwi/wokwi-features#409]
Duplicating/Moving a collection of many interrelated parts is frustrating because you have to select each component one by one.  

Click-drag across the canvas to select all components within (left-to-right drag) or touching (right-to-left drag) the box would greatly speed up this process, making it much faster/easier to reorganize the schematic.

**Comment by urish** [comment]
Done! 

Shift-click then drag to select multiple items. Selection mode is always touching at the moment. In the future we may add the all components within mode, as suggested.

Thanks again for creating this feature request, this is indeed very useful.
