### ISSUE TITLE
not important: trying to check for errors on empty page pops error - can it be handled?

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#41]
open the quick start page:

https://wokwi.com/share

Click on the button: "check for error"

I understand it is right in its own way though t expect the setup function. 

![image](https://user-images.githubusercontent.com/68117142/103927562-8d945f00-5140-11eb-81b4-0fa10a71d7b5.png)

![image](https://user-images.githubusercontent.com/68117142/103927578-94bb6d00-5140-11eb-8253-88250fb12e9b.png)

**Comment by urish** [comment]
How would you expect it to work in this case?

**Comment by Puneethkumarsn** [comment]
if it is empty, check for errors button need not be active
OR
it can state, no content or file is empty

**Comment by urish** [comment]
> if it is empty, check for errors button need not be active

Sounds good!
