### ISSUE TITLE
Simulator Schematic usability: rule lines every 5 or 10 dots

### ISSUE THREAD

**Issue by toybuilder** [wokwi/wokwi-features#410]
When a grid is a sea of dots, there is not enough visual reference to tell when items that are not close by are aligned.

Having a faint rule line every 5 or 10 dots would make it easier to quickly tell that you have aligned or evenly spaced your items.

**Comment by urish** [comment]
Thanks for the feedback! I'll look into it - if it's trivial, might add it quickly. Otherwise, will open this feature for voting.

**Comment by urish** [comment]
Closing as this hasn't received any votes within the past 6 months
