### ISSUE TITLE
Serial.availableForWrite() returns 0 on Arduino nano board

### ISSUE THREAD

**Issue by alonbl** [wokwi/wokwi-features#415]
**Describe the bug**

The `Serial.availableForWrite()` returns 0 on Arduino nano board while in esp32 it works correctly.

**To Reproduce**

Consider the following program:

```c++
void setup() {
  Serial.begin(115200);
  Serial.println(Serial.availableForWrite());

}

void loop() {
  Serial.println(Serial.availableForWrite());
}
```

**Expected behavior**

Any number is sufficient... however, in Arduino Nano it always returns 0.
Async programs that rely on the available buffer to wrote are broken.
In esp32 it works correctly.
In real board we get 63.

**Environment (please complete the following information):**

Reproducible at https://wokwi.com/ without any special environment settings.

**Additional context**

N/A

**Comment by urish** [comment]
Thanks for reporting!

Are you sure it's always returning 0?

I tested here, and I can see it does initially return larger values:

![image](https://user-images.githubusercontent.com/892318/189541129-70a7fdf9-2946-4541-b129-b8964fe93be3.png)

The values are slightly different compared to the physical board, which drops to 0 faster:

![image](https://user-images.githubusercontent.com/892318/189541072-adff925b-36ac-48ba-867b-3fe34f29b24e.png)

**Comment by alonbl** [comment]
Thanks for the prompt reply!

It is very strange!!! I can swear that it was zero constant... but now I cannot reproduce this.

I will reopen if I am able to reproduce.
