### ISSUE TITLE
Having the button component selected when running the script causes button to fail

### ISSUE THREAD

**Issue by jaseinatl** [wokwi/wokwi-features#417]
**Describe the bug**
After modifying a button element, with it still selected, I hit the green triangle compile button and run my script. However, clicking on the button fails to trigger the button event. It does nothing. 
Once I figured it out, I was able to restore functionality to the button by deselecting it in the editor, then re-compiling my script and it worked fine. 
I'm not sure if this is true for all components or just the button component. 

**To Reproduce**
Here is a link to the problem with a comment description:
https://wokwi.com/projects/343030951543046740

**Expected behavior**
The button should be "deselected" in the editor and should work when compiled and clicked.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version Latest

**Additional context**

**Comment by urish** [comment]
Thanks for reporting, fixed!
