### ISSUE TITLE
SSD1306 vertial flip painting errors - out by 1?

### ISSUE THREAD

**Issue by penfold42** [wokwi/wokwi-features#422]
**Describe the bug**
I think there's an out by 1 error on either screen painting or rendering.

It looks like 
- row 0 is still at the top of the screen
- row 1 is on the bottom row (when it should be up one)

**To Reproduce**
[](https://wokwi.com/projects/343460442395378259)
Then O=2 and O=0 to flip between Vflip and normal
Normal:
![image](https://user-images.githubusercontent.com/13173376/192076339-06038057-fa03-4408-9e6d-11b3943c9269.png)

Vflip:
![image](https://user-images.githubusercontent.com/13173376/192076343-f3b1eba5-e65b-4b3b-80b7-1c9290f0ed45.png)

**Expected behavior**
Vertical flip should look something like:
![image](https://user-images.githubusercontent.com/13173376/192076444-f5cdce98-830d-48e9-aabd-de7a20426ee1.png)

**Comment by urish** [comment]
Reproduction: https://wokwi.com/projects/343460442395378259 (same instructions as [here](https://github.com/wokwi/wokwi-features/issues/420#issuecomment-1255732881))

**Comment by penfold42** [comment]
> Reproduction: https://wokwi.com/projects/343460442395378259 (same instructions as [here](https://github.com/wokwi/wokwi-features/issues/420#issuecomment-1255732881))

yes, sorry - must have lost it in an edit as i added the pictures.

**Comment by urish** [comment]
Fixed! Thanks again for crafting such helpful bug report. It really speeds up the development!

**Comment by penfold42** [comment]
confirmed, thanks!
