### ISSUE TITLE
Library dependency parsing is not working correctly

### ISSUE THREAD

**Issue by dz0ny** [wokwi/wokwi-features#424]
**Describe the bug**
A library contains dependency which is underscored, library in your repo contains space and therefore cannot be recognised.

**To Reproduce**
https://wokwi.com/projects/343889711620686419

**Expected behavior**
Code compiles.

**Environment (please complete the following information):**
 - OS: [e.g. iOS/Android/Windows]

**Additional context**

**Comment by urish** [comment]
Thanks for the detailed report. Unfortunately, this is not a problem with Wokwi, rather the LcdMenu library, which has the wrong dependency. 

To verify this, I just tried installing LcdMenu from the Arduino CLI and got the same error message:

```
$ ./arduino-cli lib install LcdMenu
Error installing LcdMenu: Error resolving dependencies for LcdMenu@: dependency 'LiquidCrystal_I2C' is not available
```

You may want to the send [library repo](https://github.com/forntoh/LcdMenu/blob/master/library.properties) a pull request to fix the issue.
