### ISSUE TITLE
Pan in and out compromised the text label size

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#428]
**Describe the bug**
The text (PIN label, IC name, and any other text present in the Wokwi parts in the simulation window) size was reduced. It is no more proportional to the Wokwi element
![image](https://user-images.githubusercontent.com/68117142/194313134-9ca8e08a-1728-450c-840c-6d9a015ecc73.png)

Link of the project: https://wokwi.com/projects/306031380875182657
![image (1)](https://user-images.githubusercontent.com/68117142/194313097-ac111539-3575-409b-8917-75d0c4cdbb50.png)

**To Reproduce**
Not yet reproducible

**Expected behavior**
text size should always be proportional to the wokwi element size
**Environment (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version 105.0.5195.127

**Comment by urish** [comment]
This seems to be a bug in Chrome - did you observe it in any other browsers?

**Comment by matititam** [comment]
Just reporting again - Chrome browser, Windows 11
![image](https://user-images.githubusercontent.com/68117142/195665805-47d2ae11-2018-46ba-916d-d97781814bfc.png)

again during the zooming operation. I will try in other browsers for a while

**Comment by urish** [comment]
Found a way to reliably reproduce this in chrome:

1. Go to https://wokwi.com/projects/new/arduino-uno
2. Zoom in (or out) using the mouse wheel
3. Click on the Arduino Uno part to select it
4. Press Ctrl+A

The issue should reproduce.

**Comment by urish** [comment]
This has been fixed
