### ISSUE TITLE
Add "flip" component to the list of attributes

### ISSUE THREAD

**Issue by jaseinatl** [wokwi/wokwi-features#430]
**Is your feature request related to a problem? Please describe.**
In the layout mode, sometimes the layout could be significantly simplified if the component were flipped on the screen.

**Describe the solution you'd like**
Add the "flip" property to elements like "rotate". So "flip"::"horizontal" or perhaps flip:1 for horizontal and flip:0 for vertical. or flip:y or flip: x   Adding this attribute would not affect the function of the element, just how it appeared on the screen. 

Not important at all, just thought it would be easy to do and might help with connections. I've run into several times I wish I'd had this feature.  I'm sure there are much better examples of the benefits of being able to flip a component.

![Flip Request](https://user-images.githubusercontent.com/755697/194975556-f876bb23-ccb6-4791-9f9d-6fe56494b9af.png)

**Comment by urish** [comment]
Thanks for the detailed request!

LEDs already have a "flip" attribute: https://docs.wokwi.com/parts/wokwi-led#examples (see the last example in the linked table)

You can toggle it by clicking on the LED and then pressing "P", or by clicking this button:

![image](https://user-images.githubusercontent.com/892318/195008369-5539f690-7371-4bd8-a0f0-7c6a2afd5f51.png)

For most other parts, flip does not make sense.
