### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by mpcour** [wokwi/wokwi-features#432]
First attempt to have a french language file.
[fr.txt](https://github.com/wokwi/wokwi-features/files/9794692/fr.txt)
(json is not allowed as file type for attachments)

**Comment by urish** [comment]
Thanks! The translations are now online, can you have a look and report if there are any issues?

**Comment by mpcour** [comment]
After a quick test/check it is "So far, so good " !
I'm waiting for comments/criticisms .........
