### ISSUE TITLE
ESP32-S2 PWM Frequency

### ISSUE THREAD

**Issue by Dlloydev** [wokwi/wokwi-features#435]
With the setup as shown [here](https://github.com/Dlloydev/ESP32-ESP32S2-AnalogWrite/discussions/19) compared with the WokWi example [here](https://wokwi.com/projects/334765722024542804), the simulated frequency is too high (x2).

**Comment by urish** [comment]
Thanks for reporting! So the phases are fine, and the frequency is the only problem?

**Comment by Dlloydev** [comment]
Yes, only the frequency.

I haven't done much testing with the phase shift as it uses a low level command and I don't expect it to be very accurate because the LEDC hardware timers don't support synchronization.

**Comment by urish** [comment]
Thanks! Have you had a chance to test it with the ESP32 too? Or only the S2?

**Comment by Dlloydev** [comment]
Only the S2. My ESP32 is hiding somewhere. I guess lost hardware is a side effect of using simulation software!

**Comment by urish** [comment]
> I guess lost hardware is a side effect of using simulation software!

Can I quote that? 😉

**Comment by Dlloydev** [comment]
Sure!

**Comment by urish** [comment]
Fix is up - can you please check now and report?

**Comment by Dlloydev** [comment]
Wow, that was fast. Looks good!

![image](https://user-images.githubusercontent.com/63488701/197355175-0bb765a9-f79f-440c-a1c8-560b80d97d3e.png)
