### ISSUE TITLE
ESP32 Servo animation is NOT working 

### ISSUE THREAD

**Issue by DromaDox** [wokwi/wokwi-features#437]
**Describe the bug**

ESP32 Servo motor animation is not working.
Other boards work fine but I think it's ESP32 simulation releated

**To Reproduce**
I've been using @urish's project without any modification (https://wokwi.com/projects/323706614646309460)

**Comment by urish** [comment]
Thanks for reporting, fixed!

**Comment by DromaDox** [comment]
I confirm .
Thanks for acting fast <3
