### ISSUE TITLE
Able to change the pin names of the Logic Analyzer

### ISSUE THREAD

**Issue by cheyao** [wokwi/wokwi-features#442]
Being able to change the pin names of the Logic Analizer wold be a real nice feature so that you can know what the pins are for in logic analizer apps (like scansion)

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

Being able to change the pin names

**Comment by urish** [comment]
Added a "channelNames" attribute for this purpose: 

https://docs.wokwi.com/guides/logic-analyzer#customizing-the-channel-names

@Koepel mind updating your [Logic Analyzer example](https://wokwi.com/projects/325933824665977428) to use this new feature?

**Comment by Koepel** [comment]
Added channel names and changed explanation for using the channel names.

**Comment by urish** [comment]
Amazing, thanks!
