### ISSUE TITLE
Can Serial Terminal Support Parity bits implementation as well?

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#448]
I'm always frustrated when I test my code without the actual hardware. The code is for the UART communication test with a module. The module needs the parity bit to be used for error detection. 

As I am aware, the Serial Terminal in the Arduino IDE doesn't support the option to set the parity bits.

**Describe the solution you'd like**
Can we have the odd part bit settings enabled for the serial terminal? This helps in verifying my code using the serial terminal on Wokwi for particular use cases where party bits, as well as different-size data bits, are used. 

Link: https://wokwi.com/projects/307248101781930560

![image](https://user-images.githubusercontent.com/68117142/201508091-223f6ab5-cf37-4cd0-b5c3-d47d234f658f.png)

**Comment by urish** [comment]
Parity bits are too niche, so we won't be adding support for them.
