### ISSUE TITLE
DHT sensor examples shared are misbehaving

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#45]
**Link**: https://github.com/winlinvip/SimpleDHT/issues/45

**Examples** are linked in the above issue page

![image](https://user-images.githubusercontent.com/68117142/104030360-4c0fbc80-51f1-11eb-823a-1434fe5e1002.png)

![image](https://user-images.githubusercontent.com/68117142/104030392-5467f780-51f1-11eb-8f90-eb6c2bb64deb.png)

**Comment by urish** [comment]
Thanks for reporting, fixed! 

I also fixed the issue with [this example](https://wokwi.com/arduino/projects/286863323599733260) mentioned in winlinvip/SimpleDHT#45, it should now behave correctly :-)
