### ISSUE TITLE
MCP2515 CAN Bus

### ISSUE THREAD

**Issue by wastegate** [wokwi/wokwi-features#451]
**Is your feature request related to a problem? Please describe.**
Not related to a problem.

**Describe the solution you'd like**
Add on board to emulate MCP2515 shield for CAN Bus communications.

**Comment by urish** [comment]
Thanks, opened this for [voting](https://wokwi.com/features?sort=newest#feature-1452476943).

Can you please share more details about the use case? e.g. what kind of project you'd like to build with the MCP2515? Do you need other CAN bus parts?

**Comment by wastegate** [comment]
Well at the moment, we use a MCP2515 to read CAN bus data from vehicle ECU and display the parameters to a ssd1306. 

It would be great to be able to test code with the MCP2515 library and maybe even completely awesome would be a way to have two arduinos talking to each other over a virtual CAN bus.

**Comment by urish** [comment]
Closing as this hasn't received any votes within the past 6 months

**Comment by nshobe** [comment]
Well I'd vote for this. I want to develop multiple automotive related projects all of which require can bus to interact with existing systems.

Automotive Use Cases:
 - Data Logger
 - Smart system interaction ( if fuel pressure drop under power, trigger second fuel pump)
 - Static System interaction ( switch to secondary fuel system )
 - Extended Data Inputs ( brake pressure sensors, air temp before/after turbos, etc)

My point is that can bus is the standard communication for anything automotive and nearly every hobbyist is a tinkerer and once you've fully committed to go as far as removing the factory engine computer there's no "perfect" aftermarket solution and there's always some feature gap that something like an arduino could fit into.

There's even a github project for someone trying to make a full PDM (power distribution module) with current-sense amplifiers, and MOSFETs for a traditional fuse and relay replacement unit, ideally CAN bus integrated. Project uses a STM32 and MCP2515.
