### ISSUE TITLE
Basic Switch with Normally Open (NO), Normally Closed (NC) and Common (COM) Contact

### ISSUE THREAD

**Issue by MicroBeaut** [wokwi/wokwi-features#452]
**Is your feature request related to a problem? Please describe.**

The Basic Switch is a Future part.

**Describe the solution you'd like**
When I need an NC contact switch, I have to use the DIP switch.
To easily do a simulation, better to have the basics switch in the Wokwi.
For example:
I need Sensor as NC Contact. I only wired the uC pin to the NC and COM of the Basic Switch.

**Comment by urish** [comment]
Hello! How about the [wokwi-slide-switch](https://docs.wokwi.com/parts/wokwi-slide-switch)?

**Comment by MicroBeaut** [comment]
You can close this case. Thank you 😃 .
