### ISSUE TITLE
can you please add STM32 microcontroller board using arduino ide.

### ISSUE THREAD

**Issue by L0ke5h** [wokwi/wokwi-features#453]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by urish** [comment]
Thanks, we already have a request for that: #363 

You can see its status and vote here: https://wokwi.com/features#feature-1270975357

**Comment by urish** [comment]
Note that this has been implemented, e.g.: https://wokwi.com/projects/367245102561225729

For more info, check out the STM32 docs: https://docs.wokwi.com/parts/board-st-nucleo-l031k6

**Comment by L0ke5h** [comment]
Thank you so mauch....😊
