### ISSUE TITLE
RFID READ

### ISSUE THREAD

**Issue by QUANGQUY1305** [wokwi/wokwi-features#455]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by urish** [comment]
Do you mean an [MFRC522](https://www.nxp.com/docs/en/data-sheet/MFRC522.pdf) reader, like this one?

![image](https://user-images.githubusercontent.com/892318/202899972-f061b763-5a6c-4e99-9b5e-5d7519855858.png)

**Comment by urish** [comment]
Duplicate of #359
