### ISSUE TITLE
ESP32 low speed mode sets PWM to 1/10 of frequency setting

### ISSUE THREAD

**Issue by Dlloydev** [wokwi/wokwi-features#460]
**Describe the bug**
ISSUE: In low speed mode only, the PWM frequency at the output is 1/10th of the defined frequency when set to 979 Hz or higher at 10-bit resolution.  Note: 1/978 = 1023 (10-bit)

**To Reproduce**
[Example](https://wokwi.com/projects/349124916130349652)

**Expected behavior**
Output PWM frequency = set PWM frequency.

**Environment (please complete the following information):**
 - OS:  Windows 10
 - Browser: FireFox

**Additional context**
High speed mode works OK.

**Comment by urish** [comment]
Fixed!

Thanks for the detailed report.
