### ISSUE TITLE
How to load a Spiffs or LittleFS partition in wokwi with esp32 for simulation.?

### ISSUE THREAD

**Issue by laldana73** [wokwi/wokwi-features#462]
Hello.

there are some way to load a Spiffs or LittleFS partition in wokwi with esp32 for simulation.?

Thanks

**Comment by urish** [comment]
Hello, if you build the binary on your computer, you can include an SPIFFS / LittleFS partition in the .bin file: https://docs.wokwi.com/guides/esp32#custom-application-bin-file

What project are you working on?

Also, in the future, [the discord community](https://wokwi.com/discord) is a better place for questions. There is a #questions channel there, where any questions about Wokwi are welcome.

**Comment by laldana73** [comment]
Thanks, I am testing pikascript on esp32

**Comment by laldana73** [comment]
I have created an unique bin file with  bootloader.bin, partition-table.bin, pikascript.bin, ota_data_initial.bin, and storage.bin .
I can flash it with esptool.py on my esp32c3, but is not working on wokwi.

ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
configspi:0x000000b9
SPIWP:0x00
mode:DIO, clock div:1
load:0x3fcd6100,len:0x420
load:0x403ce000,len:0x90c
load:0x403d0000,len:0x2370
entry 0x403ce000
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021

rst:0xc (RTC_SW_CPU_RST),boot:0x8 (SPI_FAST_FLASH_BOOT)
configspi:0x000000b9
SPIWP:0x00
mode:DIO, clock div:1
load:0x3fcd6100,len:0x420
load:0x403ce000,len:0x90c
load:0x403d0000,len:0x2370
entry 0x403ce000
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021

... and continue again and again

**Comment by urish** [comment]
You may need to add a "firmwareOffset" attribute to the "attrs" section of the esp32c3 chip in diagram.json, to tell it to load this .bin file at address 0:

```json
{
      "type": "board-esp32-c3-devkitm-1",
      "id": "esp",
      "top": -3.33,
      "left": -23.33,
      "attrs": { "firmwareOffset": "0" }
}
```

**Comment by laldana73** [comment]
Perfect!! Is working Now
Thanks @urish

**Comment by urish** [comment]
Awesome! I wasn't familiar with pikascript until now. Are you one of the developers?

**Comment by laldana73** [comment]
No, i am developing a project based on pikascript.
I found it very interesting, and i hope be contributing soon
