### ISSUE TITLE
ESP32S2 simulation some GPIO non functional

### ISSUE THREAD

**Issue by PaRaDoXz81** [wokwi/wokwi-features#465]
**Describe the bug**
ESP32S2 simulation GPIO 17, 34 to 45 do not work.
Simulating online outputs do not function.

**To Reproduce**
Simple blinky to operate all GPIO with LED, or logic analyzer not showing correct output of GPIO.
https://wokwi.com/projects/349558637604110932

**Expected behavior**
All GPIO are expected to blink the corresponding LED

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 107.0.1418.56 (Official build) (64-bit)

**Comment by urish** [comment]
Thanks for reporting! Have you tested this on real hardware as well?

**Comment by PaRaDoXz81** [comment]
Hi Uri
Yes I have, this all gpio outputs worked fine on a esp32-s2 module.

Kind regards,
Jason Schoch

**Comment by urish** [comment]
Thanks, investigating

**Comment by urish** [comment]
Alright, fix is up - can you please test again with Wokwi and report?

**Comment by PaRaDoXz81** [comment]
Looks Good, tests well. Thank you

Kind Regards,

Jason


Jason Schoch

30 Santa Barbara Court
Waikiki,  Western Australia, 6169
M +61 427 198 595
***@***.******@***.***>
