### ISSUE TITLE
Request for 3-switch DIP module (from FB group for HERO/Arduino project)

### ISSUE THREAD

**Issue by Chappie78** [wokwi/wokwi-features#467]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I spoke to someone from Wokwi in the Hero Project/Arduino group after finding your simulator (AWESOME, btw) and asked for a 3-switch DIP - you only have an 8-switch DIP in the item list. They suggested I post it here.

Also, while placing the 8-switch DIP on the simulator, both rows don't connect, I had to connect the top row by drawing a 'wire' from the top connections to a space on the breadboard. Am I doing something wrong or is this a bug?

**Comment by urish** [comment]
Thanks! I opened this request for [voting](https://wokwi.com/features?sort=newest#feature-1469319677)

> Also, while placing the 8-switch DIP on the simulator, both rows don't connect, I had to connect the top row by drawing a 'wire' from the top connections to a space on the breadboard. Am I doing something wrong or is this a bug?

It sounds like a bug indeed. Can you please [open a separate bug report](https://github.com/wokwi/wokwi-features/issues/new/choose) for this?

**Comment by urish** [comment]
Update: we already fixed the issue with the 8-DIP switch + breadboard, no need to open a separate report.

**Comment by urish** [comment]
Closing as this hasn't received any votes within the past 6 months
