### ISSUE TITLE
Bug report - 8-switch DIP module does not connect on top row when placed on Breadboard

### ISSUE THREAD

**Issue by Chappie78** [wokwi/wokwi-features#468]
**Describe the bug**
While placing the 8-switch DIP on the simulator, both rows don't connect, I had to connect the top row by drawing a 'wire' from the top connections to a space on the breadboard

**To Reproduce**
Just place the DIP switch on the breadboard

**Expected behavior**
When placing the switch, I expect all the connections to go green to show they are 'in', as per the bottom row.

**Environment (please complete the following information):**
 - Mac OS (latest)
 - Browser = Chrome
 - Version 107.0.5304.110

**Additional context**
See attached image.

![image](https://user-images.githubusercontent.com/119490831/204802743-47795022-fec7-42bc-adb7-8712649ee404.png)

**Comment by urish** [comment]
Thanks for the detailed report.

Fixed! Can you please test now?

**Comment by Chappie78** [comment]
Magic! Looks like it's working now thanks :)

![image](https://user-images.githubusercontent.com/119490831/204843077-a12268a9-f289-4d88-aca4-f7f996b7c704.png)
