### ISSUE TITLE
Raspberry Pico Rust support

### ISSUE THREAD

**Issue by passcod** [wokwi/wokwi-features#469]
Like #334, but for the Pico!

**Comment by urish** [comment]
Thanks for the suggestion!

Is this something you'd like to work on? Is there a big community around Rust + Pi Pico?

**Comment by passcod** [comment]
Not nearly as much as ESP, but there's a decent community around Rust and RP2040 (and Pico by extension). The original post in #334 mentioned Rust/Pico too! I was just passing by and thought that was a curious omission given [the rust page](https://wokwi.com/rust) and [the pico sketch](https://wokwi.com/projects/new/pi-pico?template=pi-pico); I'm not (yet?) a wokwi user.

**Comment by urish** [comment]
Thanks! 

With ESP32, the Espressif Rust Team has been really helpful putting together all the example projects, etc.

I've opened this for [voting](https://wokwi.com/features?sort=newest#feature-1470657750), even though - this would probably move forward much faster if there was someone who wanted to work on it and push it forward.

**Comment by urish** [comment]
Closing, as this hasn't received any votes in the past 6 months

**Comment by Koepel** [comment]
There are regularly requests for Rust on the Raspberry Pi Pico in the Discord channel.

**Comment by sturmenta** [comment]
I would really love to try Rust on a Raspberry Pi Pico using your app ❤️

**Comment by urish** [comment]
For future people who come across this issue: you can still simulate Rust on Raspberry Pi Pico with Wokwi, but you'll have to compile the firmware yourself. Then you can load it into [Wokwi for VS Code](https://docs.wokwi.com/vscode/getting-started) or [Wokwi for Intellij](https://plugins.jetbrains.com/plugin/23826-wokwi-simulator).
