### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by F8ASB** [wokwi/wokwi-features#473]
{
  "userMenu.signIn": "S'identifier",
  "userMenu.signUp": "S'inscrire",
  "userMenu.discord": "Discord",
  "userMenu.myProjects": "Mes projets",
  "userMenu.theClub": "Le Club",
  "userMenu.featureRoadmap": "Feuille de route du developpement",
  "userMenu.language": "Language",
  "userMenu.logout": "Déconnection",
  "project.header.save": "Sauvegarder",
  "project.header.share": "Partager",
  "project.header.likeProjectTooltip": "Aimer ce projet",
  "project.header.unlikeProjectTooltip": "Ne plus aimer ce projet",
  "project.menu.saveACopy": "Sauvegarder une copie",
  "project.menu.lockProject": "Bloquer le projet",
  "project.menu.unlistProject": "Désinscrire le  project",
  "project.menu.downloadProjectZip": "Télécharger le projet en ZIP",
  "project.error.saveFailed": "Erreur de sauvegarde: projec bloqué!",
  "project.error.signInToLikeProject": "Connectez vous pour imer le projet.",
  "project.shareDialog.title": "Partager le projet",
  "project.shareDialog.copyToClipboard": "Copier dans le presse-papier",
  "project.shareDialog.pleaseSave": "Pour partager le projet, sauvegarder avant:",
  "project.shareDialog.saveProject": "Sauvegarder le projet",
  "project.shareDialog.closeButton": "Fermer",
  "simulator.main.restart": "Redémarrer la simulation",
  "simulator.main.start": "Démarrer la simulation",
  "simulator.main.resume": "Reprendre",
  "simulator.main.pause": "Pause",
  "simulator.main.addNewPart": "Ajouter un nouveau composant",
  "simulator.main.stopSimulation": "Stopper la simulation",
  "simulator.main.zoomGridTooltip": "Zoom, Grille, et plus",
  "simulator.buildFailedDialog.title": "Erreur compilation!",
  "simulator.downloadingDataDialog.title": "Télécharger des données sur SD Card...",
  "editor.fileMenu.formatSuccessful": "Formatage du code réussi",
  "editor.fileMenu.formatAlready": "Code déja formaté",
  "editor.fileMenu.formatCode": "Format du code",
  "editor.fileMenu.rename": "Renommer",
  "editor.fileMenu.delete": "Effacer",
  "editor.fileMenu.newFile": "Nouveau fichier...",
  "editor.fileMenu.uploadFile": "Charger fichier(s)...",
  "editor.fileMenu.confirmDelete": "Cela supprimera {{filename}}. Dois-je continuer ?",
  "editor.fileMenu.error.invalidFileName": "Nom de fichier invalide: caractère {{char}} n'est pas autorisé.",
  "editor.fileMenu.error.invalidFileType": "Type de fichier invalide. Fichiers supportés: {{types}}.",
  "editor.fileMenu.error.fileExists": "Un fichier avec ce nom existe déjà",
  "editor.fileMenu.error.uploadFailed": "Certains fichiers ne peuvent pas être envoyés!",
  "editor.sdCard.uploadFiles": "Charger les fichiers",
  "editor.sdCard.uploadCompleteFolder": "Envoyer le dossier complet",
  "editor.sdCard.deleteAllFiles": "Effacer tous les fichiers",
  "editor.sdCard.noFilesYet": "Aucun fichier actuellement. Merci d'envoyer des fichiers.",
  "diagram.menu.undo": "Annuler",
  "diagram.menu.redo": "Refaire",
  "diagram.menu.fit": "Adapter",
  "diagram.menu.zoomIn": "Zoom avant",
  "diagram.menu.zoomOut": "Zoom arrière",
  "diagram.menu.toggleGrid": "Changer de grille",
  "diagram.menu.fullScreen": "Pleine écran",
  "diagram.menu.exitFullScreen": "Sortir du pleine écran",
  "diagram.menu.help": "Aide",
  "diagram.addPart.board-esp-01": "ESP-01 Modem WiFi",
  "diagram.addPart.board-ssd1306": "Ecran SSD1306 OLED",
  "diagram.addPart.wokwi-74hc165": "74HC165 Input Shift Register (PISO)",
  "diagram.addPart.wokwi-74hc595": "74HC595 Registre à decalage",
  "diagram.addPart.wokwi-7segment": "Afficheur 7 segments",
  "diagram.addPart.wokwi-7segment-4digits": "Afficheur 7 segments(4 digits)",
  "diagram.addPart.wokwi-a4988": "A4988 Driver moteur pas à pas",
  "diagram.addPart.wokwi-analog-joystick": "Joystick analogique",
  "diagram.addPart.wokwi-biaxial-stepper": "Moteur pas à pas Bi axe",
  "diagram.addPart.wokwi-breadboard": "Plaque d'essais (beta)",
  "diagram.addPart.wokwi-breadboard-half": "Demie plaque d'essais (beta)",
  "diagram.addPart.wokwi-breadboard-mini": "Mini plaque d'essais (beta)",
  "diagram.addPart.wokwi-buzzer": "Buzzer",
  "diagram.addPart.wokwi-dht22": "DHT22",
  "diagram.addPart.wokwi-dip-switch-8": "DIP Switch 8",
  "diagram.addPart.wokwi-ds1307": "DS1307 RTC",
  "diagram.addPart.wokwi-flip-flop-d": "Logic: Flip-Flop D",
  "diagram.addPart.wokwi-gate-and-2": "Logic: porte AND",
  "diagram.addPart.wokwi-gate-nand-2": "Logic: porte NAND",
  "diagram.addPart.wokwi-gate-not": "Logic: porte NOT",
  "diagram.addPart.wokwi-gate-or-2": "Logic: porte OR",
  "diagram.addPart.wokwi-gate-xor-2": "Logic: porte XOR",
  "diagram.addPart.wokwi-gnd": "Symbole GND",
  "diagram.addPart.wokwi-hc-sr04": "HC-SR04 Capteur distance Ultrason",
  "diagram.addPart.wokwi-hx711": "HX711 Load Cell (50kg)",
  "diagram.addPart.wokwi-hx711-5kg": "HX711 Capteur de pression (5kg)",
  "diagram.addPart.wokwi-ili9341": "Ecran ILI9341 2.8\" TFT-LCD",
  "diagram.addPart.wokwi-ir-receiver": "Récepteur IR",
  "diagram.addPart.wokwi-ir-remote": "Télécommande IR",
  "diagram.addPart.wokwi-ks2e-m-dc5": "Relai DPDT",
  "diagram.addPart.wokwi-ky-040": "KY-040 Encodeur rotatif",
  "diagram.addPart.wokwi-lcd1602": "LCD 16x2",
  "diagram.addPart.wokwi-lcd1602-i2c": "LCD 16x2 (I2C)",
  "diagram.addPart.wokwi-lcd2004": "LCD 20x4",
  "diagram.addPart.wokwi-lcd2004-i2c": "LCD 20x4 (I2C)",
  "diagram.addPart.wokwi-led": "LED",
  "diagram.addPart.wokwi-led-bar-graph": "BarGraph LED",
  "diagram.addPart.wokwi-led-ring": "Anneau NeoPixel",
  "diagram.addPart.wokwi-logic-analyzer": "Analyseur Logique (8 channels)",
  "diagram.addPart.wokwi-max7219-matrix": "Matrice LED (MAX7219)",
  "diagram.addPart.wokwi-membrane-keypad": "Clavier",
  "diagram.addPart.wokwi-microsd-card": "microSD card",
  "diagram.addPart.wokwi-mpu6050": "MPU6050 Acceleromètre + Gyroscope",
  "diagram.addPart.wokwi-mux-2": "Logic: MUX",
  "diagram.addPart.wokwi-neopixel": "NeoPixel",
  "diagram.addPart.wokwi-neopixel-meter": "NeoPixel Meter",
  "diagram.addPart.wokwi-nlsf595": "NLSF595 SPI Driver LEd Tri-Color",
  "diagram.addPart.wokwi-ntc-temperature-sensor": "Capteur température analogique (NTC)",
  "diagram.addPart.wokwi-photoresistor-sensor": "Photoresistor (LDR) Sensor",
  "diagram.addPart.wokwi-pir-motion-sensor": "PIR détecteur de mouvement",
  "diagram.addPart.wokwi-potentiometer": "Potentiomètre",
  "diagram.addPart.wokwi-pushbutton": "Bouton poussoir",
  "diagram.addPart.wokwi-relay-module": "Module relais",
  "diagram.addPart.wokwi-resistor": "Résistance",
  "diagram.addPart.wokwi-rgb-led": "LED RGB",
  "diagram.addPart.wokwi-rotary-dialer": "Composeur rotatif",
  "diagram.addPart.wokwi-servo": "Servomoteur",
  "diagram.addPart.wokwi-slide-potentiometer": "Potentiometre linéaire",
  "diagram.addPart.wokwi-slide-switch": "Interrupteur à glissière",
  "diagram.addPart.wokwi-stepper-motor": "Moteur pas à pas bipolaire",
  "diagram.addPart.wokwi-tm1637-7segment": "Affichage 7 segments (TM1637)",
  "diagram.addPart.wokwi-tv": "PAL TV",
  "diagram.addPart.wokwi-vcc": "Symbole VCC"
}

**Comment by urish** [comment]
Thanks! French texts updated
