### ISSUE TITLE
中文翻译

### ISSUE THREAD

**Issue by golftir** [wokwi/wokwi-features#474]
{
  "userMenu.signIn": "登录",
  "userMenu.signUp": "注册",
  "userMenu.discord": "Discord",
  "userMenu.myProjects": "我的项目",
  "userMenu.theClub": "俱乐部",
  "userMenu.featureRoadmap": "特性路线图",
  "userMenu.language": "",
  "userMenu.logout": "注销登录",
  "project.header.save": "保存",
  "project.header.share": "分享",
  "project.header.likeProjectTooltip": "给这个项目点赞",
  "project.header.unlikeProjectTooltip": "给这个项目点踩",
  "project.menu.saveACopy": "另存为",
  "project.menu.lockProject": "锁定项目",
  "project.menu.unlistProject": "私有化此项目",
  "project.menu.downloadProjectZip": "下载项目文件",
  "project.error.saveFailed": "保存失败：项目被锁定！",
  "project.error.signInToLikeProject": "请登录后再为这个项目点赞",
  "project.shareDialog.title": "分享项目",
  "project.shareDialog.copyToClipboard": "复制到剪贴板",
  "project.shareDialog.pleaseSave": "请在分享此项目前先保存它：",
  "project.shareDialog.saveProject": "保存项目",
  "project.shareDialog.closeButton": "关闭",
  "simulator.main.restart": "重启仿真",
  "simulator.main.start": "启动仿真",
  "simulator.main.resume": "恢复",
  "simulator.main.pause": "暂停",
  "simulator.main.addNewPart": "增加一个新元件",
  "simulator.main.stopSimulation": "终止仿真",
  "simulator.main.zoomGridTooltip": "缩放、网格及更多",
  "simulator.buildFailedDialog.title": "构建失败！",
  "simulator.downloadingDataDialog.title": "正在下载SD卡数据",
  "editor.fileMenu.formatSuccessful": "",
  "editor.fileMenu.formatAlready": "",
  "editor.fileMenu.formatCode": "",
  "editor.fileMenu.rename": "重命名",
  "editor.fileMenu.delete": "删除",
  "editor.fileMenu.newFile": "新建文件",
  "editor.fileMenu.uploadFile": "上传文件",
  "editor.fileMenu.confirmDelete": "这将会移除{{filename}}，我要继续吗？",
  "editor.fileMenu.error.invalidFileName": "非法的文件名：字符{{char}}不允许使用。",
  "editor.fileMenu.error.invalidFileType": "非法的文件类型，支持的文件类型：{{types}}。",
  "editor.fileMenu.error.fileExists": "已经有同名文件存在",
  "editor.fileMenu.error.uploadFailed": "一些文件无法上传！",
  "editor.sdCard.uploadFiles": "上传文件",
  "editor.sdCard.uploadCompleteFolder": "上传整个文件夹",
  "editor.sdCard.deleteAllFiles": "删除所有文件",
  "editor.sdCard.noFilesYet": "尚无文件，请先上传一些文件。",
  "diagram.menu.undo": "",
  "diagram.menu.redo": "",
  "diagram.menu.fit": "自适应",
  "diagram.menu.zoomIn": "放大",
  "diagram.menu.zoomOut": "缩小",
  "diagram.menu.toggleGrid": "开关网格",
  "diagram.menu.fullScreen": "全屏",
  "diagram.menu.exitFullScreen": "退出全屏",
  "diagram.menu.help": "帮助",
  "diagram.addPart.board-esp-01": "ESP-01 WiFi模块",
  "diagram.addPart.board-ssd1306": "SSD1306 OLED显示器",
  "diagram.addPart.wokwi-74hc165": "74HC165输入移位寄存器(PISO)",
  "diagram.addPart.wokwi-74hc595": "74HC595 位移缓存器",
  "diagram.addPart.wokwi-7segment": "七段数码管",
  "diagram.addPart.wokwi-7segment-4digits": "4位七段数码管",
  "diagram.addPart.wokwi-a4988": "A4988步进电机驱动器",
  "diagram.addPart.wokwi-analog-joystick": "模拟摇杆",
  "diagram.addPart.wokwi-biaxial-stepper": "",
  "diagram.addPart.wokwi-breadboard": "",
  "diagram.addPart.wokwi-breadboard-half": "",
  "diagram.addPart.wokwi-breadboard-mini": "",
  "diagram.addPart.wokwi-buzzer": "蜂鸣器",
  "diagram.addPart.wokwi-dht22": "温湿度传感器DHT22",
  "diagram.addPart.wokwi-dip-switch-8": "8位拨码开关",
  "diagram.addPart.wokwi-ds1307": "DS1307 时钟芯片",
  "diagram.addPart.wokwi-flip-flop-d": "",
  "diagram.addPart.wokwi-gate-and-2": "",
  "diagram.addPart.wokwi-gate-nand-2": "",
  "diagram.addPart.wokwi-gate-not": "",
  "diagram.addPart.wokwi-gate-or-2": "",
  "diagram.addPart.wokwi-gate-xor-2": "",
  "diagram.addPart.wokwi-gnd": "",
  "diagram.addPart.wokwi-hc-sr04": "HC-SR04超声波传感器",
  "diagram.addPart.wokwi-hx711": "",
  "diagram.addPart.wokwi-hx711-5kg": "",
  "diagram.addPart.wokwi-ili9341": "ILI9341 2.8寸TFT-LCD显示屏",
  "diagram.addPart.wokwi-ir-receiver": "红外接收器",
  "diagram.addPart.wokwi-ir-remote": "红外遥控器",
  "diagram.addPart.wokwi-ks2e-m-dc5": "双刀双掷继电器",
  "diagram.addPart.wokwi-ky-040": "KY-040 旋转编码器",
  "diagram.addPart.wokwi-lcd1602": "LCD 16x2",
  "diagram.addPart.wokwi-lcd1602-i2c": "LCD 16x2 (I2C)",
  "diagram.addPart.wokwi-lcd2004": "LCD 20x4",
  "diagram.addPart.wokwi-lcd2004-i2c": "LCD 20x4 (I2C)",
  "diagram.addPart.wokwi-led": "LED灯",
  "diagram.addPart.wokwi-led-bar-graph": "LED条图显示器",
  "diagram.addPart.wokwi-led-ring": "NeoPixel环",
  "diagram.addPart.wokwi-logic-analyzer": "逻辑分析仪（8通道）",
  "diagram.addPart.wokwi-max7219-matrix": "LED点阵屏 (MAX7219)",
  "diagram.addPart.wokwi-membrane-keypad": "键盘",
  "diagram.addPart.wokwi-microsd-card": "microSD卡",
  "diagram.addPart.wokwi-mpu6050": "MPU6050 六轴传感器（加速度计+陀螺仪）",
  "diagram.addPart.wokwi-mux-2": "",
  "diagram.addPart.wokwi-neopixel": "NeoPixel",
  "diagram.addPart.wokwi-neopixel-meter": "NeoPixel表",
  "diagram.addPart.wokwi-nlsf595": "NLSF595 SPI三色LED驱动器",
  "diagram.addPart.wokwi-ntc-temperature-sensor": "模拟温度传感器 (NTC)",
  "diagram.addPart.wokwi-photoresistor-sensor": "光敏电阻（LDR）传感器",
  "diagram.addPart.wokwi-pir-motion-sensor": "PIR运动传感器",
  "diagram.addPart.wokwi-potentiometer": "电位器",
  "diagram.addPart.wokwi-pushbutton": "按钮",
  "diagram.addPart.wokwi-relay-module": "",
  "diagram.addPart.wokwi-resistor": "电阻",
  "diagram.addPart.wokwi-rgb-led": "三色灯",
  "diagram.addPart.wokwi-rotary-dialer": "旋转拨号器",
  "diagram.addPart.wokwi-servo": "舵机",
  "diagram.addPart.wokwi-slide-potentiometer": "滑动电位器",
  "diagram.addPart.wokwi-slide-switch": "开关",
  "diagram.addPart.wokwi-stepper-motor": "双极步进电机",
  "diagram.addPart.wokwi-tm1637-7segment": "",
  "diagram.addPart.wokwi-tv": "PAL制式电视",
  "diagram.addPart.wokwi-vcc": ""
}

**Comment by urish** [comment]
Thanks! I checked the list of translations you provided, and they seem identical to the [translations we already have](https://wokwi.com/api/i18n/zh.json). Did you make any changes?
