### ISSUE TITLE
Inlined svg definitions collisions

### ISSUE THREAD

**Issue by guillaume-dorczynski** [wokwi/wokwi-features#476]
Hello !

**Describe the bug**
There is a problem with inlined svg, which causes definitions to collide.

**To Reproduce**
In the editor, add a half-size breadboard, then a full-size breadboard. The bottom row of numbers on the full-size breadboard will stop at 30, because it uses `#numbers` which was first defined in the half-size breadboard's svg.

**Expected behavior**
There should be a way to encapsulate inlined svg so they `use` local definitions only. Or do not use inlined svg.

**Environment**
 - OS: Windows 11
 - Browser: Chrome, Edge, Firefox
 - Version: up to date

**Additional context**
This problem may not be limited to breadboards, I don't know if editor uses others inlined svg

**Comment by AriellaE** [comment]
Thank you @guillaume-dorczynski!

Fixed it, should be fine now.

Have a great day!
