### ISSUE TITLE
Arduino Nano pins interferes on breadboard

### ISSUE THREAD

**Issue by guillaume-dorczynski** [wokwi/wokwi-features#477]
**Describe the bug**
When an Arduino Nano is placed on a breadboard, pins GND.3, 11.2 and 5V.2, on the ICSP header, interferes with pin 0 and Vin, so they are connected to the same row on the breadboard.

**Expected behavior**
Ideally, the ICSP header should not auto-connect to the breadboard.

**Possible solutions**
- In the Arduino Nano element, you could maybe add a flag to these pins so a breadboard will check this flag and not auto-connect those pins.
- Modify the Arduino Nano graphic to move the ICSP header 0.1in to the right so it is not aligned with pin 0 and Vin.

**Comment by AriellaE** [comment]
Hello again @guillaume-dorczynski,
Fixed it. 
Thank you!

**Comment by guillaume-dorczynski** [comment]
Thanks :)
