### ISSUE TITLE
Searching for new parts only works in English

### ISSUE THREAD

**Issue by urish** [wokwi/wokwi-features#479]
When adding a new part (by pressing the purple "+" sign), there's a search box at the top. Any text you type in the search box will filter the list of parts. However, when switching to a different language, the search box still tries to match the English text.

For example, if you [switch to Spanish](https://wokwi.com/projects/new?lang=es-ES) and type "Pulsador", you will get an empty list, even through there's a "Pulsador" in the part list. Ideally, searching would look for matches both in English and the selected language.

**Comment by AriellaE** [comment]
Bug fixed.👍
