### ISSUE TITLE
optional feature request: blur the rest of the area to highlight the LEDs

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#48]
With blur:
![image](https://user-images.githubusercontent.com/68117142/104198794-a9537a00-544c-11eb-8e38-a4e417187b67.png)

Without blur:
![image](https://user-images.githubusercontent.com/68117142/104199076-fdf6f500-544c-11eb-9dab-30a460d1ca18.png)

**Comment by urish** [comment]
How about hiding the Arduino?  you can set `"hide": true` in diagram.json

**Comment by Puneethkumarsn** [comment]
This issue can be again reopened if other requests come. I vote to close this issue
