### ISSUE TITLE
Pico on breadboard width mismatch and not connecting to both sides 

### ISSUE THREAD

**Issue by tproffen** [wokwi/wokwi-features#481]
Love the new breadboard feature. It works great, except when I added the Raspberry Pico (CircuitPython), the distance of the pins does not match the breadboard and only one side auto connects to the breadboard pins and wires need to be run to the Pico pins on the not connected side (see https://wokwi.com/projects/350444482715451988).

**Comment by AriellaE** [comment]
Hello @tproffen, 

I'm very happy to hear that you love the breadboard!
I fixed the Raspberry Pico and it should be fine now. 

Thank you for helping us make Wokwi better.

**Comment by tproffen** [comment]
@AriellaE Thank you so much - this must have been the quickest bug fix I have ever seen 🥰 There is one more thing 😨 It looks like the Pico being one row to wide as you can see on the screenshot vs. picture from the actual device. So you loose one row on one side currently. 

<img width="301" alt="sim" src="https://user-images.githubusercontent.com/2531863/206524229-577ba535-a239-4abd-a52f-0d9c7e58b950.png">

![real](https://user-images.githubusercontent.com/2531863/206524611-5d1e7f95-6836-4e91-b51f-7874c8d032da.jpg)

**Comment by AriellaE** [comment]
Hello again @tproffen,

Fixed it:
![Screen Shot 2022-12-12 at 11 17 39](https://user-images.githubusercontent.com/35613240/207007687-f914035b-cc47-4468-b199-0d3a582e94f4.png)

Thank you for the complement and enjoy using Wokwi.

Have a great day, 
Ariella.
