### ISSUE TITLE
Wokwi Simulator vscode extension does not run more than once per invocation

### ISSUE THREAD

**Issue by bonnyr** [wokwi/wokwi-features#483]
**Describe the bug**
The extension does not restart properly if Stop and then Start are selected.

**To Reproduce**
Since this is a problem with the vscode extension, the link here is to a github repo with a custom chip: https://github.com/bonnyr/wokwi-ds1820-custom-chip

1. Clone the repo
2. Run in dev container
3. Start Wokwi Simulation from the command palette and let it run for a bit
4. Stop the simulation but do not close the window
5. Start the simulation again - custom chip initialisation code is not called

**Expected behavior**
Every Stop/Restart should behave like a completely new invocation

**Environment (please complete the following information):**
 - OS: Windows
 - Browser VSCode
 - Version 
   - Last updated 09/12/2022, 15:55:40
   - Identifier wokwi.wokwi-vscode

**Comment by urish** [comment]
Thanks for reporting, fixed!
