### ISSUE TITLE
Hungarian translation update, 2022-12-17

### ISSUE THREAD

**Issue by misibacsi** [wokwi/wokwi-features#485]
Hello

I just updated the previous Hungarian translation, please use it.

Some remarks: 

1. When you run your software, on the right side there is a "Simulation" text. 
This text is not in the English text file, so it cannot be translated.
(On the big green arrow button it is translated)

2. On the upper right corner, beside your avatar, there is a "Docs" text, which is also cannot be translated.

[wokwi-HU-2022-12-17.zip](https://github.com/wokwi/wokwi-features/files/10250971/wokwi-HU-2022-12-17.zip)

**Comment by urish** [comment]
Thanks! Translations updated, and also added the "Simulation" text to the translation list. The "Docs" will probably be added in the future.
