### ISSUE TITLE
Pagination fails for some projects and makers' pages

### ISSUE THREAD

**Issue by sutaburosu** [wokwi/wokwi-features#487]
When viewing [my projects](https://wokwi.com/dashboard/projects) I can see the first page fine, but scrolling down never loads subsequent pages.

The responses take several seconds and the result is "500: Internal server error".
![image](https://user-images.githubusercontent.com/20606/208422453-bf01e8eb-45ec-47fa-836f-a3e8d9e8308d.png)

This seems to affect some makers' pages too. [Your own maker page](https://wokwi.com/makers/urish) loads all pages fine. [My maker page](https://wokwi.com/makers/sutaburosu) fails to load past the first page.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser:  Chrome v108.0.5359.125, Firefox v108.0.1

PS Apologies for my extended absence from the Discord. I hope to have more free time next year.

**Comment by urish** [comment]
Steve! 

Missed you so much, great to hear again from you :)

Looking into this right way

**Comment by urish** [comment]
Fix is up! Mind trying now and reporting?

**Comment by sutaburosu** [comment]
That works perfectly now. Thanks, Uri.
