### ISSUE TITLE
Neopixel Ring does not work using Pico Pi and Micropython

### ISSUE THREAD

**Issue by martinkoehler** [wokwi/wokwi-features#493]
**Describe the bug**
Using the NeoPixel Ring in a simulation with a Pico Pi and Micropython does not work. The leds stay white.

**To Reproduce**
See https://wokwi.com/projects/352320936190737409

**Expected behavior**
Should behave like https://wokwi.com/arduino/projects/305569065545499202
Same python code, but other board used

**Environment (please complete the following information):**
 - Browser chrome
 - Version 108.0.5359.124

**Comment by urish** [comment]
Thanks for reporting!

Upon initial investigation, connecting the [logic analyzer](https://docs.wokwi.com/guides/logic-analyzer) to the pin, it seems like the code is sending a valid WS2812 signal, even though it's all black pixels:

![image](https://user-images.githubusercontent.com/892318/209868271-2205c5f4-a33e-452f-bb67-c3b9f055d10e.png)

**Comment by martinkoehler** [comment]
Note: If you change "wokwi-pi-pico" to "wokwi-esp32-devkit-v1" in diagram.json, and connect DIN to D15, it works as expected.
... but of course then the board is not a pico pi anymore :-(

**Comment by martinkoehler** [comment]
i also tried to use the neopixel library from micropython (https://raw.githubusercontent.com/micropython/micropython-lib/master/micropython/drivers/led/neopixel/neopixel.py) directly (as additional file, but named as `np.py` to avoid name collisions and then `from np import NeoPixel`). Unfortunately with the same result.

**Comment by martinkoehler** [comment]
Indeed the Pin in the pico pi case seems to emit black pixels.
I just created two even simpler versions, where a single NeoPixel is attached to `PIN(15)` and which clearly shows the problem:
The python code is:
```
from machine import Pin
from neopixel import NeoPixel
np=NeoPixel(Pin(15),1)
np.fill((0xfa,0xfa,0xfa))
np.write()
```

https://wokwi.com/projects/352400356608819201 for the ESP32 Version and a single NeoPixel
This works and the NeoPixel is white after running the Simulation
Same code and layout for the Pico Pi with Micropython
https://wokwi.com/projects/352400550196923393
Here the NeoPixel remains black.

In the first case the logic analyzer shows
![image](https://user-images.githubusercontent.com/9458435/209987275-c921a51f-6c2a-4019-92b8-6e902b50aad6.png)
(correct values (0xfa,0xfa,0xfa), which gives a white pixel)
while in the Pico Pi case one sees
![image](https://user-images.githubusercontent.com/9458435/209987157-681bfd98-2a8d-40a0-bbd5-92ce68db8712.png)
(wrong values (0,0,0), which gives a black pixel)

Hope this helps for the debugging?!
Thanks for you efforts!

**Comment by urish** [comment]
Moving the discussion to #551
