### ISSUE TITLE
board-ili9341-cap-touch not listed in the new part box

### ISSUE THREAD

**Issue by usernameeReal** [wokwi/wokwi-features#494]
**Describe the bug**
The `board-ili9341-cap-touch` component is not listed in the new part box

**To Reproduce**
Search for ili9341 in the new part box.

**Expected behavior**
The component shows up.

**Environment (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 108

**Additional context**
`board-ili9341-cap-touch` exists and seems to have no issues

**Comment by AriellaE** [comment]
Hello,
I added the board-ili9341-cap-touch to the part box.
Thank you and have a great day,
Ariella.
