### ISSUE TITLE
possibility to edit the project - `Later`

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#5]
I came up with the need to edit the project I had already shared with many. A provision for the `original author` to update the project is preferred. Seems like logging-in is the only option I believe

**Comment by urish** [comment]
Agreed! For now, as long as you use the same browser, you should have access to edit the project. You can find a list of all the projects you have access edit to on https://wokwi.com/arduino/projects

**Comment by Puneethkumarsn** [comment]
This works for me for now

**Comment by urish** [comment]
There's now also an option to sign in, using either a Google or a GitHub account:

![image](https://user-images.githubusercontent.com/892318/102728338-fc497e00-4333-11eb-9c40-8cedba4cc054.png)
