### ISSUE TITLE
Project sometimes shows old version after saving

### ISSUE THREAD

**Issue by urish** [wokwi/wokwi-features#50]
To reproduce:

1. Save a new project
2. Make some changes, save it again
3. Refresh the browser. You'll see that you get the older version of the project, without the changes.

Refreshing 1-2 more times usually fixes this issue, but it can still be frustrating for a user who doesn't realize what happened.

**Comment by M-square** [comment]
Between point 2 and 3 you can even restart the browser (chrome) and it still reloads(?) the old copy

**Comment by urish** [comment]
I believe this is fixed now.
