### ISSUE TITLE
Potential bug: ATTiny85 interrupt INT0 always as "level trigger"

### ISSUE THREAD

**Issue by makkiato83** [wokwi/wokwi-features#500]
**Describe the bug**
I suspect the current ATTiny85 simulator does not correctly handle the bits `ISC01` and `ISC00` of the register `MCUCR`, which are used to determine the way the external interrupt on INT0 is triggered.

The problem seems to be that the simulator always does a level trigger (which should be the case only when both ISC01=0 and ISC00=0).

**To Reproduce**

https://wokwi.com/projects/353005290703259649

Push the button a few times and see what happens in the Logic Analyser. It shows that PB0 was being toggled all the time while the pushbutton was down.

This would be the correct behaviour with level trigger but not with RAISING EDGE (ISC01=1 and ISC00=1).

**Expected behavior**

On a physical Attiny85 the same code triggers on "RAISING EDGE" as expected.

**Comment by urish** [comment]
Fixed! Thanks for reporting :)
