### ISSUE TITLE
Filter "logic" is not working anymore

### ISSUE THREAD

**Issue by shaos** [wokwi/wokwi-features#504]
**Describe the bug**
After removing prefix "Logic :" for basic logic components filter "logic" stopped working

**To Reproduce**
Enter "logic" in the filter text entry 

**Expected behavior**
Previously it showed basic logic components as NOT, AND, etc

**Environment (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 91.11.0esr (64-bit)

**Additional context**
Just add section name to item names before executing the search - it will fix the issue

**Comment by AriellaE** [comment]
Hello @shaos 

Thank you for bringing this to our attention.
Searching "Logic" is now working!

Have a great day,
Ariella
