### ISSUE TITLE
Add a keyboard shortcut for the "View Compiled Assembly Listing"

### ISSUE THREAD

**Issue by makkiato83** [wokwi/wokwi-features#505]
At the moment there is no shortcut for this very nice feature. 

Thanks

**Comment by urish** [comment]
Can you proposed a key shortcut? Please check if doesn't already exist / conflict with the browser defined keys (Ctrl+T for instance)

**Comment by makkiato83** [comment]
I think ⌘§ could be an option.

Granted it is not very 'mnemonic'. On the other hand it is very fast to type and it is currently unused ( I think ).

Regarding the 'mnemonic', § is like the "S" in aSm... :-P

**Comment by urish** [comment]
Hmm, I'm not sure which key is §? It probably only appears on some keyboard layouts?

**Comment by makkiato83** [comment]
Uhm, sorry I should have checked. 
In my keyboard (Macbook air M2, international keyboard) it is the button on the left of "1", just below "ESC".

**Comment by urish** [comment]
Oh, well, on my keyboard that is where the ` (backtick) and ~ button is.

We don't have an § key here. I guess we could go for Cmd(or Ctrl) + backtick then?

**Comment by makkiato83** [comment]
Sure! That would work as well!
Thanks

**Comment by urish** [comment]
Done!
