### ISSUE TITLE
Share a project in read-only mode

### ISSUE THREAD

**Issue by TimothyFran** [wokwi/wokwi-features#506]
I have the pro version of wokwi, and sometimes I use it to demonstrate something to my customers.
It would be great to have a function to share a project in a "read-only" mode.
From the shared link, you can interact with the components, but you cannot see the source code.
Moreover, if the viewer moves the components on the layout, changes are not saved and I can continue working on the project as I left it.

**Comment by urish** [comment]
Thanks for the feedback Timothy!

There's actually a way to achieve both things:
1. When sharing a link, if other users make modifications to your project and save it, it won't modify the original project (which belongs to you), rather make a copy in their account and save the modifications in their copy. Is this different from how you thought the Save function works?

3. You can add `?view=diagram` at the end of the project link. This will hide the code editor. I'm not sure if this fits your need as the user can still manually edit the URL (removing ?view=diagram at the end) and retrieve the code, but at the basic level, it doesn't show the code. Here's an example: https://wokwi.com/projects/328451800839488084?view=diagram.

**Comment by TimothyFran** [comment]
Thanks for your reply.
This solves all my problems

**Comment by urish** [comment]
Amazing!
