### ISSUE TITLE
Please add rotary encoder with button

### ISSUE THREAD

**Issue by beliboba** [wokwi/wokwi-features#508]
**Is your feature request related to a problem? Please describe.**
Rotary encoder with click function.
Just like this
![image](https://user-images.githubusercontent.com/73661136/213931340-ee6c817f-cc71-4432-90ae-c605fe1733e8.png)

**Comment by urish** [comment]
We already have this rotary encoder. Here's the documentation: https://docs.wokwi.com/parts/wokwi-ky-040
and usage example: https://wokwi.com/projects/304184909747978816
