### ISSUE TITLE
IDE / VS Code Extension / Publish as vsix or on open-vsx.org

### ISSUE THREAD

**Issue by Semnodime** [wokwi/wokwi-features#515]
As mentioned by @OliverKeeve in this [readme](https://github.com/OliverKeefe/vscode-extensions-in-vscodium#readme), the `codium` fork (vs code without telemetry) uses a different extensions store, namely [open-vsx.org](https://open-vsx.org/).

Currently, wokwi is not available there and therefore won't be listed within the available extensions within `codium`.
The github search does not list a respective download link anywhere, so I kindly want to promote providing one.

Related to #414.

**Comment by urish** [comment]
Thanks! So your use case is using the extension with `codium`, right?

**Comment by Semnodime** [comment]
> Thanks! So your use case is using the extension with `codium`, right?

Correct.

**Comment by Semnodime** [comment]
**Temporary workaround for `codium`:**
I circumvented the (primarily legal) trouble of switching `codium` to the microsoft vscode extension store
by using vscode to install the extention, then moving the extention data (`.vsix`, basically a zip) into the local `codium` dir afterwards.

**Comment by Semnodime** [comment]
Stumbled upon https://pre-release.private.wokwi.com/wokwi-vscode-latest.vsix, is this still maintained?

**Comment by urish** [comment]
nope, it was maintained during the private alpha period. That version is now a month+ old and does not receive updates.

**Comment by urish** [comment]
I looked into this today - looks like Open-vsx.org may be shutting down in a few weeks: https://blogs.eclipse.org/post/john-kellerman/help-us-sustain-open-vsxorg

**Comment by dzid26** [comment]
They haven't https://www.globenewswire.com/news-release/2023/06/27/2695137/0/en/The-Open-VSX-Registry-a-Vendor-Neutral-Community-Supported-Alternative-to-the-Visual-Studio-Marketplace-Gets-its-Own-Working-Group-at-the-Eclipse-Foundation.html

**Comment by urish** [comment]
Good news - then, I'll look into this again in a couple of weeks

**Comment by urish** [comment]
https://open-vsx.org/extension/Wokwi/wokwi-vscode

**Comment by urish** [comment]
Would love to see some users 5-starring the project :-)

https://open-vsx.org/extension/Wokwi/wokwi-vscode
