### ISSUE TITLE
Display and allow changing whether project is unlisted or public in "Your Projects" view

### ISSUE THREAD

**Issue by sbdswr** [wokwi/wokwi-features#518]
I would like to at least see in https://wokwi.com/dashboard/projects whether the project is unlisted or public. E.g. with a padlock vs the globe icons next to project name.

Additionally an option to change this setting in the kebab menu of each project would be nice.

**Comment by AriellaE** [comment]
Hello @sbdswr 
From now you can see for each project in your project list if it is unlisted or public and change its status if you are a Club member.
![Screen Shot 2023-03-28 at 15 20 06](https://user-images.githubusercontent.com/35613240/228237029-a14d52c6-ecfa-4be9-a36f-9bddf5a3bd1d.png)

Have a great day!
