### ISSUE TITLE
RTC DS1307 error

### ISSUE THREAD

**Issue by FernandoGarcia** [wokwi/wokwi-features#521]
Hi!

There's some bug in RTC DS1307. Setting the date to  31/5/2023 the serial monitor is showing 3/5/2023.

I have tested the same code in real hardware and it doesn't happens.

![Captura de tela de 2023-02-15 10 01 58](https://user-images.githubusercontent.com/2778501/219041323-c5c54cee-9b24-485c-90a6-e56fbdd6a9ed.png)

![Captura de tela de 2023-02-15 09 55 17](https://user-images.githubusercontent.com/2778501/219041367-e46d7de6-5396-4018-818c-eb698171dd9f.png)

The link for simulation: https://wokwi.com/projects/356669043513165825

Best regards.

**Comment by urish** [comment]
This issue happens when the current month setting in the DS1307 has less days than the requested day in the new date. For instance, if the current month is February, setting the date to anything beyond 28 may cause this issue.

**Comment by urish** [comment]
Fix is up! Thanks again for the super detailed report

**Comment by FernandoGarcia** [comment]
It's fine now, thanks!
