### ISSUE TITLE
Reversed RX/TX pins on Arduino Nano

### ISSUE THREAD

**Issue by umsenn** [wokwi/wokwi-features#528]
**Describe the bug**
On a real Arduino Nano pin 1 is TX and pin 2 is RX. In WOKWI however, when I send a message using  Serial.println, it is sent using pin 2.

**To Reproduce**
- Open LogicAnalyzerDemonstration.ino using https://wokwi.com/projects/348006603081908820. This example uses an Arduino UNO and works as expected.
- Now change the type in diagram.json from "wokwi-arduino-uno" to "wokwi-arduino-nano". You will realize, that Serial.println sends using pin 2, which is RX on an Arduino NANO.  

**Expected behavior**
Serial.println should send using pin 1.

**Environment (please complete the following information):**
 - OS: Windows
 - Browser safari

**Additional context**

**Comment by urish** [comment]
Thanks for the detailed report, fixed!
