### ISSUE TITLE
Want ADC in ESP32C3

### ISSUE THREAD

**Issue by Qinka** [wokwi/wokwi-features#530]
I hope we can use ADC in esp32-c3

**Comment by urish** [comment]
It's already there: https://wokwi.com/projects/343856707806429779

You can see the implementation status of all the peripherals across different ESP32 chips in the docs: https://docs.wokwi.com/guides/esp32#simulation-features

**Comment by Qinka** [comment]
@urish well, the Chinese version document is out of date.

**Comment by urish** [comment]
Yeah, the person who voluntarily worked on it stopped updating it. We'll probably remove it until someone starts updating it again.
