### ISSUE TITLE
When you have multiple files on SD, it doesn't delete them all in one click

### ISSUE THREAD

**Issue by ilja89** [wokwi/wokwi-features#531]
**Describe the bug**
I have multiple files on sd, in different folders. When I click on delete files button, I have to click few times to delete them all.

**To Reproduce**
1. Upload few files, for me it minimally worked with 3
2. Try to delete all

**Expected behavior**
All files should be deleted

**Environment (please complete the following information):**
 - Windows
 - Chrome

**Comment by urish** [comment]
Thanks for reporting! Can you please share a link to a project where this happens?

**Comment by ilja89** [comment]
https://wokwi.com/projects/356860098426595329

**Comment by urish** [comment]
Thanks, issue fixed!
