### ISSUE TITLE
Lock project function doesn't prevent deletion

### ISSUE THREAD

**Issue by FernandoGarcia** [wokwi/wokwi-features#535]
https://user-images.githubusercontent.com/2778501/220511895-a40326af-af45-46c7-baa9-7e15f6b834f4.mp4

**Comment by urish** [comment]
Thanks for reporting, fixed!

**Comment by FernandoGarcia** [comment]
Hi!

Thanks!

Could you add option to lock/unlock the project in dashboard without open?

Best regards.

**Comment by urish** [comment]
We might add it in the future - right now, we have [other priorities](https://wokwi.com/features)
