### ISSUE TITLE
Add Teensy 4.1 to the microcontroller list

### ISSUE THREAD

**Issue by falkenx** [wokwi/wokwi-features#538]
Teensy 4.1 is a very powerful small SoC that is compatible with the Arduino framework.  It would be a welcome addition to the list of microcontrollers in my opinion.

**Comment by urish** [comment]
Thanks for the request! 

I looked into this, and unfortunately, simulating the Teensy 4.1 requires an enormous effort, so unless NXP/PJRC help funding the development, it's not likely to happen.

**Comment by leftCoast** [comment]
I just left a comment on the PJRC forum about this. (Because I'd LOVE to have a Teensy emulated) Maybe they'll step up? Maybe the'll just ignore me. We'll see.

[https://forum.pjrc.com/threads/72276-Teensy-on-Wokwi](url)

-jim lee

**Comment by urish** [comment]
Thx!
