### ISSUE TITLE
Need more IC Modules in simulation panel. 

### ISSUE THREAD

**Issue by ak4shp** [wokwi/wokwi-features#541]
Please add some more ICs and Module in the simulation panel. 
A feature to import some kind of IC module externally will be a great addition.

**Comment by ak4shp** [comment]
A few suggestions ->
1. RC522 RFID Reader
2. ULN2003 Stepper Motor Driver ( Yes there is already A4988 but this will be good add)

**Comment by urish** [comment]
Thanks for the suggestions!

1. The [RC522 RFID](https://wokwi.com/features#feature-1242782423) is already open for voting (#359)
2. Feel free to open a separate issue for that specific driver (and we'll open it for voting).

Note that it's also possible to create your own ICs by writing a simulation model in C. See the Custom Chips API docs for examples: https://docs.wokwi.com/chips-api/getting-started
