### ISSUE TITLE
Add web viewer for ESP32 

### ISSUE THREAD

**Issue by zakarialaoui10** [wokwi/wokwi-features#543]
**Is your feature request related to a problem? Please describe.**
Esp32 Esp8266 and many other boards need a web view to be simulated

**Describe the solution you'd like**
when the the IP address will be ready (in both AP or STA mode) we have to use a web browser

**Comment by urish** [comment]
ESP32 is already simulated and well supported: https://docs.wokwi.com/guides/esp32

ESP8266 is tracked in #314, but it's not very likely, as more and more people are replacing it with newer chips (ESP32-C3 for example).

AP mode is tracked in #304. 

You can see the list of proposed features and vote for them here: https://wokwi.com/features.
