### ISSUE TITLE
Use more visible color for line 3 on serialMonitor::display=plotter (maybe #800080 )

### ISSUE THREAD

**Issue by drf5n** [wokwi/wokwi-features#544]
**Is your feature request related to a problem? Please describe.**

I'm Frustrated with color #3 in the wokwi serialMonitor: {display=plotter} palette.  It is nearly unreadable on a dark background.

Per https://docs.wokwi.com/guides/serial-monitor with this in diagram.json:

```
  "serialMonitor": { "display": "plotter", "newline": "lf" },
```

I see this in https://wokwi.com/projects/358190033668210689

<img width="262" alt="image" src="https://user-images.githubusercontent.com/2236516/223744521-f28dde8a-d203-4915-9007-9dc50c020c11.png">

The trace is visible, but the legend is unreadable.

Another example from https://wokwi.com/projects/358643496953546753

<img width="386" alt="image" src="https://user-images.githubusercontent.com/2236516/223752536-8109430e-d4d0-492a-9ad5-9c07cb59d958.png">

**Describe the solution you'd like**
I'd like the magenta trace and legend color to be more visible, perhaps instead of #400040 double it to a lighter shade like #800080 ?

<img width="861" alt="image" src="https://user-images.githubusercontent.com/2236516/223754323-11bd03de-e007-4801-903c-cd2dbbb13afa.png">

**Comment by drf5n** [comment]
Code from the above https://wokwi.com/projects/358643496953546753

```
void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
}

void loop() {
  // put your main code here, to run repeatedly:
  const double n = 8;
  for (int i = 0; i < n; i++) {
    Serial.print(i);
    Serial.print(':');
    Serial.print(sin((millis() / 3600.0/2 + i / n/2) * 2 * PI));
    Serial.print(' ');
  }
  Serial.println();

  delay(100);
}
```

**Comment by urish** [comment]
Thanks for the suggestion, done!

**Comment by drf5n** [comment]
<img width="237" alt="image" src="https://user-images.githubusercontent.com/2236516/223763640-f75795e6-abd7-4c15-bc08-0bff18f8c30f.png">


Cool!   Just what I imagined.  

Thank you.
