### ISSUE TITLE
Add GPIO Expander such as PCF8574

### ISSUE THREAD

**Issue by sephalias** [wokwi/wokwi-features#546]
GPIO Expanders are useful for MCUs with limited pins.

**Comment by urish** [comment]
Hi! This is already requested in #385, and you can see the [vote status](https://wokwi.com/features#feature-1311403347).

However, someone made a custom chip that implements the PCF8574 (not sure if a full implementation, but definitely a useful one): https://wokwi.com/projects/350228699564474964
