### ISSUE TITLE
Does not work on Yandex !

### ISSUE THREAD

**Issue by NarzullayevMe** [wokwi/wokwi-features#547]
**Describe the bug**
This site does not work on Yandex

**To Reproduce**
Steps to reproduce the behavior, including link to a simulation project where we can see the problem.
https://wokwi.com/projects/new/arduino-uno

**Expected behavior**
![image](https://user-images.githubusercontent.com/95655675/225423949-dc685855-4312-4afa-bfca-e0538764a579.png)

**Environment (please complete the following information):**
OS: Windows 11. 

![image](https://user-images.githubusercontent.com/95655675/225424230-37b71763-797a-405e-b0d0-bdb8d9bde13b.png)

**Yandex Version: 23.1.5.708 (64-bit) (latest)**

....however, it works fine in chrome....
![image](https://user-images.githubusercontent.com/95655675/225426616-960c0d91-3b6b-4f97-b05e-52b36c121ef5.png)

**Additional context**

**Comment by urish** [comment]
Checked on Yandex version 23.1.5.708 (64-bit), Windows 11 - works fine.

![image](https://user-images.githubusercontent.com/892318/226610710-e9f1ba15-33d3-47d3-9eb9-b6db45d20d68.png)

Closing as this issue does not easily reproduce and there's a workaround (using Chrome).
