### ISSUE TITLE
Compilation error when including dma.h

### ISSUE THREAD

**Issue by SukuWc** [wokwi/wokwi-features#548]
I tried to prototype some dma based code but could not get the compiler to build any dma based code... Is PR2040 dm supported in the WokWi simulator?

/home/wokwi/project/src/main.c:3:10: fatal error: hardware/dma.h: No such file or directory
    3 | #include "hardware/dma.h"

**Comment by urish** [comment]
Added the dma library to the build server.

If you are still getting this error, please change the code you're trying to compile (e.g. add a comment), and it should recompile the code and find the library.
