### ISSUE TITLE
New Project

### ISSUE THREAD

**Issue by leftCoast** [wokwi/wokwi-features#552]
**Just a request.**

**What'd like**
On the menu, next to the save button. I would really like a "New" selection.  Click it and I get a choice of processor then a a new wokwi project pops up. Could be overlaying what I was working on, hopefully saved, or maybe a new tab. Not given that bit a lot of thought. But I'm tired of going out to my project list to get a fresh one.

**Comment by urish** [comment]
Thanks Jim! Opened this for [voting](https://wokwi.com/features?sort=newest#feature-1631149982)

**Comment by djedu28** [comment]
Hello! An alternative you could try is adding the new project page to your browser bookmarks. This will allow you to quickly access it with just one click, without having to navigate through other menus.

**Comment by avipars** [comment]
Would be cool if you @urish  could buy the wowki.new domain or something similar with the same TLD that then opens up with a new project

**Comment by urish** [comment]
Well, if someone has $1,200 to spare on wokwi.new I'd be happy to register it
