### ISSUE TITLE
The current favicon doesn't work in darkthemed systems/browsers

### ISSUE THREAD

**Issue by sajjad** [wokwi/wokwi-features#554]
**Is your feature request related to a problem? Please describe.**
In a dark themed browser, the Wokwi favicon isn't visible in the browser tabs. Example screenshot:
![image](https://user-images.githubusercontent.com/3789566/227744334-a380a4d2-b268-471a-9e39-fa5332abf085.png)

**Describe the solution you'd like**
I would like a favicon which works for both dark and light themes. For instance, adding a white circle/square on top of the 'W' symbol will fix this issue (like github.com)

**Comment by urish** [comment]
Thanks for reporting! How about now?

**Comment by sajjad** [comment]
That's perfect, thank you 👍
