### ISSUE TITLE
MicroPython program runs twice when it should run once

### ISSUE THREAD

**Issue by Lucvolders** [wokwi/wokwi-features#555]
**Describe the bug**
A MicroPython program with no continuous loop should run once when started and then stop. In real life situation it does. On Wokwi it runs twice.

**To Reproduce**
Here is the link to the project on Wokwi:
https://wokwi.com/projects/360215418797037569

**Expected behavior**
As stated: it is expected to run once and it runs twice

**Environment (please complete the following information):**
Computer: PC with windows 10
Browser tested on Firefox and on Chrome

**Comment by urish** [comment]
Thanks for reporting, fixed!

**Comment by Lucvolders** [comment]
Thanks, tested works  !!!
