### ISSUE TITLE
Elf files with no file extensions get's silently eaten with no user Error Feedback

### ISSUE THREAD

**Issue by Vollbrecht** [wokwi/wokwi-features#556]
**Describe the bug**
Uploading an elf file for simulation in an project that does not have an elf extension doesn't through an error. It just do nothing.

**To Reproduce**
 To specify it was an rust esp-idf std file build for esp32c3. on default the file has no file extension.
[wokwi-crash.zip](https://github.com/wokwi/wokwi-features/files/11109411/wokwi-crash.zip)

The zip contains the same file two times. First without file extension, than with file extension. Simulation only works with file with file extension,
**Expected behavior**
Return  some sort of error to the user if the uploaded file is not working

**Environment (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 111

**Comment by urish** [comment]
Thanks for reporting, fix is up!
