### ISSUE TITLE
rust std app panic in simulator if debug build is used 

### ISSUE THREAD

**Issue by Vollbrecht** [wokwi/wokwi-features#557]
**Describe the bug**
A call to esp-idf-svc::systime::EspSystemTime panics inside the wokwi simulator when build as an debug target on esp32c3.
Noticeable here is the elf runs fine on real hardware! It also runs fine in the simulator when build with --release.
**To Reproduce**
The following repo contains a minimal 50 lines example to reproduce. It also has an debug and release .elf file attached in the root folder. https://github.com/Vollbrecht/wokwi-debug-build-panic

**Expected behavior**
Do the same as in real hardware and dont panic

**Environment (please complete the following information):**
 - OS: linux debian 11

**Comment by Vollbrecht** [comment]
update info: 
![Screenshot from 2023-03-30 14-30-23](https://user-images.githubusercontent.com/12041081/228838472-138bceea-a875-43c4-8013-79ad83449f19.png)
this negativ value in esp-idfv4.4.4/components/esp_timer/src/system_time.c/esp_system_get_time is problematic

**Comment by urish** [comment]
Tracked this down to a missing RTC TIMER 0 implementation.

**Comment by urish** [comment]
Fix is up - can you try now and report if there are still issues?

**Comment by Vollbrecht** [comment]
It's fixed now. :tada:  Was fun tracking it down with you. Thanks for the fix!
