### ISSUE TITLE
Rust Esp32s3 board is missing 

### ISSUE THREAD

**Issue by Vollbrecht** [wokwi/wokwi-features#559]
**Describe the bug**
Creating a new project in https://wokwi.com/dashboard/projects misses the Esp32s3 option for Rust (std)

**To Reproduce**
Create new project here -> https://wokwi.com/dashboard/projects

**Expected behavior**
Because it is an option for Rust no_std and for arduino i would assume that Esp32s3 should also be there for Rust (std)

**Environment (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 111

**Comment by Vollbrecht** [comment]
From outside its hard to tell if this is a bug or a missing feature, so that's why i run with a bug.

**Comment by urish** [comment]
Thanks for reporting! The thing is, we don't have an std builder for the ESP32-S3 yet. I'll discuss with @SergioGasquez to see what we can do about it.
