### ISSUE TITLE
ESP32 Simulation: FastLED.show() crashes when number of LEDs is a multiple of 8

### ISSUE THREAD

**Issue by github-ec** [wokwi/wokwi-features#565]
**Describe the bug**
FastLED lib in combination with ESP32 here at Wokwi crashes 
if the number is exactly  8 or a multiple of 8. The first call of
FastLED.show() in loop() stops the whole sketch.
For one led-ring with 16 LEDs you can use 1 to 7 or 9 to 15 or 17 ...
but NUM_LEDS = 8, 16, 24, 32, 40 or 48 ... let the sketch crash ....

**To Reproduce**
Use the sketch
[https://wokwi.com/projects/362461890000450561](https://wokwi.com/projects/362461890000450561)
but change the line 
`#define NUM_LEDS 49`    // This works!

to 

`#define NUM_LEDS 48` // This does not work, neither does 8, 16, 24, ... tested up to 48

**Expected behavior**
The number of LEDs should allow multiples of 8.

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser Google Chrome 
 - Version 112.0.5615.138 

**Additional context**
The identical sketch works with e.g. Arduino UNO simulation.
see [https://wokwi.com/projects/362458687561066497](https://wokwi.com/projects/362458687561066497)

The Sketch as txt-file:

[FastLED_ESP32_Bug.txt](https://github.com/wokwi/wokwi-features/files/11290364/FastLED_ESP32_Bug.txt)

**Comment by urish** [comment]
Thanks for reporting! Weird indeed

**Comment by urish** [comment]
Interestingly, this doesn't happen with ESP32-C3: https://wokwi.com/projects/362801722531028993

**Comment by urish** [comment]
Fixed!
