### ISSUE TITLE
Wokwi extension ELF conversion failure

### ISSUE THREAD

**Issue by MabezDev** [wokwi/wokwi-features#568]
**Describe the bug**
Automatic conversion from ELF to bin doesn't work

**To Reproduce**
Take [this ELF](https://cdn.discordapp.com/attachments/959934555534544936/1101127680683937832/sync) and use it for both `elf` and `firmware` keys of wokwi.toml (Note this ELF is built for esp32s3)

**Expected behavior**
The elf should be converted to bin and the simulation should start

**Environment (please complete the following information):**
 - OS: Linux
 - Browser VScode
 - Version 1.77.1

**Comment by urish** [comment]
Thanks for reporting! Fix is up - can you please test it?

**Comment by urish** [comment]
Fix is bad - working on another one

**Comment by urish** [comment]
New fix is up! ready to test

**Comment by MabezDev** [comment]
Works now, thanks!
