### ISSUE TITLE
Simulating Access Point Scanning Crashes the simulation

### ISSUE THREAD

**Issue by Vollbrecht** [wokwi/wokwi-features#569]
**Describe the bug**
using the AccesPoint scanning method in rust std esp-idf-svc -> scan() behaves differently in simulation as on real hardware.

**To Reproduce**
Here is a minimal repository that can build a minimal example : https://github.com/Vollbrecht/wifi-scan-wokwi-bug

**Expected behavior**
Dont return an ESP-FAIL error -> Either find the only available acces-point "Wokwi-Guest" or doesnt find any but continoue with the simulation

**Additional context**
Log output from simulation and real hardware:

[hardware_output.txt](https://github.com/wokwi/wokwi-features/files/11347708/hardware_output.txt)
[simulation_output.txt](https://github.com/wokwi/wokwi-features/files/11347709/simulation_output.txt)

Edit:
Added elf file for your convenience :smile_cat: 
[wifi-scan-wokwi-bug.zip](https://github.com/wokwi/wokwi-features/files/11347757/wifi-scan-wokwi-bug.zip)

**Comment by urish** [comment]
Thanks! Can you please add the compiled .elf file to the repo? I'm not very good at compiling Rust, so I'm bound to spend an hour or so just to figure out how to compile it.

**Comment by urish** [comment]
(You can also attach the compiled ELF file to this issue, if that's easier)

**Comment by Vollbrecht** [comment]
> (You can also attach the compiled ELF file to this issue, if that's easier)

done

**Comment by urish** [comment]
Thanks! Issue reproduces for me

**Comment by urish** [comment]
Initial investigation shows that the simulated program is sending an ARP packet, without even connecting to the access point:

![image](https://user-images.githubusercontent.com/892318/235072311-038f8029-7d5a-498e-8fa8-2c769ecf36f0.png)

**Comment by urish** [comment]
Trying to run the same on physical ESP32-C3, it also fails at the same point:

![image](https://user-images.githubusercontent.com/892318/235099853-4f441233-c5f3-4a07-8c26-5fb623e2fd52.png)

My current bet is that there's some issue with the NVS partition. Can you try to dump the current partition table and the NVS partition from your chip?

**Comment by Vollbrecht** [comment]
ah i forget about the nvs partition - i flashed not on a brand new esp and didn't override the flash :D will check it out

**Comment by urish** [comment]
Any updates? Should we keep this open?

**Comment by Vollbrecht** [comment]
Yeah i couldn't pinpoint it down exactly, to a repeatable case. Was using different methods to work with the nvs. I was also playing with a newer version of esp-idf here. If it surface again and i can pinpoint it better i will reopen.
