### ISSUE TITLE
draw more attention to the like button

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#57]
Hi

I would like to draw more attention from the users towards the heart button so that there will be good validation in listing/selecting famous projects. sometimes, I think it is blending with the other buttons. 

can we have some animation or a pop-up window to tell the user, to hit the button if they like the project?

![image](https://user-images.githubusercontent.com/68117142/106892541-3919da80-6712-11eb-8515-f46b61944dc0.png)

**Comment by urish** [comment]
Closing, as this got no votes in the past 6 months.
