### ISSUE TITLE
Neopixel Bad Colors

### ISSUE THREAD

**Issue by ndelapaz** [wokwi/wokwi-features#571]
**Describe the bug**
After using more than 42 neopixel leds, the strip put the wrong colors in some leds.

**To Reproduce**
Using more than 42 leds appears the problem, if you reduce que amount to 42 o less the colors works fine.
https://wokwi.com/projects/363590874378627073

**Expected behavior**
all leds has to have the same color.

**Environment (please complete the following information):**
 - OS: [e.g. iOS/Android/Windows]: MacOS
 - Browser [e.g. chrome, safari]: Firefox
 - Version [e.g. 22]:112:0.2

**Additional context**

**Comment by urish** [comment]
Thanks for reporting. Issue reproduces for me

**Comment by urish** [comment]
Seems like this is a regression that started after fixing #565. Investigating.

**Comment by urish** [comment]
Fixed! Thanks again for reporting :)
