### ISSUE TITLE
HD44780UA02 variant

### ISSUE THREAD

**Issue by chocomintyy** [wokwi/wokwi-features#573]
I'm constantly working on projects using Spanish and Catalan, both languages have accents and they can't be seen on the LCD i2c display, this would be a great feature for all the users that speak romance languages.

**Comment by urish** [comment]
Done!

Docs updated with the new variant: https://docs.wokwi.com/parts/wokwi-lcd1602#a02-variant
Quick example: https://wokwi.com/projects/363824415758035969

**Comment by chocomintyy** [comment]
This is so awesome!!! Thank you so much
