### ISSUE TITLE
Weird display on Oled SSD1306 on vscode-extension

### ISSUE THREAD

**Issue by AnisBoubaker** [wokwi/wokwi-features#574]
**Describe the bug**
When displaying information on an SSD1306 Oled, the result is weird (as if the display was divided into 4 different zones).  The problem does not occur on the website, only on the VS extension. 

**To Reproduce**
The simulated project is this one: https://wokwi.com/projects/363172552908797953
The same code is simulated on vscode. The elf and bin files are attached. 

**Expected behavior**
I expect the display to work the same as on the website. 

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser: Not relevant (vscode)
[firmware.zip](https://github.com/wokwi/wokwi-features/files/11391228/firmware.zip)

 - VSCode Version: 1.77.3

<img width="234" alt="Screen Shot 2023-05-03 at 4 42 33 PM" src="https://user-images.githubusercontent.com/46570545/236049045-aa45de60-78ea-4ec7-b092-5c2e66870df8.png">
<img width="267" alt="Screen Shot 2023-05-03 at 4 43 16 PM" src="https://user-images.githubusercontent.com/46570545/236049047-d60e9b5f-4e15-413e-9988-a520bc3a5047.png">

**Comment by urish** [comment]
Missing bin/elf files

**Comment by AnisBoubaker** [comment]
> Missing bin/elf files

You were too fast :-) Just attached them to the initial comment.

**Comment by urish** [comment]
Thanks! Seems like the issue is in the firmware - loading the compiled firmware to the website (go to https://wokwi.com/projects/363172552908797953, press F1 in the code editor, select "Upload Firmware and Start Simulation...", and choose firmware.bin) gives the same result as in VS Code. 

How do you compile the firmware?

**Comment by AnisBoubaker** [comment]
With PlatformIO, Arduino framework.  Here is the content of the platform.ini content: 

[env:esp32]
platform = espressif32
framework = arduino
board = esp32dev
lib_deps = 
	adafruit/Adafruit SSD1306@^2.5.7
	madhephaestus/ESP32Servo@^0.13.0

**Comment by urish** [comment]
Can you please share a repo with the complete setup?

**Comment by AnisBoubaker** [comment]
Here you are: https://github.com/AnisBoubaker/WokwiTest

**Comment by urish** [comment]
Thanks! I clone your repo, ran `pio run` to build the code, and then opened the folder in VS Code. Seems that it works correctly:

![image](https://user-images.githubusercontent.com/892318/236201370-f92bc9a8-6b94-4c01-8e35-e93bb4dc80fc.png)

Note: I had espressif32 version 5.2.0 installed. I'm now upgrading to the latest version (6.2.0), to see if I get a different result.

**Comment by urish** [comment]
Getting the same results even after upgrading the espressif32 platform.

Can you please run `pio pkg update`, then delete the `.pio` build directory, and run `pio run` to rebuild the project, and see if this changes anything for you?

**Comment by AnisBoubaker** [comment]
That fixed it, thank you for your help! I had an old version of expressif32, sorry I thought all these packages were always the latest version unless I say so.
