### ISSUE TITLE
Custom Characters for LCD stopped working.

### ISSUE THREAD

**Issue by Koepel** [wokwi/wokwi-features#577]
It was reported on the Discord channel that the custom characters for a LCD display do no longer work.

As far as I know, every Arduino C++ project has trouble with custom characters at the moment. It did not test Python.
For example: https://wokwi.com/projects/294395602645549578
The heart symbol is shown for a very short time and then it disappears.

There seems to be no logic for when it happens.
It happens with the LiquidCrystal, LiquidCrystal_I2C and hd44780 libraries.
Sometimes ten lines with `lcd.write('\1');` will work, and by adding another one, none of the custom characters is displayed anymore. Or when replacing one with `lcd.print('\1');` it stops working.
Some sketches can return to a situation that some custom characters are displayed, but soon with other code they disappear.

**Comment by urish** [comment]
Thanks for reporting! This is related to #573

**Comment by urish** [comment]
Fixed :-)

**Comment by Koepel** [comment]
Almost there.
Can you start this one and click the restart button many times: [https://wokwi.com/projects/364649895877421057](https://wokwi.com/projects/364649895877421057)
About 1 in 10 times, no Custom Characters are displayed.

**Comment by Koepel** [comment]
It might only fail in firefox, it seems to work in Chrome.

**Comment by urish** [comment]
Thanks for testing! That was some nasty race condition, that existed for a long long time. 

Should be fixed now - can you please test again and report?

**Comment by Koepel** [comment]
The custom characters work now all the time with every sketch and in every browser that I tested.
Thank you.

**Comment by ppvnf** [comment]
In my school project (the same we discussed in https://github.com/wokwi/wokwi-features/issues/231#issuecomment-1542602133) if I save the High Score name to the EEPROM  and then display it on the LCD, it will glitch (show 1 extra random character after the name). 

The same code won't glitch on my Arduino Uno. Also, changing line 42 from `char name[4] = "___"; ` to `char name[3] = "___";` will fix the problem on the emulator, however that will glitch on the Arduino Uno.

to reproduce the bug just press '1' on the keypad, and then press '#' 3 times (you can use 'A' to change the character, but that is unnecessary for reproducing the bug)
 https://wokwi.com/projects/365343012802008065
<img width="91" alt="Screenshot 2023-05-21 160727" src="https://github.com/wokwi/wokwi-features/assets/73800734/15bd7f33-a186-4b73-b356-20560f25cbcb">

**Comment by Koepel** [comment]
That is actually the same problem of EEPROM persistence.

If you add this at the end of setup(), then you can see the data:
```
  for( int i=2; i<6; i++)
  {
    Serial.print("0x");
    Serial.print(EEPROM.read(i), HEX);
    Serial.print(", ");
  }
  Serial.println();
```
It is 0xFF for all 4 characters. That means the zero-terminator is also 0xFF and the string had no defined length.
Your code should be able to deal with an empty EEPROM.
You remove that zero-terminator also with this code: `memset(name, '_', sizeof(name));`. It fills all 4 characters with '_'.

**Comment by ppvnf** [comment]
That makes sense, thank you!
