### ISSUE TITLE
rotate number - easy fix in need

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#58]
![image](https://user-images.githubusercontent.com/68117142/107256489-9342d480-6a5f-11eb-905e-e4f3510e2d90.png)

**Comment by urish** [comment]
Hi Puneeth, just write it without the quotes around the number, e.g.: `"rotate": 180`

**Comment by Puneethkumarsn** [comment]
okay! thanks a lot
