### ISSUE TITLE
Are there any limitations on the complexity of the algorithm used in Wokwi simulator

### ISSUE THREAD

**Issue by KlaudiuszSoltysik** [wokwi/wokwi-features#580]
I wrote tic-tac-toe game with minimax algorithm, but simulator seems to be not powerful enough to compute computer move. I am obeying that by providing prepared game board with 2 fields filled (less depth of decision tree).
Link to the game:
https://wokwi.com/projects/365185972838894593

**Comment by urish** [comment]
No limitations - we simulate the microcontroller at the instruction set level. You can add debug prints to your code to try to figure why it is not behaving the way you expect. Good luck!
