### ISSUE TITLE
SPI clock mismatch between Nucleo Physical and Wokwi Board (L432KC)

### ISSUE THREAD

**Issue by miso-mosi** [wokwi/wokwi-features#590]
**Describe the bug**
The SPI clock frequency on the Physical device doesn't match the simulated device

**To Reproduce**
Run the simulation here: https://wokwi.com/projects/365797682421188609

**Expected behavior**
Frequencies measured on the Wokwi logic analyzer and the physical logic analyzer should be the same

**Environment (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome
 - Version 113.0.5672.127 

**Additional context**
None
![2023-06-06_00h12_16](https://github.com/wokwi/wokwi-features/assets/133621245/ae8ae7b4-015b-46d0-9aaf-6aa42818292c)

**Comment by urish** [comment]
Fixed! Can you please verify?

**Comment by miso-mosi** [comment]
The measured SPI frequencies:  Wokwi L432KC and Physical Nucleo-L432KC, matches. ✅

Both measure 20 MHz. 
![2023-06-06_18h17_51](https://github.com/wokwi/wokwi-features/assets/133621245/2061559d-e49e-40ab-ab0f-a6b6e4819515)

**Comment by urish** [comment]
Thanks! Then you can go ahead and close the issue :)
