### ISSUE TITLE
Bug in map() in STM32 environment.

### ISSUE THREAD

**Issue by Koepel** [wokwi/wokwi-features#593]
The map() function for Wokwi with the STM32 environment has a bug.

This simple test works on a Arduino Uno, it returns 2.
When using Wokwi with the ST NUCLEO C031C6 board, it returns -4198401.
```
void setup() 
{
  Serial.begin(115200);
  int x = 100;
  int y = map(x, 0, 1023, 2, -2);
  Serial.println(y);
}

void loop() {}
```

Test project: https://wokwi.com/projects/366946693851653121

The map() function is not well defined and differs for different platforms. Some have an extra check for when the input limits are the same (it would result in a division by zero) and if that happens then some platforms return 0 and some platforms return -1.
The Arduino reference: https://reference.arduino.cc/reference/en/language/functions/math/map/

**Comment by urish** [comment]
Thanks for reporting! 

Unfortunately, I'm having trouble with getting my Nucleo-C031C6 board run this sketch. Spent an hour trying to figure out how to make it talk to OpenOCD (and also ST-LINK gdbserver), but support seems non existent at the moment.

**Comment by urish** [comment]
Tricky one, but now it is fixed!
