### ISSUE TITLE
Problem with the function minimizer

### ISSUE THREAD

**Issue by DanteCecchetti** [wokwi/wokwi-features#597]
**Describe the bug**
I'm having a problem minimizing a function (I don't know if specifically the action I'm referring to is called like this). I call minimize the function when you press the arrow that appears to the left of the word "void" once typed (this arrow also appears when you type any type of conditional: while, if, for, etc.) and allows you to retract all the code that appears inside the function/conditional. When I do a retraction I don't have any problem, but if I add some new line of code or just press enter above said retraction, the arrow that is to the left of the word "void" does not move to its true position, making that the retraction looks bad and simply, the name of the function in question cannot be seen. This problem arose after the last app update.

**Environment (please complete the following information):**
 - OS: Windows
 - Browser : chrome

**Additional context**

-Without applying enter on line 23
![without applying enter on line 23](https://github.com/wokwi/wokwi-features/assets/117865807/15178f01-1eec-45dc-9c70-2b7d9e934310)

-Applying a single enter on line 23
![applying a single enter on line 23](https://github.com/wokwi/wokwi-features/assets/117865807/5e4f5e42-34e3-474d-881f-04b298892a86)

-Applying two enter on line 23
![Applying two enter on line 23](https://github.com/wokwi/wokwi-features/assets/117865807/5f4fd00d-add9-4678-9311-a54aba70e772)

**Comment by urish** [comment]
Thanks for reporting! I've updated the [code editor](https://github.com/microsoft/monaco-editor/) to the latest version, in hope it may fix the issue.
