### ISSUE TITLE
ESP32: repeat timer period is 2x longer than expected

### ISSUE THREAD

**Issue by Dlloydev** [wokwi/wokwi-features#598]
**Describe the bug**
 The simulated ESP32 repeat timer produces twice the duration as the set value.

**To Reproduce**
 Simulation project: https://wokwi.com/projects/367395055144204289

**Expected behavior**
Expected to measure 1000 μs between interrupts

**Actual behavior**

* Measured 2000 μs between interrupts using wokwi-logic-analyzer
* The Chips API (Time API) appears to work as expected. Tested using PWM Breakout chip. Also tested [here](https://wokwi.com/projects/367429307095682049)
*  See comments on simulation project.
* Not tested with real ESP32 hardware.

**Environment:**

- OS: Windows 10,  Firefox

**Comment by urish** [comment]
Fixed - can you please check again and report?

**Comment by Dlloydev** [comment]
Looks good, thanks!

**Comment by urish** [comment]
And thanks for the super detailed bug report and reproduction instructions, it's really helpful!

**Comment by miso-mosi** [comment]
![2023-06-14_09h02_44](https://github.com/wokwi/wokwi-features/assets/133621245/36977d7b-3914-4928-a6ed-c6804c83bcdf)

I am too late I guess. Here is the screesnhot of the signals captured using actual hardware.
