### ISSUE TITLE
breakpoint option 

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#6]
A wish list feature is to stop the code execution at the instruction set. Is it really possible? Use case is to 

1. Visualise the output slowly - Graphics development and update can be made interesting.
2. I can turn the knob and keep it ready exactly at the moment where my code or logic should read the ADC value. This helps me debug the code and verify the control flow

 I will update more use cases if I find any

**Comment by urish** [comment]
This is now supported with GDB:

https://blog.wokwi.com/gdb-avr-arduino-cheatsheet/
