### ISSUE TITLE
VS Code plugin - simulator does not reload diagram.json, it's necessary to close the simulator

### ISSUE THREAD

**Issue by georgik** [wokwi/wokwi-features#601]
**Describe the bug**
VS Code plugin does not reload diagram.json when the similator is already open and user selects Start Wokwi from command pallete. Workaround close simulator manually and Start Wokwi simulation again. 

**To Reproduce**
- open VS Code, start simulation
- edit diagram JSON, do not close simulator
- open commands list and select Start simulator

**Expected behavior**
The simulator should reload diagram.json, when user selects new start.

**Comment by urish** [comment]
Thanks for reporting! Fixed in VS Code extension release 1.3.4

**Comment by georgik** [comment]
Perfect. Solution works. Now it's very convenient.
