### ISSUE TITLE
Delay not working as expected

### ISSUE THREAD

**Issue by SergioGasquez** [wokwi/wokwi-features#602]
Delays are not working as expected, setting 1-second delay results in about 2 seconds
## How to reproduce
Simulate a blinky example, e.g: https://wokwi.com/projects/341952826535051858

## Expected behavior
On real hw, the delay last, more or less, 1 seccond
<img width="1439" alt="image" src="https://github.com/wokwi/wokwi-features/assets/12926049/14a03ba0-7d43-4f91-9c7f-1e837f2344e4">

**Comment by urish** [comment]
Initial investigation shows that this is related to the ESP32 ROM accelerator (a mechanism that skips the ROM / bootloader and executes the user code directly). A quick workaround is to disable the ESP32 ROM accelerator by adding a `"fullBoot": "1"` attribute:

```json
        {
            "type": "wokwi-esp32-devkit-v1",
            "id": "esp",
            "top": 0,
            "left": 0.67,
            "attrs": {
                "builder": "rust-nostd-esp",
                "fullBoot": "1"
            }
        },
```

**Comment by SergioGasquez** [comment]
The issue also appears in
- [S2](https://wokwi.com/projects/341955297469792851)
- [S3](https://wokwi.com/projects/349568945405035090)

C3 seems to be working fine

**Comment by urish** [comment]
With ESP32-S2, it seems like same issue (ESP32 ROM accelerator).

For ESP32-S3/C3/C6 (and future chips), we don't use the ESP32 ROM accelerator. For ESP32-S3, it seems like there's an issue with the clock simulation, I'll investigate. The delay takes 4 seconds instead of just 1.

**Comment by urish** [comment]
Update: ESP32-S3 clock issue found and fixed

**Comment by urish** [comment]
I removed the ESP32 ROM accelerator. So now ESP32 and ESP32-S2 should always work correctly. 

This also means they are going to be more chatty when booting - but if this annoys users or break things, we can also disable the bootrom output.

Thanks again for the detailed report!
