### ISSUE TITLE
RGB LED COM Pin

### ISSUE THREAD

**Issue by nosknut** [wokwi/wokwi-features#603]
Feature 1:
The dox explain that the default setting is anode (positive).
It is more intuitive for beginners that the default settings reflect a similar behaviour to normal LED's, meaning you activate the pin, the LED color activates. The default COM should therefore be cathode (negative).

Feature 2:
There is no visual option to change the COM attribute. There should be a checkbox to make this more user friendly for beginners.

**Comment by AriellaE** [comment]
Hello @nosknut 
Thank you for your feedback. 
I added a checkbox for changing the common pin as you suggested.
