### ISSUE TITLE
Resistor value attribute should have a GUI input

### ISSUE THREAD

**Issue by nosknut** [wokwi/wokwi-features#604]
The resistor value attribute can currently only be changed by editing diagram.json.
To be more user friendly to beginners, there should be a text input to change this value, in the same place where you change LED colors and the buttons "bounce" attribute.

**Comment by C00lzer0** [comment]
A feature i am still missing too.

**Comment by AriellaE** [comment]
Done. 
![Screenshot 2023-07-18 at 14 54 51](https://github.com/wokwi/wokwi-features/assets/35613240/5d6d0c56-db47-4e5d-af33-3e3b39615094)

Thank you
