### ISSUE TITLE
Pull up resistor on GPIO 0 does not work on Pico

### ISSUE THREAD

**Issue by Lucvolders** [wokwi/wokwi-features#609]
**Describe the bug**
When a pull-up resistor is attached to GPIO-0 on the Raspberry Pico the pin still shows as value 0 both in Micropython as in Arduino IDE

**To Reproduce**
Link to MicroPython example:
https://wokwi.com/projects/369141069526856705

Link to Arduino IDE example:
https://wokwi.com/projects/369143295747092481

**Expected behavior**
Expected to have the value of the pin show up as 1

**Environment (please complete the following information):**
 - OS: windows 10
 - Browser Firefox, Chrome, Edge

**Additional context**
Confirmed by Urish on Discord

**Comment by urish** [comment]
Thanks for reporting!

**Comment by urish** [comment]
Fixed
