### ISSUE TITLE
options in the editor tab similar to Arduino IDE

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#61]
![image](https://user-images.githubusercontent.com/68117142/107920335-cc64d280-6f92-11eb-896f-473f282c222b.png)

* Comment/uncomment
* increase and decrease indent
something to match with the Arduino editor experience

**Comment by sutaburosu** [comment]
I'm not sure matching the Arduino IDE is desirable. :)

The Monaco editor used here is the same editor used in VS Code. Press F1 to call up the command palette, which is useful index to keyboard shortcuts.

To comment/uncomment, use `Ctrl /`.

For indentation, use `Ctrl ]` and `Ctrl [`.

**Comment by Puneethkumarsn** [comment]
I think this issue must be deleted. The Editor has more than enough feature for everyone to work with already
