### ISSUE TITLE
It will be greate if all the projects are visible in Read only mode to anyone in the internet. This will make a greate community where people can exchange ideas and look at what others are building. 

### ISSUE THREAD

**Issue by samjoe-coder** [wokwi/wokwi-features#611]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by urish** [comment]
Thanks for the feedback, we're working on it!

For now there are two pages where you can find public projects:

* rust - https://wokwi.com/rust
* micropython - https://wokwi.com/micropython
