### ISSUE TITLE
phone editing bug

### ISSUE THREAD

**Issue by Der-Meister-von-codes** [wokwi/wokwi-features#615]
When I try to edit some files on my phone, I cant do this, bacaus its just text, no-editable field. Please fix this bug, I wery love wokwi and wont have able to work with this by phone.

**Comment by urish** [comment]
Thanks for the feedback! There's already an open request to allow editing of the code on mobile phones, see #208.

Unfortunately, it hasn't received much votes. You can track the current feature vote status here: https://wokwi.com/features#feature-1028025160
