### ISSUE TITLE
diagram.json - can't cut, then paste, a component

### ISSUE THREAD

**Issue by alto777** [wokwi/wokwi-features#616]
I am unable to get a neopixel matrix into the diagram.json dexcription file.

I have a text file with some things that aren't on the pop-up menu of components. I cut from the file, after adjusting the "id", and paste into diagram.json. A bit inconvenient but It has worked for a long time. 

Now when I paste the component into a new sketch *.json file, the schematic window goes black, offers "RETRY", and does never recover.

In desperation (!), I took an existing project

[this one](https://wokwi.com/projects/369196030361510913)

and cut this from diagram.json:

    {
      "type": "wokwi-neopixel-matrix",
      "id": "neopixels1",
      "top": 15.72,
      "left": -415.48,
      "attrs": { "pixleate": "1", "rows": "1", "cols": "25" }
    },

(strip disappears, good)

and immediately pasted it back, having not budged the cursor, which should make the strip come back. As doing with a new project did up until now.

It does not. It behaves identically to adding the same thing to a basically blank project. Diagram window goes black, "RETRY", no joy.

Mac OS 10.14.5
Chrome Version 114.0.5735.198 (Official Build) (x86_64)

and Firefox 114.02

Safari does not work very well with wokwi, or didn't, so I don't use it anymore for that.

Did the neopixel matrix descriptor change? Where can I find all the neopixel parts? 

a7

**Comment by urish** [comment]
Thanks for reporting, should be fixed now!

Neopixel matrices / strips are still kind of hacky at the moment, should be fixed once we get an opportunity to work on #240 (and then we'll also add proper documentation).
