### ISSUE TITLE
Boeard Power Management

### ISSUE THREAD

**Issue by bodo29** [wokwi/wokwi-features#617]
For the moment I can use LEDs on digital output pins of Arduino boards without any resistor and the simulation  works. I can also use multiple relais or sensors on several pins at the same time without problems. In reality that doesn't work because of the current output restrictions of an Arduino.
Integrate a function in the simulator that checks connected devices with respect to their electric current consumption. Create a part to fix that problems, ULN2803A f. e.

**Comment by urish** [comment]
Thanks for the feedback! We focus on digital simulation, so unfortunately, we do not simulate analog parts like resistors or calculate current consumption. We don't even check if parts are powered - you can get a servo running without connecting it to power, only the signal. Wokwi focuses on the firmware, MCU, and digital communication (I2C, UART, SPI) simulation, with only limited analog support.

There's an open feature request to (simulate resistor dividers)[https://wokwi.com/features#feature-1021779688] (#203), which may be a first step in the way to supporting more complete analog simulation.
