### ISSUE TITLE
Support for Particle Devices

### ISSUE THREAD

**Issue by chipmc** [wokwi/wokwi-features#618]
I would like to see support for the Particle devices.  Particle is a significant IoT platform with a mature and well documented API and libraries.  Adding Wowki support could help is large community collaborate on IoT solutions without requiring everyone to purchase specific sensors or dedicate hardware to testing.  

Links: 
Particle - https://www.particle.io
deviceOS - https://docs.particle.io/reference/device-os/firmware/
Particle libraries - https://docs.particle.io/getting-started/device-os/firmware-libraries/
Particle community - https://community.particle.io

**Comment by urish** [comment]
Thanks for the suggestion! 

Unfortunately, adding support for those devices will require a huge amount of effort. So unless particle is interested in sponsoring the development, or there's a big commercial customer interested in these devices, it is not likely to happen any time soon.

**Comment by chipmc** [comment]
Understand, thank you.
