### ISSUE TITLE
the LED blinks when driven using PWM

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#62]
https://drive.google.com/file/d/1PdEIZc_VcqVcqMwifvd7RKIJqYE4QK5d/view?usp=sharing

The sketch link is below

https://wokwi.com/arduino/projects/290575991887102473

Observation
1. the blink happens only in Avast Secure browser (chrome) but not on the firefox browser. In the image, the left one is Avast browser and the right one is Firefox

**Comment by urish** [comment]
Thanks for reporting! I managed to reproduce, but not consistently. 

What is the relative simulation speed (in %) when this happens?

**Comment by urish** [comment]
I believe that this is fixed now, can you please check again and confirm?

**Comment by Puneethkumarsn** [comment]
yes. It is okay now :)

**Comment by urish** [comment]
Thanks!
