### ISSUE TITLE
esp-idf-hal UART inconsistent behavior 

### ISSUE THREAD

**Issue by apollolabsdev** [wokwi/wokwi-features#620]
Running the uart loopback example from the esp-idf-hal repo (https://github.com/esp-rs/esp-idf-hal/blob/master/examples/uart_loopback.rs) on the ESP32C3, the code seems to get stuck at the blocking read statement as the following println! statement does not get executed. When downloading the same code on real hardware works no issues are observed.

This is a link to the example project:
https://wokwi.com/projects/370479605507228673
Line 30 is where the execution halts.

**Comment by urish** [comment]
Thanks for reporting! Pausing the simulator shows that the pins (5, 6) do not get configured correctly as UART1 RX/TX:

![image](https://github.com/wokwi/wokwi-features/assets/892318/407fc72b-49a3-4fe4-88ce-6a87c5a76263)

Investigating why

**Comment by urish** [comment]
Actually, scratch that - I paused the simulation too early. For some reason, it takes the code more than 1 second to reach the actual UART test code, and I hit the "pause" button to early. So the pins do get assigned correctly:

![image](https://github.com/wokwi/wokwi-features/assets/892318/94857fd1-39ab-4fff-86e7-46db2cb460af)

**Comment by apollolabsdev** [comment]
I encountered the same behavior as I was trying to debug. Looking at the console, it seems that the device is still booting before the pins get finally configured.

**Comment by urish** [comment]
Alright, uploaded a fix - can you please test again and confirm?

**Comment by apollolabsdev** [comment]
Tried it out. Working as expected now, thanks!
