### ISSUE TITLE
esp-idf-hal UART Incorrect First Transmission 

### ISSUE THREAD

**Issue by apollolabsdev** [wokwi/wokwi-features#623]
Using UART with the esp-idf-hal the first transmission is always received incorrectly. Subsequent transmissions, however, work fine. To verify, I removed the UART code from the loop and it consistently shows the same behavior. 

The following is a link to Example Behavior:
https://wokwi.com/projects/370657861781898241

The value of 170 (in decimal) is sent, yet 245 is received instead.

**Comment by urish** [comment]
Initial investigation shows that the UART line goes low at the beginning: 

![image](https://github.com/wokwi/wokwi-features/assets/892318/1bb37776-7c9c-4e0b-b6fd-e51360cbaf7f)

This causes us to miss the first few bits of data:

![image](https://github.com/wokwi/wokwi-features/assets/892318/09bf08f0-f807-42ab-8a1a-fe6d3fa45bd3)

**Comment by urish** [comment]
Note: I already pushed a fix, but having some problems with the deployment. So hopefully the fix will be available sometime later today.

**Comment by urish** [comment]
Fix deployed! Can you please check now?

**Comment by apollolabsdev** [comment]
Checked it, it works! thanks for the fix!
