### ISSUE TITLE
rfc2217 memory leak

### ISSUE THREAD

**Issue by nosknut** [wokwi/wokwi-features#629]
When running the start command from the command palette while a simulation is active, the rfc2217 port in VScode publishes duplicate messages. The second time start is run it generates 3 versions of each message. The second time 5, third time 7 etc ...

The duplicate messages are coming from the new simulation so the simulation itself does not persist. Only the rfc server.

**Comment by urish** [comment]
Thanks for reporting! The issue reproduces for me.

**Comment by urish** [comment]
Fixed!
