### ISSUE TITLE
Blue pill STM32F103C8  -  SPI

### ISSUE THREAD

**Issue by dzid26** [wokwi/wokwi-features#637]
SPI functionality is missing in STM32F103C8.

Here is an example usage:
https://wokwi.com/projects/373792701364482049
<img width="631" alt="image" src="https://github.com/wokwi/wokwi-features/assets/841061/a2e3b9b7-9ebd-4dae-a7c5-0451f131691b">

The program hangs on:
> Program received signal SIGINT, Interrupt.
0x08000b88 in LL_SPI_IsActiveFlag_TXE (SPIx=0x40013000) at /home/hexi/.arduino15/packages/STMicroelectronics/hardware/stm32/2.6.0/system/Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_ll_spi.h:710
710       return ((READ_BIT(SPIx->SR, SPI_SR_TXE) == (SPI_SR_TXE)) ? 1UL : 0UL);

Called from SPI flag check: 
> (gdb) info stack
#0  0x08000b88 in LL_SPI_IsActiveFlag_TXE (SPIx=0x40013000) at /home/hexi/.arduino15/packages/STMicroelectronics/hardware/stm32/2.6.0/system/Drivers/STM32F1xx_HAL_Driver/Inc/stm32f1xx_ll_spi.h:710
#1  spi_transfer (obj=<optimized out>, tx_buffer=0x20004f8f "\001\377\377", rx_buffer=0x20004f97 "", len=<optimized out>, Timeout=1000, skipReceive=false) at /home/hexi/.arduino15/packages/STMicroelectronics/hardware/stm32/2.6.0/libraries/SPI/src/utility/spi_com.c:546
#2  0x08000432 in SPIClass::transfer (this=0x2000016c <SPI>, _pin=<optimized out>, data=<optimized out>, _mode=<optimized out>) at /home/hexi/.arduino15/packages/STMicroelectronics/hardware/stm32/2.6.0/libraries/SPI/src/SPI.cpp:251
#3  0x080019da in SPIClass::transfer (_mode=SPI_LAST, _data=1 '\001', this=<optimized out>) at /home/hexi/.arduino15/packages/STMicroelectronics/hardware/stm32/2.6.0/libraries/SPI/src/SPI.h:183
#4  Adafruit_SPITFT::spiWrite (this=this@entry=0x20000124 <tft>, b=b@entry=1 '\001') at /tmp/build-7HSdoc/libraries/Adafruit_GFX_Library/Adafruit_SPITFT.cpp:2120
#5  0x08001c20 in Adafruit_SPITFT::sendCommand (this=this@entry=0x20000124 <tft>, commandByte=commandByte@entry=1 '\001', dataBytes=dataBytes@entry=0x0, numDataBytes=numDataBytes@entry=0 '\000') at /tmp/build-7HSdoc/libraries/Adafruit_GFX_Library/Adafruit_SPITFT.cpp:1940
#6  0x080020b4 in Adafruit_ILI9341::begin (this=this@entry=0x20000124 <tft>, freq=<optimized out>, freq@entry=0) at /tmp/build-7HSdoc/libraries/Adafruit_ILI9341/Adafruit_ILI9341.cpp:194
#7  0x080001da in setup () at /tmp/build-7HSdoc/sketch/sketch.ino:23
#8  0x08006400 in main () at /home/hexi/.arduino15/packages/STMicroelectronics/hardware/stm32/2.6.0/cores/arduino/main.cpp:52
(gdb)

**Comment by urish** [comment]
Implemented! Example: https://wokwi.com/projects/374780854731040769
