### ISSUE TITLE
Blue pill STM32F103C8 - DWT - delayMicroseconds() not working

### ISSUE THREAD

**Issue by dzid26** [wokwi/wokwi-features#638]
Arduino's `delayMicroseconds(1000)` doesn't work on STM32F103C8. I think it hangs on [DWT->CYCCNT](https://developer.arm.com/documentation/ddi0403/d/Debug-Architecture/ARMv7-M-Debug/The-Data-Watchpoint-and-Trace-unit/CYCCNT-cycle-counter-and-related-timers) peripheral. 

I think this can be easily worked around by defining [DWT_DELAY_DISABLED](https://github.com/stm32duino/Arduino_Core_STM32/blob/main/cores/arduino/wiring_time.h#L66) in the build process.

**Comment by urish** [comment]
Thanks for reporting, fixed!
