### ISSUE TITLE
Option to upload the ino, .h and .cpp files 

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#64]
The **request** is to have an option to upload the files to the project.

Use case: For a multi-file project, there will be multiple files to be created manually 

- each file name has to be entered manually
- and the contents of the file has to be copied to the editor

The **benefit** of this feature
it will help the user to easily upload the files, especially in multifile projects

A **bonus** feature will be to upload all the project files at once :)

**Comment by urish** [comment]
Thanks for the suggestion! 

How would you like to upload the files?

**Comment by Puneethkumarsn** [comment]
an option in the menu itself
![image](https://user-images.githubusercontent.com/68117142/111030439-44a2a480-8428-11eb-997a-a1c12d5dd4c2.png)

**Comment by Puneethkumarsn** [comment]
another feature along with the upload file is to mention the link of the file. User shall be able to give the file link from GitHub or another site for example. as long the type of the file is supported.

**Comment by urish** [comment]
Thanks! This is now implemented:

![image](https://user-images.githubusercontent.com/892318/135439329-7d86b6a4-fc32-4436-81dc-140b4c5dde5e.png)
