### ISSUE TITLE
Bug in ESP 32 DHT 22.

### ISSUE THREAD

**Issue by PAULisaac12** [wokwi/wokwi-features#644]
I entered the WOKWI website for our project and encountered an issue with the ESP32 DHT22. Despite facing this challenge, we managed to overcome it and successfully completed our new project. However, due to this issue, our initial expectations were not met, and I lost the progress of my project, which was the result of our hard work.

*Environment (please complete the following information):*
- OS: Windows 11
- Browser: Chrome
- Version: 4

*Additional context:*
We encountered a problem with the WOKWI DHT22. Upon investigation, I identified the issue with pins D4 and D5, which were connected to the humidity sensor. As a result, we were unable to submit our project. While learning about the WOKWI DHT22, I came across this type of problem, and unfortunately, it led to the loss of our project progress.

![Screenshot 2023-09-12 190609](https://github.com/wokwi/wokwi-features/assets/144790252/15d2dfe7-4f03-47d5-9e2c-24197b0eab24)
[](https://wokwi.com/projects/322410731508073042)
My details ,
         Email : [mr.paulisaac1212@gmail.com] 
Founded by : 
             PAUL ISAAC . S

**Comment by urish** [comment]
Please take a look at the following example: https://wokwi.com/projects/322410731508073042

**Comment by PAULisaac12** [comment]
In that link it has not sensing with the humidity sensor in D4 and D5. So check that issue. I has attached the screenshot below.
![Screenshot 2023-09-12 190609](https://github.com/wokwi/wokwi-features/assets/144790252/dd8cbf5e-858a-4817-8bc0-da075b41b739)

**Comment by urish** [comment]
So it works with D15 but not D4/D5? Interesting

Have you tried it with D5 on real hardware?

**Comment by PAULisaac12** [comment]
I'm not doing in reality even I am learner that's why I'm mailed about this

**Comment by urish** [comment]
Okay, so we'll have to wait until someone can try this on real hardware to verify this is indeed a bug in the simulation and not in the library or some ESP32 limitation. Thanks for reporting!

**Comment by PAULisaac12** [comment]
I can try in hard ware and report it with the proof file thank you.

**Comment by urish** [comment]
That would be very helpful

**Comment by PAULisaac12** [comment]
but the report is confirm what will u do

**Comment by urish** [comment]
If we know the behavior is different between the simulator and hardware we can start investigating why

**Comment by PAULisaac12** [comment]
if the bug is confirmed and the problem founded by me any payment will be provided for the report.

**Comment by PAULisaac12** [comment]
if the bug is confirmed and the problem founded by me any payment will be provided for the report.

**Comment by urish** [comment]
I wish we were in a situation we could provide payment to anyone who submits a bug report. Unfortunately, we are not.

**Comment by K1rdro** [comment]
I tested this on my hardware, and can confirm this is IRL behavior with this library. I was able to get it to return values after some tweaking of the code, but I would recommend using the available Adafruit DHT sensor library instead.
