### ISSUE TITLE
MicroPython Update

### ISSUE THREAD

**Issue by ghost** [wokwi/wokwi-features#651]
MicroPython v1.21.0 would add some more options to `machine.PWM` for Pico:
https://github.com/micropython/micropython/releases/tag/v1.21.0

Example where it would be useful:
https://wokwi.com/projects/378026754493598721

**Comment by urish** [comment]
Added MicroPython 1.21.0. It's now the default for new MicroPython projects.

For existing projects, you need to bump the version in diagram.json manually:

```json
      "attrs": { "env": "micropython-20231005-v1.21.0" }
```

**Comment by ghost** [comment]
Thanks, works! (The piezo buzzer emulation seems to produce double the frequency, though, and clicks only with mode `"accurate"`, if driven symmetrically.)
