### ISSUE TITLE
std::array won't work

### ISSUE THREAD

**Issue by AlexanderTonn** [wokwi/wokwi-features#653]
It's not possible to include the std::array header in the wokwi online editor.  With Arduino IDE 2.0 and VSCode Arduino extension, the ```#include <array>``` is compiling without error

I've created a project for showing the issue:  https://wokwi.com/projects/377839112927963137

``` shell
sketch.ino:1:10: fatal error: array: No such file or directory
 #include <array>
          ^~~~~~~
compilation terminated.

Error during build: exit status 1
```

**Comment by urish** [comment]
`<array>` is also not available in the Arduino IDE when compiling for the Arduino Board Uno:

![image](https://github.com/wokwi/avr8js/assets/892318/a2bbcc13-61c7-4557-8eea-5992c10d9785)

You may have installed some third party library that provides this file into your local Arduino installation.

Behind the scenes, Wokwi uses the Arduino CLI to compile your code, so it should be equivalent to how Arduino IDE builds the code. You can use the [Library Manager](https://docs.wokwi.com/guides/libraries) to install standard Arduino libraries as needed.

**Comment by sutaburosu** [comment]
I have used the code [in this Stackexchange comment](https://arduino.stackexchange.com/a/69178) successfully on Wokwi.
