### ISSUE TITLE
How do I add multiple files

### ISSUE THREAD

**Issue by AlphaTechNinja** [wokwi/wokwi-features#655]
How to add multiple files to a project. I’m asking because I want to organize my code is there anyway?

**Comment by sutaburosu** [comment]
With the "New file" option from the drop-down menu on the list of tabs in the editor.

A picture can be worth a thousand words. Hopefully this helps:
![image](https://github.com/wokwi/wokwi-features/assets/20606/f913a5f2-7c95-4a07-87e1-a4dbb6cad2ec)
