### ISSUE TITLE
Misalignment for older projects with a breadboard.

### ISSUE THREAD

**Issue by Koepel** [wokwi/wokwi-features#659]
Old projects that didn't use the grid do no longer work because there is a misalignment.
As far as I know, it only happens with a breadboard.

Example: https://wokwi.com/projects/328952970765926995
The resistor is no longer connected.

![afbeelding](https://github.com/wokwi/wokwi-features/assets/12096541/a4e960d9-73bc-4636-9f00-46bbc5784582)

**Comment by urish** [comment]
Thanks for reporting! I investigated this, and it looks like it only applies to projects created before Jan 21st, when we slightly adjusted the pin positions of the resistors to fit them on the grid. As far as I can tell, this only functionally affects resistors that are attached to a breadboard. Unfortunately, there is no easy fix, so I'll just fix my own demo projects and close the issue. Other users are invited to fix their own projects.
