### ISSUE TITLE
MGB-I2C63EN

### ISSUE THREAD

**Issue by Vitalij31** [wokwi/wokwi-features#661]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Comment by urish** [comment]
Thanks for your suggestion. I [looked up this part](https://mgbot.ru/catalog/platy_rasshireniya/plata_rasshireniya_mgb_i2c63en_rj_9_v1_0en_c_i2c_khabom/), and it seems to be pretty niche and has no English documentation. We won't be implementing it in Wokwi. In the future, we hope to let users contribute them own custom boards (see #302), so users may be able to contribute this part.
