### ISSUE TITLE
CircuitPython stopped working with "env" set to "circuitpython-20210914-8520c43"

### ISSUE THREAD

**Issue by Koepel** [wokwi/wokwi-features#667]
This problem was reported in the Discord channel.

CircuitPython does no longer work with the "env" attribute set to "circuitpython-20210914-8520c43", but it does work with "circuitpython-7.0.0-rc.1".

The examples in the 'Docs' do therefor not work: https://docs.wokwi.com/guides/circuitpython
The starter does also not work: https://wokwi.com/projects/new/circuitpython-pi-pico

**Comment by urish** [comment]
Thanks for reporting! I'm not sure why `circuitpython-20210914-8520c43` stopped working, but as the name suggest, it's a two year old version. 

I updated the template + all existing project that used the old version to 8.0.2, which seems to work well. Total of 3534 projects were updated.
