### ISSUE TITLE
ESP32-S3 with display connected to SPI3 does not work

### ISSUE THREAD

**Issue by georgik** [wokwi/wokwi-features#668]
When connecting SPI display to ESP32-S3 in Wokwi, it's possible to use only SPI2.

Problem: SPI3 does not work

Note: The similar situation was already present in ESP32 simulation.

Working project: https://wokwi.com/projects/380020905633874945

**To Reproduce**
Change SPI2 to SPI3 in the project and try to run it: https://wokwi.com/projects/380020905633874945

**Expected behavior**
Text is displayed in the screen.

**Comment by urish** [comment]
Thanks for reporting! When choosing SPI3, pin names indeed look weird: 

<img width="305" alt="image" src="https://github.com/wokwi/wokwi-features/assets/892318/020714c8-606a-448d-b9bf-793793e65838">

Looking into why

**Comment by urish** [comment]
Fixed!

**Comment by georgik** [comment]
Perfect. It Works. Thank you for the quick fix
