### ISSUE TITLE
Wokwi CI - Support for rotating screenshots

### ISSUE THREAD

**Issue by georgik** [wokwi/wokwi-features#670]
Current state: Wokwi CI is able to take a screenshot, but it does not take into account orientation of simulated display. User needs to rotate the screenshot afterwards using tool like ImageMagic which might not be present in CI build container.

Example of diagram.json: https://github.com/georgik/esp32-spooky-maze-game/blob/main/esp-wrover-kit/diagram.json#L18

Desired state: Image is rotated, either by using the information from `diagram.json` or from a CLI parameter.

**Comment by urish** [comment]
The CI should now take into account the "rotate" value from the diagram (it only works for right angle rotations, i.e. 90 / 180 / 270 degrees)
