### ISSUE TITLE
Copy all / select all button for exams

### ISSUE THREAD

**Issue by mfranzen0906** [wokwi/wokwi-features#671]
We would like to use Wokwi in exams at our school.
Therefore the students are supposed to copy the code from Wokwi into the online exam.

Since they are not allowed to download and upload files during the exam, copying the written code and diagram would be sufficient enough for the exam. 

Yet copying the code on iPads is currently not working. 

Is there a way to create a Copy All or at least a Select All button for the textfields?

**Comment by urish** [comment]
Added a Select All button to the context menu:

![image](https://github.com/wokwi/wokwi-features/assets/892318/a8d79afd-723a-44d0-818f-0e62cecc651f)
