### ISSUE TITLE
A "Select all" for the all the text of the code.

### ISSUE THREAD

**Issue by Koepel** [wokwi/wokwi-features#672]
Could a "Select all" or "Copy all" option be added ? It is in my opinion a useful addition.
This problem was mentioned in the Discord channel. When an iPad is used, then it is not easy to copy all the text. 

For example:
![afbeelding](https://github.com/wokwi/wokwi-features/assets/12096541/65c93ad9-aa42-4e4d-9f73-c7f5a6033c05)

Possible options:
1. A button.
2. Added to the drop-down menu on the right of the tabs.
3. Added to the Monaco menu (the menu that appears with a right click or F1).
4. Added to the Command Palette (which can be selected after opening the Monaco menu).

**Comment by urish** [comment]
![image](https://github.com/wokwi/wokwi-features/assets/892318/b5acdabd-ac35-4158-b5fa-cdf86b5b9c8c)
