### ISSUE TITLE
Add Lock Icon

### ISSUE THREAD

**Issue by wulfhednar02** [wokwi/wokwi-features#674]
In order to add to organization, I would like to see locked project on the projects page. I use the locked project when I have completed a design, and this would help with knowing which designs are complete without having to go into each project.

I do not think the lock icon needs to be functional, in that it locks / unlocks the project. I believe that going into the project to lock or unlock it is good, to keep the lock somewhat safe. It would just be helpful to have the display of the lock.

**Comment by urish** [comment]
Good idea - added a display of the lock
