### ISSUE TITLE
GDMA the DMA support for ESP32 S3 / C3 / C6 / H2

### ISSUE THREAD

**Issue by georgik** [wokwi/wokwi-features#676]
Please add GDMA support for  ESP32 S3 / C3 / C6 / H2.

Example without DMA on ESP32-C3 works: https://wokwi.com/projects/380658681618693121

Example with DMA (GDMA) on ESP32-C3 has blank display: https://wokwi.com/projects/381270798558541825

**Comment by urish** [comment]
GDMA support implemented
