### ISSUE TITLE
Simulator not recognising variable attributes correctly

### ISSUE THREAD

**Issue by Graham55H** [wokwi/wokwi-features#677]
The simulator changes global variables in an interrupt routine which are then reflected in the body of the program. In the actual device, changes made in an interrupt routine are NOT reflected in the body of the program unless the variable is declared as "volatile".

I declare a variable "milliseconds" as a global unsigned long, and set it to 0. In the interrupt routine, this variable is incremented on a timer interrupt when a switch is closed. In the main program, this initiates the "loop" action. In the simulator, closing the switch sets the loop process in action, but in the actual device, the loop doesn't run. I traced this to the change in the "milliseconds" variable not being transferred out of the interupt; declaring the "milliseconds" variable as "volatile" corrects the problem, and allows the loop code to run.

Windows 10, Chrome version 119, Arduino Uno, rev 3. The device compiler / programmer is the Arduino IDE, V2.2.1. The code can be found under MIDI_player in my projects.

**Comment by sutaburosu** [comment]
> changes made in an interrupt routine are NOT reflected in the body of the program unless the variable is declared as "volatile".

This is to be expected, and exactly what the `volatile` keyword is intended to work around. Honestly, it's surprising that your code works as intended on your physical device without `volatile`.

I feel that this is unlikely to be an issue with the simulation, but rather a difference in the compiled binaries generated by your local Arduino toolchain compared to the toolchain installed on the Wokwi build server.

It would be nice if you could verify this by uploading [the .hex built on your machine](https://arduino.stackexchange.com/questions/48431/how-to-get-the-firmware-hex-file-from-a-ino-file-containing-the-code#48437) and testing it within Wokwi. Press F1 in the Wokwi code editor and select "Upload Firmware and Start Simulation".

> The code can be found under MIDI_player in my projects.

I checked your GitHub profile, and there are no repos/projects with that name, so I presume you're referring to a Wokwi project. Your username here on GitHub isn't listed on [the Wokwi Makers page](https://wokwi.com/makers) so there is no way for me to discover your projects. It would be useful to include a link to your project in this ticket.

**Comment by Graham55H** [comment]
Hi – see my inline response in red.

 

Best regards

 

Graham

**Comment by sutaburosu** [comment]
> The source of the binaries surely shouldn’t be relevant?  Otherwise, what’s the point of having a language specification?

It is relevant. Different minor versions of a single compiler can generate very different code from the same source. There is nothing in the specification preventing a compiler from reading a variable from memory each time it is referenced (i.e. code that unexpectedly works without `volatile`). For some reason the compiler chose to not optimise away these superfluous memory accesses, despite not being forced to do so by `volatile`.

I'm sure if you upload the hex that didn't work on a real board, you will see the same results in Wokwi.
