### ISSUE TITLE
Dht22 error constants

### ISSUE THREAD

**Issue by Gavin-Perry** [wokwi/wokwi-features#681]
**Describe the bug**
In dht22.h the error constants e.g. dht22.OK were made private

**To Reproduce**
  if (dht22.getLastError() != dht22.OK) {   // dht22.OK was made private, get compile error

**Expected behavior**
it should compile!

**Environment (please complete the following information):**
Not that it matters...
 - OS: Windows
 - Browser chrome  119.0.6045.160 (Official Build) (64-bit) (cohort: Stable)

**Comment by urish** [comment]
Can you get the code to compile on your own computer?

Wokwi doesn't implement its own compiler - it just uses the standard Arduino compiler (arduino-cli).

**Comment by Gavin-Perry** [comment]
Yes the code compiles fine on my own computer. Or at least it did. I'll double check to make sure they're haven't been any changes. Perhaps you use different flags in the compiling commands.

Gavin

Sent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Phetdanai** [comment]
Yes but in function `void loop` has this code

`if (isnan(t) || isnan(h)) {`                      
`   Serial.println("Failed to read from DHT sensor");`
`   return;`
`}`

It's my  ESP32 Blynk IoT project

**Comment by Phetdanai** [comment]
Serial monitor display
`Failed to read from DHT sensor`
forever

**Comment by Phetdanai** [comment]
Only one solution is:
Use pull-up resistor about 4700 - 10000 ohms

**Comment by Gavin-Perry** [comment]
Non of the comments addressed the issue of failing to compile. I reinstalled Arduino and rebooted and that resolved the problem.
