### ISSUE TITLE
analogReadMilliVolts() crashes the ESP32-S2 and shows a message on the ESP32-S3.

### ISSUE THREAD

**Issue by Koepel** [wokwi/wokwi-features#683]
The function analogReadMilliVolts() is for the Arduino layer and is an extra function from Espressif.
Calling the function analogReadMilliVolts() crashes the ESP32-S2 and it resets.

The analogReadMilliVolts() on the ESP32-S3 shows this message: "ADC_CALI: esp_adc_cal_characterize(140): No calibration efuse burnt 0".

Test project: https://wokwi.com/projects/382766079385499649

**Comment by urish** [comment]
Fixed (also for the S3/C3). Thanks for the detailed report!
