### ISSUE TITLE
hx711 not working in vscode

### ISSUE THREAD

**Issue by Juli-L** [wokwi/wokwi-features#684]
I tried to use the HX711 with the ESP32 in VSCode. It works fine on the website, but it fails to initialize the load cell in VSCode

https://wokwi.com/projects/382911040339664897
[esp32_hx711.zip](https://github.com/wokwi/wokwi-features/files/13526290/esp32_hx711.zip)

**Comment by urish** [comment]
This is caused as the VS Code project is using a different library (there are two different libraries called HX711). You can fix it by changing platformio.ini as follows:

```
lib_deps = robtillaart/HX711
```

**Comment by Juli-L** [comment]
Thanks it works now
