### ISSUE TITLE
Sticky buttons are released when the mouse cursor moves over them.

### ISSUE THREAD

**Issue by Koepel** [wokwi/wokwi-features#686]
This issue was reported on the Arduino forum: https://forum.arduino.cc/t/questions-about-wokwi/1194411
As far as I can tell, this happens on every browser, on every Operating System.

When I use Ctrl + click to keep a button pressed, then it gets released when I no longer press the Ctrl key and move the cursor outside the area of the button.

Every Wokwi project with a button has this. For example the Piano: https://wokwi.com/projects/291958456169005577

It might be related to this Issue: https://github.com/wokwi/wokwi-features/issues/578

**Comment by urish** [comment]
Thanks for reporting, fixed!
