### ISSUE TITLE
pico sdk stdio_init_all()

### ISSUE THREAD

**Issue by rafaelcorsi** [wokwi/wokwi-features#687]
The Pico SDK fails to compile when using `stdio_init_all()`, resulting in an error message that suggests avoiding this function call . However, this approach is not ideal since it prevents testing the same software in both hardware and simulation environments. 

Test case: https://wokwi.com/projects/382961943505755137

Erro/warning msg:
```
/rp2040/hardware/rp2040/3.6.0/cores/rp2040/Arduino.h:138:44:
error: static assertion failed: stdio_init_all is not supported or needed.
Either use Serial.printf() or set the debug port in the IDE to Serial/1/2 and use printf().  
See https://github.com/earlephilhower/arduino-pico/issues/1433#issuecomment-1540354673 and 
https://github.com/earlephilhower/arduino-pico/issues/1433#issuecomment-1546783109
```

**Comment by rafaelcorsi** [comment]
uhm... I think this issue arises due to the example projects provided on the Wokwi Pico SDK page, which seem to use the Arduino library. However, when I create a new project from the 'My Projects' section, it works properly.

**Comment by urish** [comment]
Yeah, I'm not sure how supported is using the Pico SDK directly in the Arduino environment. You can look at their GitHub repo here, perhaps this is documented: https://github.com/earlephilhower/arduino-pico.

To you the Pi Pico SDK directly, just start with the following project template: https://wokwi.com/projects/new/pi-pico-sdk

**Comment by rafaelcorsi** [comment]
ok thanks! i just suggest you to update the pico sdk example on the webpage because it is using the arduino porject.

**Comment by urish** [comment]
Good idea, done!
