### ISSUE TITLE
Example how to export variable for Wokwi-CLI on token page

### ISSUE THREAD

**Issue by georgik** [wokwi/wokwi-features#688]
Current state: When creating a new CI token, there is following message displayed:
```
Token created
Your secret token "working-token" has been created.
Please copy it now, as you won't be able to see it again.
```

Desired state: Display also example which environment variable should be set to get wokwi-cli working, so that one does not need to seek documentation and copy the whole command. Basically the same convenience which one can get when setting up GitHun self-hosting runner.

E.g. for *nix shells:
```
export WOKWI_CLI_TOKEN="wok_....."
```

**Comment by urish** [comment]
Excellent suggestion, thanks!

Implemented: 

![image](https://github.com/wokwi/wokwi-features/assets/892318/7277659c-e8f6-4b44-825c-031d9894c559)
