### ISSUE TITLE
Error installing Library - not found

### ISSUE THREAD

**Issue by GyverLibs** [wokwi/wokwi-features#691]
**Describe the bug**
Error installing library

**To Reproduce**
Bug is hard to reproduce, it can appear after adding an empty line of code in editor, and disappear same way

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Win 11 x64
 - Browser Chrome
 - Version latest

**Additional context**
Maybe it's an error in library repo? It has *library.properties*, but no *library.json*

![image](https://github.com/wokwi/wokwi-features/assets/84599917/f13266f8-9d37-478b-b068-7becab24dd05)

**Comment by urish** [comment]
Thanks for reporting! Is this a library that was recently published?

**Comment by GyverLibs** [comment]
Few weeks ago. It works in wokwi, but very unstable. Even an empty line of code can break it. And fix too 😅

**Comment by urish** [comment]
Thanks, looking into it!

**Comment by GyverLibs** [comment]
🙏 🙏

**Comment by urish** [comment]
Ok, I uploaded a fix. Can you please try now?

Note that for existing projects, the error might be cached. In that case, simply add `?build-cache=disable`  (e.g. https://wokwi.com/projects/328451800839488084?build-cache=disable) to force a rebuild. This all also update the cache and fix the error in the future.

**Comment by GyverLibs** [comment]
yes, it works! Many thanks
