### ISSUE TITLE
Wokwi Traditional Chinese Translation

### ISSUE THREAD

**Issue by Sear-0887** [wokwi/wokwi-features#696]
**Is your feature request related to a problem? Please describe.**
Please give the community using non-simplified chinese a translation.
Note the #211 #393 all discusses about simplified chinese which is different.
I've translated the current English string json and some preview:
[zhcn.json](https://github.com/wokwi/wokwi-features/files/13696702/zhcn.json)
```
...
"project.shareDialog.closeButton": "關閉",
  "simulator.tabs.simulation": "模擬",
  "simulator.tabs.code": "程式",
  "simulator.tabs.description": "描述",
  "simulator.main.restart": "重啟模擬",
  "simulator.main.start": "開始模擬",
  "simulator.main.resume": "繼續",
  "simulator.main.pause": "暫停",
  "simulator.main.addNewPart": "增加組件",
  "simulator.main.stopSimulation": "停止模擬",
  "simulator.main.zoomGridTooltip": "縮放, 網格與更多",
  "simulator.buildFailedDialog.title": "建構失敗",
...
```

**Comment by urish** [comment]
Thanks!

Translations added :)

![image](https://github.com/wokwi/wokwi-features/assets/892318/5bdd8f5a-7db9-4c4e-ab2e-232ebe78e1dc)

**Comment by urish** [comment]
Direct link to see the translation in action: https://wokwi.com/projects/new/esp32?lang=zh-Hant
