### ISSUE TITLE
MQTT program crashes - ESP32

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#697]
**Describe the bug**
The connection resets and program termiantes
**To Reproduce**
[Steps to reproduce the behavior, including link to a simulation project where we can see the problem.

Run https://wokwi.com/projects/322577683855704658 and try cahnging the value of temp. and humidity value of the sensor a few times. 

**Expected behavior**
updated values should be published in the terminal
**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome, 120.0.6099.109
 

**Additional context**

The issue also happens in Firefox browser.. 120.0.1 (64-bit)
![trial3](https://github.com/wokwi/wokwi-features/assets/68117142/30ad5ecc-ee72-425e-9692-386b0420c835)

**Comment by urish** [comment]
Thanks for reporting. This is not a simulator issue - rather, there is a problem with the HiveMQ MQTT broker.

As a workaround, you could use `broker.emqx.io`, which is a different free broker, until HiveMQ broker is fixed.
