### ISSUE TITLE
do we have a LCD with rows

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#70]
Link: https://wokwi.com/arduino/libraries/LiquidCrystal_I2C/HelloWorld

in the example provided, the code expects the LCD to be 4 rows one. the simulated LCD element has only two rows. is there any update possible?

![image](https://user-images.githubusercontent.com/68117142/112574485-5d419000-8e14-11eb-98a8-8dc00ee3fee8.png)

**Comment by urish** [comment]
Added wokwi-lcd2004: 

https://docs.wokwi.com/parts/wokwi-lcd2004
