### ISSUE TITLE
Add a Description/README.md file to the other new project templates 

### ISSUE THREAD

**Issue by drf5n** [wokwi/wokwi-features#700]
**Is your feature request related to a problem? Please describe.**
When I'd doing an Uno project, I have trouble remembering the README.md -> Description tab that you see on :

https://wokwi.com/projects/new/blank

**Describe the solution you'd like**
Please add the README.md file to the other template projects besides "Blank" available from the New Project dropdown on the https://wokwi.com/dashboard/projects page to provide for easy additional documentation.

**Comment by urish** [comment]
Thanks for the proposal! What should the initial README contain?

**Comment by drf5n** [comment]
Copying a slightly more generalized version of the one that is already delivered in https://wokwi.com/projects/new/blank seems OK:

```
# Wokwi project

This is a Wokwi project. Please edit this README file and add a description of your project.

## Usage

1. Add parts by clicking the blue "+" button in the diagram editor
2. Connect parts by dragging wires between them
3. Click the green play button to start the simulation
```

Or it could demonstrate a few more more Markdown features like a link to markdown:

```
[Markdown syntax](https://daringfireball.net/projects/markdown/syntax)

![some SVG Logo](https://www.adobe.com/cc-shared/assets/img/product-icons/svg/express.svg)

* item
* item 2

    code1
    code2

```

(I wonder why this github comment isn't rendering markdown.)

**Comment by urish** [comment]
Thanks! The comment probably doesn't render markdown since it was sent via email:

![image](https://github.com/wokwi/wokwi-features/assets/892318/5ae08f76-a5e1-4ae3-84db-5a147e5000ce)

Added a default README file for new projects. Let's wait for a week and see how it goes!

e.g. https://wokwi.com/projects/new/esp32

**Comment by urish** [comment]
Unfortunately, this change didn't make any significant difference, so I plan to revert it. 

Here's the data:

![image](https://github.com/wokwi/wokwi-features/assets/892318/b6def9dc-5f25-43ec-bc81-9a4369898c70)
