### ISSUE TITLE
Pushbutton shortcut conflicts with "Add new part" menu

### ISSUE THREAD

**Issue by leon0399** [wokwi/wokwi-features#701]
**Describe the bug**
A conflict with pushbutton shortcut setting for a key `A` and a UI shortcut to add new part

https://github.com/wokwi/wokwi-features/assets/1759654/69920308-07bb-489b-9b28-e6c957501101

**To Reproduce**
1) add push-button
2) click onto pushbutton shortcut field
3) press `a` to set it as a shortcut
4) "add new component" menu opens

**Expected behavior**
4) `a` button is set as a shortcut

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Brave (Chromium)
 - Version: v1.61.106 (Chromium 120.0.6099.115)

**Additional context**
Funny enough, but at my job I fixed the same error less then a month ago, and already have a snippet ready for you:
```typescript
const isEditingContent = (event: KeyboardEvent): boolean => {
    let element = event.target! as HTMLElement;
    let tagName = element.tagName;
    return (
        element.isContentEditable ||
        tagName === 'INPUT' ||
        tagName === 'SELECT' ||
        tagName === 'TEXTAREA'
    );
};

...

if ((!isEditingContent(event) && event.key === 'A') {
    ...
}
```

**Comment by urish** [comment]
Thanks for the detailed report and proposed solution. Used it with minor adaptions:

```ts
/**
 * Returns true if the given keyboard event is fired from a text input element.
 */
export function isEditingText(event: KeyboardEvent | React.KeyboardEvent) {
  if (!event.target || !(event.target instanceof HTMLElement)) {
    return false;
  }

  const tagName = event.target.tagName;
  return (
    event.target.isContentEditable ||
    tagName === 'INPUT' ||
    tagName === 'SELECT' ||
    tagName === 'TEXTAREA'
  );
}
```

and now users can happily type "a" in the shortcut field :-)
