### ISSUE TITLE
VS Code combine the simulator and diagram editor?

### ISSUE THREAD

**Issue by videopilot** [wokwi/wokwi-features#703]
On the website, we can edit and simulate in the same view. In VS Code we get two identical views that behave differently. I'm constantly trying to edit in the simulator view. It even looks like it will let me edit when I hover over a pin. What's more is that it's an extra non-obvious step to get to the code for the diagram ("open with").

Consider making the editor and simulator one view and the diagram.json file just open to the code. I'm not sure what the best way to get to the simulator would be. "Arduino Sketch Auto Switcher" adds buttons to the toolbar in the ino file to go start the simulation. There must be a better way to work like the website. Maybe opening the diagram.json just opens both views?

**Comment by urish** [comment]
Thanks for the feedback!

> What's more is that it's an extra non-obvious step to get to the code for the diagram ("open with").

In which cases do you need to edit the diagram as text? Ideally, we'd want to make sure the visual editors covers most of these cases (and perhaps offer some shortcut to reopen as text for more advanced users)

>  Maybe opening the diagram.json just opens both views?

That's actually the first thing I tried when I introduced the diagram editor. Unfortunately, VS Code kills the window when the tab is inactive, meaning the simulation restarts whenever you switch to a different tab. This is a limitation of the VS Code's [Custom Text Editor API](https://code.visualstudio.com/api/extension-guides/custom-editors#custom-text-editor). After spending some time studying the API, I believe the editor/simulator window split adheres better to the mental mode of VS Code (but feel free to prove me wrong here).
