### ISSUE TITLE
wokwi-slide-potentiometer doesn't respect "value" on startup/load.

### ISSUE THREAD

**Issue by drf5n** [wokwi/wokwi-features#707]
**Describe the bug**
wokwi-slide-potentiometer doesn't respect "value" on startup. 

**To Reproduce**
1) Set a the value attribute per

https://docs.wokwi.com/parts/wokwi-slide-potentiometer

`      "attrs": { "travelLength": "50", "value": "512" }`

2) save the simulation
3) reload the simulation

See https://wokwi.com/projects/385381410929180673 for an example:

<img width="1150" alt="image" src="https://github.com/wokwi/wokwi-features/assets/2236516/fcbeda42-5d2b-4ca2-b627-c503c811bc47">

**Expected behavior**
I expected the pots to move to the "value" position on initial load, as they do when you edit the diagram.json file:

<img width="1145" alt="image" src="https://github.com/wokwi/wokwi-features/assets/2236516/398b2f9a-d8c4-441a-8ac3-a9d5d81ac1b5">

I like that the pots do not move to "value" when you run the sketch, but I would expect the initial position to match "value".

**Environment (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 120.0.6099.109 (Official Build) (arm64)

**Additional context**
None.

**Comment by drf5n** [comment]
Here's a simpler example:

1) load example from https://docs.wokwi.com/parts/wokwi-slide-potentiometer

> [Slide potentiometer + Servo](https://wokwi.com/projects/297604176384360973) - Control a [servo](https://docs.wokwi.com/parts/wokwi-servo) with a slide potentiometer

2) add a value attribute:

```
    {
      "type": "wokwi-slide-potentiometer",
      "id": "potentiometer",
      "top": 79.25,
      "left": 397.42,
      "rotate": 0,
      "hide": false,
      "attrs": {"value":"512"}
    },
```


3) Save copy, such as:

https://wokwi.com/projects/385383386673965057

4) reload copy 

5) Observe that the pot is rendered at "value":"0"

**Comment by urish** [comment]
Thanks for reporting! Issue reproduced.

**Comment by urish** [comment]
Fixed

**Comment by drf5n** [comment]
Thanks, it's fixed on Chrome on Mac, but not on Safari on iphone:

https://wokwi.com/projects/385383386673965057 

gives:

<img width="374" alt="image" src="https://github.com/wokwi/wokwi-features/assets/2236516/1fe70f5a-281c-4733-8939-7d43835c51c8">

**Comment by urish** [comment]
Right, should also be fixed now
