### ISSUE TITLE
AC Lamp request

### ISSUE THREAD

**Issue by Phetdanai** [wokwi/wokwi-features#708]
_Originally posted by @Phetdanai in https://github.com/wokwi/wokwi-features/issues/681#issuecomment-1871930629_

**Comment by Phetdanai** [comment]
I need AC Lamp for that relay.

**Comment by Phetdanai** [comment]
```c++
void setup ()
{
  pinMode(2, OUTPUT);
}

void loop ()
{
  digitalWrite(2, HIGH);
  delay (1000);
  digitalWrite (2, LOW);
  delay (2000);
}
```

**Comment by Phetdanai** [comment]
or else
```shell
  sudo apt install gcc g++ python3
```

**Comment by Phetdanai** [comment]
```python
print("Hello")
```

**Comment by urish** [comment]
Thanks for opening the request. AC Lamp (or anything that is more than a few ten of volts) is out of the scope of Wokwi. You can use a simple LED to represent the AC lamp.
