### ISSUE TITLE
"wokwi-relay-module" Atrribute "transistor" not working

### ISSUE THREAD

**Issue by maker999** [wokwi/wokwi-features#712]
Hi,

Relay module's attribute not working as in Docs.

According to docs "wokwi-relay-module" is supposed to have a "transistor" attribute where it determines if it's going to be active-low or active-high (default) but it doesn't change anything in the simulation.

example
`{ "type": "wokwi-relay-module", "id": "relay1", "top": -86.2, "left": 211.2, "attrs": {"transistor":"pnp"} },`

Environment:
 - OS: Windows
 - Browser: firefox
 - Version [121]

**Comment by urish** [comment]
Hello, as far as I can tell it is working. 

* [Without pnp](https://wokwi.com/projects/347308007359513172):

![image](https://github.com/wokwi/wokwi-features/assets/892318/43f131fe-f43b-493d-b146-06425c942669)

* Same project as above, after changing "transistor" to "pnp":

![image](https://github.com/wokwi/wokwi-features/assets/892318/62e2ba14-eae8-43d4-9951-307200ab9762)

**Comment by maker999** [comment]
thanks. could you share how you changed the attribute?
Best Regards,
Saeed Helali

**Comment by urish** [comment]
```json
    {
      "type": "wokwi-relay-module",
      "id": "tiny1",
      "top": -76.6,
      "left": -134.4,
      "attrs": { "transistor": "pnp" }
    },
```

and here's the complete project: 

https://wokwi.com/projects/386069552818017281
