### ISSUE TITLE
How to use Interrupt in HAL based STM32 Projects?

### ISSUE THREAD

**Issue by Bharathgopal** [wokwi/wokwi-features#714]
Unable to use Interrupt in STM32 HAL mode. 
Getting multiple redefinition error for the interrupt function in the example: **https://wokwi.com/projects/386357910379730945**

Unable to find any example online which shows the usage of interrupt in HAL versions.

**Comment by urish** [comment]
Hi! 

Wokwi uses the [Arduino Core for STM32](https://github.com/stm32duino/Arduino_Core_STM32/tree/main), which takes care of the interrupts:

https://github.com/stm32duino/Arduino_Core_STM32/blob/73b834c8f9ef5722e3bd8d8f0b0f82ce0f9dcb4b/libraries/SrcWrapper/src/stm32/interrupt.cpp#L244

If you want to go with plain HAL, the best way would probably be to use Wokwi for VS Code and compile the code on your computer. Here's an example project:

https://github.com/wokwi/stm32-hello-wokwi
