### ISSUE TITLE
Wokwi simulator with Vs^code

### ISSUE THREAD

**Issue by leppto** [wokwi/wokwi-features#715]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behavior, including link to a simulation project where we can see the problem.

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. iOS/Android/Windows]

**Additional context**

**Comment by leppto** [comment]
Mac os 14.2.1
VS Code 1.85.1
Wokwi Simulator 2.4.0

When running code ( https://wokwi.com/projects/386174991780008961 ) with browser, everything works, but running in VS Code simulation, terminal "printing" is not visible and ex. servo doesn't move.

**Comment by urish** [comment]
Hello, can you please share the complete project directory in a github repo and post the link here?

Usually, this is because of incorrect configuration or not compiling the project correctly

**Comment by leppto** [comment]
https://github.com/leppto/RemoteGearControl

**Comment by urish** [comment]
Thanks! The problem happens because the board name in platformio.ini is incorrect. Please change it as follows:

```
platform = atmelavr
board = nanoatmega328
```

Then it should work:

![image](https://github.com/wokwi/wokwi-features/assets/892318/e5e2bb4b-0024-4170-8be9-552e3542c844)
