### ISSUE TITLE
On the best way to make a "custom chip" with half duplex

### ISSUE THREAD

**Issue by 0x0fe** [wokwi/wokwi-features#719]
So i try to emulate a simple RS485 network with a master and few nodes, to work on some auto address assignement issues. I found the "custom chip" UART inverter, which seems like a good base, however it is full duplex, and to emulate RS485 it should be half duplex. For the protocol emulation i dont think it is useful to emulate the differential mode, so a single line and a DE/RE port would be fine. But it is unclear to me how to write it in the chip init. Does anyone have a clue?

**Comment by urish** [comment]
There's currently not direct support for half duplex mode, but you can just "bit-bang" the protocol using the [GPIO API](https://docs.wokwi.com/chips-api/gpio).

**Comment by 0x0fe** [comment]
oh i see, and what is if define the same pin for TX and RX on a standard uart.

**Comment by urish** [comment]
You could try - not sure how it'll work

**Comment by 0x0fe** [comment]
i will, if not i'll go for the bit banging, thank's again

**Comment by urish** [comment]
You're welcome :) Looking forward to seeing what you'll come up with

**Comment by 0x0fe** [comment]
i made two attemps, the first with essentially a 2:1 mux, where DE controls INOUT mode and wether is connected to RX or TX (via the pin_watch function), it would work in real life but for some reason it doesnt in the simulation, i dont see the correct state changes when i monitor the pin_watch function, actually i see 13 state changes or more when i only send on byte.
https://wokwi.com/projects/387274633680543745

The second attempt is with the uart peripheral, where I reconfigure the port on the fly to use INOUT as TX or RX pin depending on the state of DE, which would also work in real life but does in the simulation, i suspect the reason is ; we cannot reconfigure the UART ports on the fly.
(i lost this one after reloading it while it was not properly saved)

Could you confirm we indeed cannot reconfigure the uart ports on the fly? 

Is there another approach i did not think of?

**Comment by urish** [comment]
> i made two attemps, the first with essentially a 2:1 mux, where DE controls INOUT mode and wether is connected to RX or TX (via the pin_watch function), it would work in real life but for some reason it doesnt in the simulation, i dont see the correct state changes when i monitor the pin_watch function, actually i see 13 state changes or more when i only send on byte.

I don't see the "DE" pin - did you post the correct link?

**Comment by 0x0fe** [comment]
well, it looks like i also lost this one now, i dont understand why, because it was saved multiple times, the name was sp3485, now it is uart-chip-example.ino Copy 
I will remake this soon and post a hopefully working link.

So, that's it : 
https://wokwi.com/projects/387387205731708929

And when i send the byte 0x55, i see 10 transistions on ID6 RX (the sender), i would expect 9 (8N1)
![image](https://github.com/wokwi/wokwi-features/assets/89607149/828c2b88-ea87-47b0-8749-84bf1fed0905)

same on ID5 INOUT (as expected)
![image](https://github.com/wokwi/wokwi-features/assets/89607149/d4247c3e-6786-48c3-8ab0-791f80a76cce)

which results in the wrong character
![image](https://github.com/wokwi/wokwi-features/assets/89607149/5a6e6e61-6ba8-49ba-846f-165c87b99b0b)
