### ISSUE TITLE
Wiring bug on Safari 

### ISSUE THREAD

**Issue by tawjaw** [wokwi/wokwi-features#72]
Hello, 
The wiring on Safari has bugs. 
The following is the led example. Left on safari, right on Chrome.  

![image](https://user-images.githubusercontent.com/10591561/113202719-1949f300-9239-11eb-8e08-21d301fb2cd2.png)

If I inspect the SVG element for the wiring part I get different SVGs from safari vs chrome 

![image](https://user-images.githubusercontent.com/10591561/113202846-48606480-9239-11eb-956b-7c0b26f1c37c.png)

**Comment by urish** [comment]
I think I may fixed it in the new diagram editor branch: 

https://diagram-editor.preview.wokwi.com/arduino/libraries/demos/blink-mega

I couldn't reproduce the original issue, but I'd love to know if the new branch fixes this issue for you?

**Comment by tawjaw** [comment]
The link you shared loads for a while and then gives me "An unexpected error has occurred." on safari and chrome. 

This works well though. 
https://diagram-editor.preview.wokwi.com/arduino/libraries/demo/blink

**Comment by urish** [comment]
My bad, I pasted the wrong link. The correct one is: https://diagram-editor.preview.wokwi.com/arduino/libraries/demo/blink-mega

**Comment by tawjaw** [comment]
the wiring is working fine. it's fixed

**Comment by urish** [comment]
Hooray! Thank you :)
