### ISSUE TITLE
Port the vscode extension to other editors (i.e neovim)

### ISSUE THREAD

**Issue by aikooo7** [wokwi/wokwi-features#720]
**Is your feature request related to a problem? Please describe.**
Me, being a neovim and needing to completely change to vscode just for using wowki is kind a pain.

**Describe the solution you'd like**
Port (maybe with the help of the community) the vscode extension to other editors (i.e neovim)

**Comment by urish** [comment]
Thanks for the request! We've done a survey to see which editors are popular, and unfortunately, it looks like neovim is pretty niche. Unfortunately, we don't have the resources to maintain extensions for multiple editors at the moment.

There's a community effort by @Jozott00 to support Intellij: https://github.com/Jozott00/wokwi-intellij/. If that goes well, perhaps other community members can try to port it to support neovim or other editors.
