### ISSUE TITLE
Precesion settings with up-down arrow on existing gauge settings on simulation proccess.

### ISSUE THREAD

**Issue by amp-coder** [wokwi/wokwi-features#724]
I'm always frustrated when trying to adjust the precise distance into ultrasonic sensor.
It would be nice for all of us to do some precesion settings with up-down arrow on existing gauge settings on simulation proccess.
With the existing gauge bar, it's almost impossible to do such precision adjustment. Ex. adjust the distance into ultrasonic sensor.
It would be very usefull if there are an up and down arrow to do that settings with ease like the photo.
![gauge1](https://github.com/wokwi/wokwi-features/assets/153449785/d4c79961-dd40-45e6-93d6-01bdc79c54e3)

**Comment by urish** [comment]
Thanks for the feedback! 

Have you tried clicking on the slider and using the keyboard up/down keys to change the value?

**Comment by amp-coder** [comment]
No but i can see that your solution is works well. Thank you Uri.

Στις Τετ, 24 Ιαν 2024, 13:59 ο χρήστης Uri Shaked ***@***.***>
έγραψε:
