### ISSUE TITLE
Cannot go to "your subscriptions" for my profile

### ISSUE THREAD

**Issue by geekgarage** [wokwi/wokwi-features#725]
**Describe the bug**
Cannot go to "your subscriptions" for my profile

**To Reproduce**
Click profile img on wokwi website and click "your subscriptions"

**Expected behavior**
No clue other than it should not give me an error

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 122.0 (64-bit)

**Additional context**

![image](https://github.com/wokwi/wokwi-features/assets/12700648/8c5cb1f5-9a35-411e-8140-765706c15d86)
![image](https://github.com/wokwi/wokwi-features/assets/12700648/60fbfbe7-b8e2-4c2b-aa3f-c6d16bed46ec)

Here is a test project so you can locate my profile
https://wokwi.com/projects/388273577509997569

**Comment by urish** [comment]
Thanks for the detailed report! Pushed a fix, can you please test and report if it works well now?

**Comment by geekgarage** [comment]
I can confirm it i can go into "Your Subscriptions". But i don't know If i should be able to restart my subscription.
![image](https://github.com/wokwi/wokwi-features/assets/12700648/28cfbbe2-5cc5-459b-ac09-18145522118b)

Currently i cannot "reverse" my cancellation, and it would be nice to have the option to do so.

**Comment by urish** [comment]
Thanks for the feedback! I'm not sure if our payment provider (Paddle) supports this, I'll have to check. It's possible to create a new subscription (on https://wokwi.com/club), but I do understand the value of undoing your cancellation

**Comment by geekgarage** [comment]
Problem is that i bought for a year and then cancelled right after to avoid getting renewed in case it didn't provide me with value, but it actually provides me great value, so i would like to keep going whenever it runs out. But for now I'll just have to keep an eye out for when it stops saying "Club Member" in my profile and then renew, because if I do it now it want full payment for a year, today, and i know I at least have about 6 months left.
