### ISSUE TITLE
Custom board isn't fully saved in project

### ISSUE THREAD

**Issue by geekgarage** [wokwi/wokwi-features#726]
**Describe the bug**
When i got to load my custom board into a project. then save it, after I've been doing wiring up components. If i then close the site and come back to it later I will have to load the custom board again before it is visible

**To Reproduce**
1. Create a project
2. Click inside the code editor, press "F1" and choose "Load custom board file..."
3. Select the directory that contains the board definition files (board.json and board.svg)
4. Board is now loaded
![image](https://github.com/wokwi/wokwi-features/assets/12700648/df8fb9e4-71b2-4399-bd9c-353377c4a921)
5. Save project
6. Close website
7. Open site and go to "My Projects" in the profile menu
8. Open the same project and have a look
![image](https://github.com/wokwi/wokwi-features/assets/12700648/99c017ca-271e-4b59-adf3-45822de65048)
9. Click inside the code editor, press "F1" and choose "Load custom board file..."
10. Select the directory that contains the board definition files (board.json and board.svg)
11. Board is now loaded

**Expected behavior**
I expect when i save the project with my custom board, that the board is saved to the project as well. 
I don't expect that when i open the project on my PC or tablet that i would have to load the custom board again every time i open it

**Environment (please complete the following information):**
 - OS: Android/Windows
 - Browser Both Chrome and Firefox
 - Version Latest for both windows and android

**Additional context**
Project
https://wokwi.com/projects/388202397151520769

Custom Board PR
https://github.com/wokwi/wokwi-boards/pull/28

**Comment by urish** [comment]
Thanks for the detailed report. This is by design: the purpose of `wokwi-custom-board` is just to serve as a quick way of testing custom boards while developing them. They are not meant to be sharable (yet).

 The JSON format for custom boards will probably change at some point, and I hope to implement a UI for defining the pins, connection and board features (#302 tracks this). Until this happens, the way to go with custom boards is using the custom-boards repo that you've already found :)

**Comment by geekgarage** [comment]
I see that you note in #302 that "Right now, we already have most of this implemented in the [wokwi-boards](https://github.com/wokwi/wokwi-boards/) project, but it's not very documented, and I perhaps not user friendly enough, so we don't see any user contributed custom boards."

Now I have contributed with a board and would love to create more. But if it takes forever to actually get them added, I can't really spend much time on it. I would love to help out and contribute to the project, but again, only if I actually see it's been taken serious and actually gets added within a reasonable time frame, not months after a PR have been made. I honestly think it's well enough documented to do custom boards as it is, also why i did https://github.com/wokwi/wokwi-boards/pull/28 to get the board I'm using in the list of available boards. So you can say this first custom board PR is a test run to see how it gets handled :)

I've also added some info how my take is on the PR for custom boards here https://github.com/wokwi/wokwi-boards/issues/29
