### ISSUE TITLE
6mm push button request

### ISSUE THREAD

**Issue by kevinrussel** [wokwi/wokwi-features#728]
Hello! This is very simple but I would like a smaller push button ( as I have gathered right now it is 12 mm) but a 6mm push button would be very helpful). I would like this as it takes up less space on the breadboard.

**Comment by urish** [comment]
Done. ESP32 for scale:

![image](https://github.com/wokwi/wokwi-features/assets/892318/c7ce7b3a-86f9-463e-99c6-b5f3e804f2ee)
