### ISSUE TITLE
ESP32 ledc produces same frequency if channel 0 and 1 aere used

### ISSUE THREAD

**Issue by wvsbsp** [wokwi/wokwi-features#731]
**Describe the bug**
I use two ledc channels to generate pwm with different PWM-frequncies. Both channels have the same PWM frequencies if channel 0 and 1 are used. Two different (correct) frequencies are generated, when i use channel 0 togehter with channel 2, 3, .... etc.

**To Reproduce**
In this example, both frequencies are different (and no multiples). Change the second #define to use channel 1 instead of 2, and both frequencies are identical (50Hz). Then swap lines 9 and 10 and both channels generate 123Hz (lastest setting "wins")
https://wokwi.com/projects/388882778029965313

**Expected behavior**
Each LEDC PWM channel should be independent of his neighbors.

**Environment (please complete the following information):**
 - OS: Win11
 - Browser Chrome
 - Version 120

**Comment by urish** [comment]
Thanks for reporting! Have you tested this in hardware too?

**Comment by wvsbsp** [comment]
I used different PWM frequencies in other projects with real hardware before. I didn't notice any malfunction of the servo (that was the part that made me wonder...). But it could be that in my hardware-projects is set the servo-pwm last.
I'll check tomorrow several combinations of channels and frequencies and hook up my 4chan scope.

**Comment by wvsbsp** [comment]
Ok, here it comes... i tried different channels today and hooked up my scope...
My test-program (changed the channel-number multiple times, changed the position of the LED_chan setup):

`#define LED_chan 0    
#define Servo1_chan 4
#define Servo2_chan 5
const int LED = 5, Servo1 = 18, Servo2= 23;

void setup() {
  // put your setup code here, to run once:
  Serial.begin(115200);
  Serial.println("Demo Bug in LEDC function");
  ledcSetup ( LED_chan, 123, 12);                // <<<<< ===== uncomment here
  ledcSetup ( Servo1_chan, 50, 12);              // latest setting "wins" if chan 0 and 1 are used
  //ledcSetup ( LED_chan, 123, 12);                // <<<<< ===== uncomment here
  ledcSetup ( Servo2_chan, 100, 11);              // latest setting "wins" if chan 0 and 1 are used
  //ledcSetup ( LED_chan, 123, 12);                // <<<<< ===== uncomment here
   ledcAttachPin ( LED, LED_chan);
  ledcAttachPin ( Servo1, Servo1_chan);
  ledcAttachPin ( Servo2, Servo2_chan);
}

void loop() {
  delay(250); // this speeds up the simulation
  int value0 = analogRead ( A0 );
  int value3 = 4095-value0;
  ledcWrite ( LED_chan, value3);
  // 12 Bit PWM Resolution, 50Hz => T=20ms
  // PMW-value 408 => 0.1 * T = 2ms, 204 => 0.05 * T = 1ms
  int Servo1_Pos = map (value0, 0, 4095, 204, 408);
  int Servo2_Pos = map (value0, 0, 4095, 408, 204);  // inverted servo, this one uses 100Hz with 11 bits, so same pwm-values
  ledcWrite ( Servo1_chan, Servo1_Pos);
  ledcWrite ( Servo2_chan, Servo2_Pos);
}
`

When i use LEDC-Channels that are more at least two numbers higher, everything works fine. When the channel-numbers are even and odd, both channels generate the same frequencies.
According to the datasheet, it should be possible, to select one of four clock-sources for a group of eight channels. h_timer0 to 3 can be routed to h_channel0 to 7 and l_timer0 to 3 can be selected for l_channel0 to 7. So for up to 4 channels, there should be enough clock-sources in each lecd-group - yes, but only if the programmer selects the channels properly.
Maybe, the compiler does not (want to) keep track of the used channels and their settings but simply assigns the same clock-source for two channels.

Reference: Data-Sheet Page 391, Configuration-Register LEDC_HSCHn_CONF0_REG has two bits LEDC_TIMER_SEL_HSCHn to select one of four clock-sources. 
https://www.espressif.com/sites/default/files/documentation/esp32_technical_reference_manual_en.pdf#ledpwm

Seems, this "error" is not in Wokwi, it is a "feature" of the compiler ;-)

**Comment by urish** [comment]
Thanks for checking!
