### ISSUE TITLE
The boards wont align in the center of the simulator window

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#737]
![2024-02-21_11h14_54](https://github.com/wokwi/wokwi-features/assets/68117142/86dcf921-78e5-472f-a846-d30517f51b32)
![2024-02-21_11h15_09](https://github.com/wokwi/wokwi-features/assets/68117142/4d48cac2-50c8-428b-9d82-e7fb54832030)
![2024-02-21_11h15_18](https://github.com/wokwi/wokwi-features/assets/68117142/64b8e6fe-5323-4734-8fc8-0973220bf7d3)

A refresh of the page later brings the board to the center. The links were opened from the home page.

**Comment by urish** [comment]
Thanks for reporting, this doesn't reproduce for me. 

Does it still happen? Which web browser? Can you open the devtools console and check if there are any errors there?

**Comment by matititam** [comment]
To recreate, 

I followed below steps. 

1. Open Wokwi home page and scroll down to ESP32 -IDF section - https://wokwi.com/esp32
2. Use the mouse scroll whell to click on the avaiable options  (ther are 6 board examples, currently). 

I am using chrome browser (Version 121.0.6167.185 (Official Build) (64-bit))
![2024-02-22_10h13_44](https://github.com/wokwi/wokwi-features/assets/68117142/9106045b-1be2-4aea-92bd-18d5e6cd0b04)
![2024-02-22_10h14_17](https://github.com/wokwi/wokwi-features/assets/68117142/94dec973-35aa-400d-9845-1a2e9e70bad0)

**Comment by urish** [comment]
Thanks, nothing suspicious on the dev console. Does it center if you press fit?

![image](https://github.com/wokwi/wokwi-features/assets/892318/5e7f040d-d68a-45c2-87cb-924e62713b80)

Also, can you try checking in incognito mode? It might be some Chrome extension that is causing this

**Comment by matititam** [comment]
When the part is not loaded as aligne, the options wont work No errors are created on the console while clicking on the options. The zoomin option doesn't work. No errors during this operation on the console. 
![esp-idf-4](https://github.com/wokwi/wokwi-features/assets/68117142/8865910c-4ec0-4bed-bb71-9ce733ffaab2)

**Comment by urish** [comment]
Hmm, then I'm assuming that in this case you are also not able to zoom in or drag with the mouse?

**Comment by matititam** [comment]
Yp

> Thanks, nothing suspicious on the dev console. Does it center if you press fit?
> 
> ![image](https://private-user-images.githubusercontent.com/892318/306941641-5e7f040d-d68a-45c2-87cb-924e62713b80.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1OTgwNDYsIm5iZiI6MTcwODU5Nzc0NiwicGF0aCI6Ii84OTIzMTgvMzA2OTQxNjQxLTVlN2YwNDBkLWQ2OGEtNDVjMi04N2NiLTkyNGU2MjcxM2I4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyMlQxMDI5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWQzYzU3Nzk0MjYxMTQ0ZTkxNTE4NjQyMTQ4Y2NlMDRiYWUyZWM5YTczZWM1ZGM4ODdkZDE4Mzc3NDkxN2M4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tLD7X3Nu9YJpKIJt6VKSJD5QBsdQw9u2jx2DSQBQC_U)
> 
> Also, can you try checking in incognito mode? It might be some Chrome extension that is causing this

It doesn't happen in the incognito mode. It might a plugin then.

**Comment by matititam** [comment]
> Hmm, then I'm assuming that in this case you are also not able to zoom in or drag with the mouse?

Mouse scrollbar can be used to zoomin zoomout. as well as drag. Even after dragging to the center, the zoom in zoom out or fit options doesn't work from the menu But the mouse scroll works.

**Comment by urish** [comment]
> It doesn't happen in the incognito mode. It might a plugin then.

Can you try to temporarily disable some chrome extensions and see if this helps?

Also, can you try signing out of Wokwi (in normal Chrome) and see if this makes any difference?

**Comment by matititam** [comment]
I had only two addons. Adblocker and a dark mode plugin. After removing darkmode plugin, i am not able to reproduce it.

**Comment by matititam** [comment]
reinstalled the addon and the issue appears immediately. 
This is the plugin I used.

https://chromewebstore.google.com/detail/dark-mode-dark-reader-for/pjbgfifennfhnbkhoidkdchbflppjncb?hl=en-US&utm_source=ext_sidebar

**Comment by urish** [comment]
So dark mode plugin it is. We should probably add this to the docs.
