### ISSUE TITLE
just a question… author setting

### ISSUE THREAD

**Issue by alto777** [wokwi/wokwi-features#738]
I've looked and can't find where or who informs the _diagram_._json_

`  "author": "Elmer Fudd",`

section. I would like to change it, but see no place where the connection is made or the name supplied.

TIA

alto777

**Comment by urish** [comment]
It's taken from your name in the Wokwi account, which is automatically initialized from Google / GitHub if you use them as a sign in provider. Currently, the only way to change it is to request this manually.

**Comment by alto777** [comment]
It appears I am a GitHub signer inner.

I suggest that the text for the author field should come from the GitHub handle/nickname, not some detail in the user's informations. So in this case, "alto777".

Can I switch sponsors and change my login from via GitHub to via your other vectors, forget but I think Facebook and a Google or gmail account? Without losing my foot in the door for all my stored projects?

a7

**Comment by urish** [comment]
I changed it to "alto777" for your user specifically. In the future, the plan is to have this editable through the profile page.

It's possible to switch by going to https://wokwi.com/dashboard/profile, then linking google (and later unlinking GitHub if you wish).
