### ISSUE TITLE
switching between simulator window and description tab - loses the set zoom level

### ISSUE THREAD

**Issue by matititam** [wokwi/wokwi-features#74]
https://wokwi.com/arduino/libraries/demo/electronic-safe

- When I switch between the simulator window and the description window, the simulator window forgets the zoon level I was in. it will render the whole circuit to the full page again. I would expect it not to do that. 
- Secondly, the servo motor can be seen falling from default position to expected position every time it is rendered (switched between simulator tab and description tab. Pls, see the below video for details.

https://drive.google.com/file/d/1xqQKahLTi-MeRPRCCJJXueHO858E3NHr/view?usp=sharing

**Comment by urish** [comment]
Thanks for reporting, fixed!
