### ISSUE TITLE
List of components I would like to have on Wokwi:

### ISSUE THREAD

**Issue by notesow** [wokwi/wokwi-features#742]
1. Batteries of 1.5V / 3V / 9V / 12V
2. Ability to set an input value to VCC
3. LM2577 Booster Module
4. LM2596 Voltage Regulator
5. Various connectors and terminals
6. LED Strip with the ability to set the voltage to 3V, 5V, 12V, 24V
7. LED Strip RGB + IC or Classic

**Comment by urish** [comment]
Thanks for listing down your requested parts!

However, Wokwi's focus is digital simulation, and these are mostly analog components, so we are not going to add those parts, except for the LED strip (which is already there, but needs to be better documented - see #240)
