### ISSUE TITLE
Arduino UNO digital input PIN read HIGH value while connected to GND with a resistor

### ISSUE THREAD

**Issue by hplc** [wokwi/wokwi-features#750]
**Describe the bug**
Arduino UNO digital input PIN should read LOW but get HIGH value while connected to GND with a resistor. 

**To Reproduce**
Arduino UNO any digital PIN sets to INPUT mode, with a resistor even 1 ohm connected to GND.
https://wokwi.com/projects/392069743481981953

**Expected behavior**
For PIN 0 digitalRead(0) should be LOW, but read HIGH.

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 123.0.1

**Comment by urish** [comment]
Thanks for reporting. This happens because the pin is connected to the Wokwi serial monitor, which drives it high. It's best to avoid pins 0 / 1 since they are used by the serial monitor.
