### ISSUE TITLE
hcsr04 support in micropython

### ISSUE THREAD

**Issue by seth-noaa** [wokwi/wokwi-features#762]
Please consider micropython support for the hcsr04 sensor. It is available in the parts section but I can't load the drivers per this page:
https://github.com/rsc1975/micropython-hcsr04

Using the command 
from hcsr04 import HCSR04
results in an error.

The page at: https://docs.wokwi.com/parts/wokwi-hc-sr04 only includes c code examples for implementation. I couldn't find python examples in the docs or the roadmap.

Thank you.

**Comment by urish** [comment]
You'd need to copy [hcsr04.py](https://github.com/rsc1975/micropython-hcsr04/blob/master/hcsr04.py) and it into your project in order to import it.
