### ISSUE TITLE
wokwi-CI Dashboard: No revoke created token and no refresh page

### ISSUE THREAD

**Issue by kassane** [wokwi/wokwi-features#764]
**URL:** https://wokwi.com/dashboard/ci
**OS:** Linux x86_64
**Web-Browser:** Firefox 124.0.1

I can't revoke any newly-created tokens.
![](https://cdn.discordapp.com/attachments/1119925211807096854/1224799580651131033/image.png?ex=661ece7f&is=660c597f&hm=45f5a39531ca3ccd0889c832cbcec4be6503eababb0c013c879cf75866c86dde&)

No refresh page
![image](https://github.com/wokwi/wokwi-features/assets/6756180/e6dc6ab2-b1a9-4ae5-a78b-87b7da44a8dc)

**Comment by urish** [comment]
Fixed - "Revoke" should now be functional, and the client side exception should (hopefully) be gone. Thanks for reporting!
