### ISSUE TITLE
Relay Module Issue

### ISSUE THREAD

**Issue by SailorMike** [wokwi/wokwi-features#765]
The relay module seems to operate in an erratic manner. It sometimes sticks closed when the Arduino pin goes low, deactivating the module.  I've tried reversing the module polarity (npn-pnp) and the activation sense of the pin from high to low; the problem persists.

Here's a link to my Bell_Test program, also "zipped" below.

https://wokwi.com/projects/394196838990889985

I wrote it to test a feature of a clock I'm building that will signal the hour in "ship's time" It's set to simulate a time of 4PM, indicated by a sequence of 8 bells in four groups of two. I've incorporated three leds; one direct from the Arduino pin 13, one activated from the wokwi-ks2e-m-dc5 relay module, and one from the relay module. All work as expected except the relay module. I think the problem may be caused by the short time intervals between "bell strikes". The LED on the relay module signalling activation also sticks on.

The module should work as expected, releasing the Normally Open contact when the signal goes low from the Arduino.

Using Windows 7 with a Chrome browser, Version 109.0.5414.120 .

[Bell_Test.zip](https://github.com/wokwi/wokwi-features/files/14877548/Bell_Test.zip)

**Comment by sutaburosu** [comment]
Your code doesn't configure the pin as an output, so it defaults to being an input. When the pin is an input, the calls to digitalWrite() only enable/disable the internal pull-up resistor. Adding `pinMode(bellPin, OUTPUT);` to setup() fixes the issue you describe.
