### ISSUE TITLE
Ultrasonic sensor bug

### ISSUE THREAD

**Issue by Pius171** [wokwi/wokwi-features#770]
**Describe the bug**
When using an ultrasonic sensor, if the echo pin is set to output the sensor still works correctly although, it should be an input

**To Reproduce**
use the ultrasound sensor and set the echo pin to output

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Windows
 - Browser :chrome
 - Version:

**Comment by urish** [comment]
Thanks for reporting! Can you please provide a link to a Wokwi project that demonstrates the issue?

**Comment by Pius171** [comment]
try any ultrasonic sensor example and make the echo pin output, it would still work normally
