### ISSUE TITLE
ds1307 initTime attribute

### ISSUE THREAD

**Issue by alto777** [wokwi/wokwi-features#775]
The document says

> The value can be... a valid ISO 8601 date string (e.g. "2019-11-19T11:41:56Z")

I did not find this to work. Removing the Z changed it to working like it looks like it should.

Try it and see. Maybe I 'm in a bad time zone.

I'm on OSX 10.14.5, running Chrome Version 116.0.5845.187 (Official Build) (x86_64)

a7

**Comment by urish** [comment]
"Z" means that the time you specified is not in the local time zone, rather in UTC. So you'll get a different value, depending on your time zone. So this is working as intended. I'll update the documentation to make it more clear.
