### ISSUE TITLE
serial port: should this work?

### ISSUE THREAD

**Issue by alto777** [wokwi/wokwi-features#777]
I am playing with the example sketch at

[Wokwi Serial Port](https://wokwi.com/projects/306534287811805760)

while I wait to find out about a com0com or TTY0TTY that can run on MacOS. In the meantime I am using two cross wired physical ports.

With CoolTerm I can open two sessions and typing in one shows up on the other and vice versa. Obvsly both sessions also work w/ a simple loop-back wire.

The sketch starts by tossing up a dialog which appears to be offering choices for the binding of the not-serial-monitor port. Nothing I do on this dialog ever results in either an error or joy. I am not seeing the yet-open session on CoolTerm hear, or be able to say, anything to the sketch in the simulation.

Mac 10.14.5, Chrome Version 116.0.5845.187

I did not hunt down or install anything to extend Chrome, and have assumed the appearance of the port selection dialog is a good thing and means I didn't have to do.

All baud rate numbers are 115200.

On a hunch, I moved the experiment to a privileged user, no joy.

So should that just work?

a7

**Comment by urish** [comment]
Well, the serial port is not officially supported, so YMMV :)

I suggest starting with a serial terminal web page: https://googlechromelabs.github.io/serial-terminal/
Should be useful to test if the issue is in your setup or in Wokwi. If it's in Wokwi, we're not going to fix it any time soon.
