### ISSUE TITLE
Add ESP32-C3-DevKit-RUST-1 target board

### ISSUE THREAD

**Issue by x46085** [wokwi/wokwi-features#784]
This board is very similar to the currently available ESP32-C3-devkit, with the additional inclusion of an onboard IMU & pressure/temp sensor. While I can make some progress with the existing C3, we are a Rust shop using this Rust-centric dev board, and so it would be ideal to emulate our actual target for CI/CD purposes.

![image](https://github.com/wokwi/wokwi-features/assets/1129228/0ec1c671-b43a-44c3-b2ee-8ef815f2f071)

Reference:
https://github.com/esp-rs/esp-rust-board

Hopefully this is not a large amount of work since it's pretty close to the current C3 board 🤞 

Amazing progress over the past year, and so much faster! Wokwi is really coming together! Thanks for all the hard work.

**Comment by urish** [comment]
Hi, thanks for the kind words :-)

The ESP32-C3-DevKit-RUST-1 board is already present in Wokwi:

https://wokwi.com/projects/new/rust-nostd-esp32-rust-board
