### ISSUE TITLE
Setting a Resistors are not effecting Voltage

### ISSUE THREAD

**Issue by faizan-ali-mlk** [wokwi/wokwi-features#791]
**Describe the bug**
I created a circuit diagram with multiple buttons on a single input. I used some resistors for this, but somehow the resistor concept is not working in the simulation. Only the last two buttons on the right show any analogRead values when pressed, but both have the same value, 1023. I tested the same circuit on another simulation platform, and it worked fine there. So, the issue seems to be with Wokwi.

**To Reproduce**
Here are the diagram.json and sketch.ino of my project to test.

[diagram.json](https://github.com/wokwi/wokwi-features/files/15393067/diagram.json)
[sketch.txt](https://github.com/wokwi/wokwi-features/files/15393074/sketch.txt)

**Expected behavior**
Each button should work separately, and the lights should turn on accordingly based on the button pressed.

**Environment (please complete the following information):**
 - OS: Mac OS M1
 - Browser: Chrome 124.0.6367.209 
 - Version 124.0.6367.209 

**Additional context**
 I want to make the following circuit diagram to test it.

![Screenshot 2024-05-20 at 14 23 15](https://github.com/wokwi/wokwi-features/assets/6730214/e2f00a2a-47a2-4a6f-93d8-d7eb57de7eb7)

This is my circuit diagram if no one want to look in json.

<img width="1018" alt="Screenshot 2024-05-20 at 17 20 32" src="https://github.com/wokwi/wokwi-features/assets/6730214/206f54b5-2497-41d0-ade5-ca33cf744b22">

**Comment by urish** [comment]
Thanks for the very detailed report! This is actually covered by #203
