### ISSUE TITLE
Unknown Build Error in Web interface

### ISSUE THREAD

**Issue by terrybailey** [wokwi/wokwi-features#795]
When attempting to run a large Arduino Mega Project in Wokwi adding an additional line of code to a working project causes a "unknown Build Error" to occur.

**To Reproduce**
Please see this project https://wokwi.com/projects/399775348611885057

**Expected behavior**
It should compile ok as it does in VSCODE.

**Environment (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Version 125.0.6422.113 (Official Build) (64-bit)

**Additional context**
I have tried this removing lines of code eventually you reach a point where it compiles and runs, adding even a simple line of code which should have no effect on the program causes the error.

**Comment by urish** [comment]
Hi, is it still failing?
