### ISSUE TITLE
The timer and the performance meter doesn't come in view 

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#8]
Earlier, when the window size was reduced, the timer and the performance meter used to come in the available window, so that user can still see them without scrolling to the extreme right.
Now, it is missing. I might be wrong too.

https://wokwi.com/playground/neopixel-strip

![image](https://user-images.githubusercontent.com/68117142/96998459-1d1e6e80-1551-11eb-944e-f4d6b6764a8e.png)

earlier reference:

![image](https://user-images.githubusercontent.com/68117142/96998379-fe1fdc80-1550-11eb-8449-7784c0d354fe.png)

**Comment by urish** [comment]
Workaround until this is fixed:
1. Resize the window
2. Refresh the page
3. Start the simulation

**Comment by urish** [comment]
Fixed!

**Comment by Puneethkumarsn** [comment]
it's perfect

**Comment by Gavin-Perry** [comment]
https://wokwi.com/playground/neopixel-strip in fact the whole playground is not available (links to home page). What happened?

**Comment by urish** [comment]
We deprecated the playgrounds two years ago: https://github.com/wokwi/wokwi-playgrounds

**Comment by Gavin-Perry** [comment]
Thanks for letting me know. I'm new to wokwi.
Well I have your attention the other thing that is odd is that the new pixel strip isn't available from the + add components menu. Only the ring and singe LED are available. I had to copy it from another project I found online into the .json file and figure out how to edit it.

Finally, I have two strips that are sent the same data and yet colors come out completely different depending on the brightness level I set. One saturates to white the other saturates to black and neither shows the colors as they are in real life.

Gavin

Sent via the Samsung Galaxy S22 5G, an AT&T 5G smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
