### ISSUE TITLE
ESP32 PullUp Error

### ISSUE THREAD

**Issue by AliSintax** [wokwi/wokwi-features#803]
An air input pin with PullUp resistance should read 1, but this is not always the case! I put a link:

https://wokwi.com/projects/400656346840659969

**Comment by urish** [comment]
Thanks for reporting!

Yes, I can see the issue. When pausing the simulation, it shows the current configuration of each pin. We can see that pin 17 is floating and not being pulled up:

![image](https://github.com/wokwi/wokwi-features/assets/892318/1368cbce-7f18-4444-af3b-b13eed800083)

**Comment by urish** [comment]
Pushed a fix - can you please test again now?

**Comment by AliSintax** [comment]
Ok yes!!, It works.

Very thanks for reviewing it and also for the speed!!
