### ISSUE TITLE
ESP32-S2 UART issues

### ISSUE THREAD

**Issue by lucasssvaz** [wokwi/wokwi-features#806]
**Describe the bug**
The output of some ESP32-S2 tests consistently have wrong bytes/garbled text. It started happening this last day.

**To Reproduce**
Check CI output:
https://github.com/espressif/arduino-esp32/actions/runs/9540907794/job/26312774907#step:11:1107
https://github.com/espressif/arduino-esp32/actions/runs/9540907794/job/26312774907#step:11:268
https://github.com/espressif/arduino-esp32/actions/runs/9540907794/job/26312774907#step:11:531

**Expected behavior**
Normal output like the other chips.

**Environment (please complete the following information):**
 - OS: ubuntu-latest

**Comment by urish** [comment]
Issue reproduced - researching what causes it

**Comment by urish** [comment]
Looks like it's related to wrong initial value for the PRE_DIV_CNT field in the SYSCLK_CONF conf register, causing UART baud rate to go totally crazy, initially:

![image](https://github.com/wokwi/wokwi-features/assets/892318/0c5b68ce-d4fd-4a93-9d38-614f9d5d2218)

 Working on a fix.

**Comment by urish** [comment]
Fix is up - can you please test again now?

**Comment by lucasssvaz** [comment]
@urish looks good. Everything working as expected. Thanks!

**Comment by urish** [comment]
Thanks for spotting this!
