### ISSUE TITLE
Humidity sensor project breaks - reason unknown

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#81]
![image](https://user-images.githubusercontent.com/68117142/116815198-1add4280-ab7a-11eb-8564-383ac4335b23.png)

**Observation**:

It fails always at the time stamp of around 58 seconds (simulation time)
https://wokwi.com/arduino/libraries/DHT-sensor-library/DHT-Tester

When the issue was occurring, I as also using other tabs where I was using Humidity sensors too

**Comment by urish** [comment]
Reproduced here as well

**Comment by urish** [comment]
I believe this has been fixed - it does not reproduce here anymore. 

Does the issue still reproduce for you?
