### ISSUE TITLE
Slow "Compiling Times" in Wokwi Simulator for VSCode

### ISSUE THREAD

**Issue by martysweet** [wokwi/wokwi-features#815]
**Describe the bug**
When using Wokwi in VSCode, after pressing play on the simulator, occasionally, "Compiling project" will appear for well over a minute.

> Compiling project...
> While waiting, why not check out Wokwi for VS Code?

Most times, the simulation starts without any delay.

**To Reproduce**
Locally built .bin file (using ESP-IDF).

`wokwi.toml`
```
[wokwi]
version = 1
elf = "build/blink.elf"
firmware = "build/blink.bin"
```

Custom Chips with public Github dependencies
```json
"dependencies": {
    "chip-mcp23s17": "github:martysweet/mcp23s17-wokwi-chip@1.0.0",
    "chip-st7735": "github:martysweet/st7735-wokwi-chip@1.0.3"
  }
```

ESP32 part
```
    {
      "type": "wokwi-esp32-devkit-v1",
      "id": "esp",
      "top": -52.9,
      "left": -43.4,
      "attrs": { "flashSize": "8" }
    }
```

**Expected behavior**
When starting the simulation, the experience should be consistent. 

**Environment (please complete the following information):**
 - OS: Linux / VSCode 1.86.1

**Additional context**
This used to happen on the odd occasion, but the frequency seems to have got considerably worse today (ever other launch or so) - is there a way I can enable debug logging for the extension to discover whats going on during this period? CPU and Network statistics are minimal.

Thanks for the great tool!

**Comment by urish** [comment]
Thanks for the super detailed report! 

I need to investigate, but my bet is that it's related to the custom chips loader.

**Comment by urish** [comment]
Hi again Marty, I added some caching at the backend - can you please check and report if the slow "Compiling" issue is still there for you?

**Comment by martysweet** [comment]
Hi @urish,

Thanks for the quick response!

I am now getting
>Error in diagram.json
>Please fix the error and click Retry:
>RETRY

Would be good if such an error had more details.
My diagram.json hasn't changed (git diff'ed from weeks ago).

I have attached it here: [diagram.json](https://github.com/user-attachments/files/15975296/diagram.json)

I've tried to relaunch VSCode a few times.

**Comment by urish** [comment]
Yes, seems like there is some issue with the cache :( I'll disable it and investigate

**Comment by urish** [comment]
I believe I found the issue with the caching and have hopefully fixed it - can you please check again now?

**Comment by martysweet** [comment]
Diagram seems to be working again.

First attempt: Gave up after 240s.  -- Is something timing out? (like the client - but the action completes server side?)
Restarted VSCode
Second attempt: Instant (I assume a lovely cache hit)
10+ more attempts, with various VSCode restarts: Instant

👍 

Thanks for your help!

**Comment by urish** [comment]
Thanks for testing!

And yeah, we definitely have some work on improving the error messages. It'll happen :)
