### ISSUE TITLE
'Start New project'

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#83]
a request to have a "Start new project" option on the [homepage](https://wokwi.com).

**Comment by urish** [comment]
Thanks for the suggestion! I plan to start working on it later this week 🤞

**Comment by urish** [comment]
Duplicate of #21

**Comment by urish** [comment]
https://wokwi.com/arduino/new

**Comment by Puneethkumarsn** [comment]
Thanks 🥳
