### ISSUE TITLE
wires when drawn using mouse takes a random route

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#84]
Even after guiding the mouse, some times, the wires takes a different route (the green wires)
![image](https://user-images.githubusercontent.com/68117142/116923014-b6061300-ac73-11eb-8e2f-bc392318becd.png)

here is a link to the gif. It retains the shape. only a few points are getting out of the set length. I guess. 
![arduino simulator wokwi27](https://user-images.githubusercontent.com/68117142/116923640-80adf500-ac74-11eb-8e1e-a22ddb04bfd9.gif)

**Comment by urish** [comment]
Thanks for reporting, fixed!
