### ISSUE TITLE
Pin D13 always pull-up on wokwi-esp32-devkit-v1 with Micropython

### ISSUE THREAD

**Issue by AnonEngineering** [wokwi/wokwi-features#845]
**Describe the bug**
Pin D13 always presents as INPUT_PULLUP regardless of Pin setting on wokwi-esp32-devkit-v1 with Micropython

**To Reproduce**
See https://wokwi.com/projects/403592328815813633, no matter how D13 is configured on line 19 it reports as pullup.

**Expected behavior**
Expect to be able to disable pullup on D13

**Environment (please complete the following information):**
Tested on
 - OS: Windows 10
 - Browser: Chrome
 - Version: 126.0.6478.127

**Additional context**
Reported at Wokwi | questions | Pull up resistor, Jun 16 2024

**Comment by urish** [comment]
Thanks for the detailed report. Pushed a fix - can you please try once more and report?
