### ISSUE TITLE
The ESP32-S3 with MicroPython does not have Serial output.

### ISSUE THREAD

**Issue by Koepel** [wokwi/wokwi-features#846]
It is mentioned in the Discord channel that the combination of the ESP32-S3 with MicroPython causes troubles.
Starting with a new project does not show the Serial output: https://wokwi.com/projects/new/micropython-esp32-s3

**Comment by urish** [comment]
Quick investigation shows it's probably related to the USB peripheral. Looking into this.

**Comment by urish** [comment]
Further investigation shows that the RXFLVI USB interrupt is not correctly cleared, and keeps firing forever. Unfortunately, this is not a trivial issue to investigate why the interrupt is not cleared, as the USB OTG peripheral is very sparsely documented in the TRM, so it'll take some time until we figure it out.

**Comment by Koepel** [comment]
If someone is looking for this Issue, is there a workaround ? Can one of the UARTs be routed to the Serial Monitor ?

**Comment by urish** [comment]
As a workaround, we can simply disable the USB on ESP32-S3 for all projects. 

The UARTs are already routed to the serial monitor - the issue is, if the USB peripheral is present, the code hangs on the initialization.

**Comment by urish** [comment]
Following your feedback, I decided to disable the USB-ORG peripheral on the ESP32-S3 across all projects, so now micropython should be functional again.
