### ISSUE TITLE
Error loading library index

### ISSUE THREAD

**Issue by kraa965** [wokwi/wokwi-features#851]
hello, when I try to add a library on the site wokwi.com I get the error message: Library index loading error:-(

**Comment by urish** [comment]
Hello!

What do you see when you go to the following link? https://libraries.wokwi.workers.dev/list

(this is where the library index is loaded from)

**Comment by kraa965** [comment]
> Hello!
> 
> What do you see when you go to the following link? https://libraries.wokwi.workers.dev/list
> 
> (this is where the library index is loaded from)

nothing the page is not loading

**Comment by urish** [comment]
Then there is probably something that is blocking this page on your browser or network (e.g. anti virus, firewall, VPN, etc)

**Comment by kraa965** [comment]
> Then there is probably something that is blocking this page on your browser or network (e.g. anti virus, firewall, VPN, etc)

thank you, I figured it out, for some reason the provider blocked this link https://libraries.wokwi.workers.dev/list
