### ISSUE TITLE
esp32-s2 simulation fails to start on board without default UART pins

### ISSUE THREAD

**Issue by c-DiRay** [wokwi/wokwi-features#854]
**Describe the bug**
when using board-wemos-s2-mini the simulation fails to start with the JS error: ```Error: Net pin not attached```

**To Reproduce**
[link](https://wokwi.com/projects/355047217294313473)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 127

**Additional context**
![image](https://github.com/user-attachments/assets/2a56ccfa-007e-46b0-97f8-56f3d624e7a8)

**Comment by urish** [comment]
Thanks for the detailed report! Pushed a fix, can you please test again and report?

**Comment by c-DiRay** [comment]
Thanks for the quick fix, it works now
