### ISSUE TITLE
Missing Library

### ISSUE THREAD

**Issue by martin-how** [wokwi/wokwi-features#86]
I am liking Wokwi, and hope to use it to further develop the firmware on an installed project with lots of physical IO devices.

I use the encoder library by Paul Stoffregen which is a good genral purpose library for low cost rotary encoders and de bounces nicely.
![image](https://user-images.githubusercontent.com/23172991/117309248-28e0db00-ae7a-11eb-9b53-223f66ba6748.png)

Could you consider adding it?

Martin How

**Comment by urish** [comment]
Library added!

**Comment by urish** [comment]
Now we also have a [Rotary encoder part](https://docs.wokwi.com/parts/wokwi-ky-040)!
