### ISSUE TITLE
Wokwi for VS Code - simulator does nothing when bootloader.bin is missing

### ISSUE THREAD

**Issue by georgik** [wokwi/wokwi-features#867]
Wokwi for VS Code is able to launch simulation after building the project with `idf.py build`.
This command generates also `build/bootloader/bootloader.bin`.
When the file is missing then nothing happens after selecting "Wokwi: Start Simulator".
The error is only visible in Developer Console.

**To Reproduce**
- Take ESP-IDF project and build it with `idf.py app-flash`.
- The build process won't generate `build/bootloader/bootloader.bin` file.
- Start the Simulator, result: nothing happens, no visual feedback to the user

**Workaround**
Build the project with `idf.py build`

**Expected behavior**
Display error message, that bootloader was not found and recommend to user a correction by running `idf.py build`

**Environment (please complete the following information):**
 - OS: macOS
 - VS Code

**Comment by urish** [comment]
Thanks for reporting! Fixed in version 2.5.2 of the VS Code extension.
