### ISSUE TITLE
Chips C API Provides little to no error information

### ISSUE THREAD

**Issue by dakotath** [wokwi/wokwi-features#868]
**Describe the bug**
I'm trying to use the I2C API for custom chips, and I'm getting errors as detailed as
```c
    .scl = scl,
           ^~~
1 error generated.

Error: Process exited with 1
```
**To Reproduce**
Try using the I2C API for custom chips by following the documentation.

**Expected behavior**
I expected a detailed error.

**Environment (please complete the following information):**
 - OS: Windows 11 Enterprise
 - Browser: Microsoft Edge
 - Version: 127.0.2651.86 (Official build) (64-bit)

**Additional context**
Me want to make custom chips.
![image](https://github.com/user-attachments/assets/9593b7dc-8a4f-4ac2-9bda-bab486f9ffcd)

**Comment by urish** [comment]
Thanks! Can you please provide a link to the project above with the bogus error message?

**Comment by urish** [comment]
Error messages fixed - should be more helpful now.
