### ISSUE TITLE
Pico simulator observation

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#87]
https://wokwi.com/arduino/projects/297912292682498570

After about 24 seconds, the serial terminal detects some data (mostly it happens when the for loop executes faster)
![wokwi Pico simulator 4](https://user-images.githubusercontent.com/68117142/117436101-35cdff00-af4c-11eb-9d35-7384cb4e61a0.gif)

**Comment by urish** [comment]
The reason is that the Serial monitor is connected to GP0, same as the rightmost blue LED.

So blinking that LED actually sends some garbage on the serial monitor.

As a workaround, you can break the Serial monitor connection in diagram.json (or just hide it)
