### ISSUE TITLE
The Raspberry Pi Pico W needs also a startup delay in MicroPython.

### ISSUE THREAD

**Issue by Koepel** [wokwi/wokwi-features#879]
It was mentioned in the Discord channel that the Raspberry Pi Pico **W** needs `time.sleep(0.1)` in the template code.

When this is used as starting point: https://wokwi.com/projects/new/
Then the "Raspberry Pi Pico" gets a delay in the MicroPython template. That delay is required to run.
```
import time
time.sleep(0.1) # Wait for USB to become ready

print("Hello, Pi Pico!")
```

The "Raspberry Pi Pico **W**" does not have that delay and therefor it does not run.
```
print("Hello, Pi Pico W!")
```

**Comment by urish** [comment]
Thanks for reporting, template updated!
