### ISSUE TITLE
Error connecting to build server: TypeError: failed to fetch

### ISSUE THREAD

**Issue by Puneethkumarsn** [wokwi/wokwi-features#88]
- I observed this error after clicking on RUN button. persistent even after trying several times.

- I had also observed it yesterday while trying to open "new project" link for Arduino

hard refresh got rid of it
![image](https://user-images.githubusercontent.com/68117142/117436664-dae8d780-af4c-11eb-9454-f92d36a72990.png)

link I was working on: https://wokwi.com/arduino/projects/297912292682498570

**Comment by urish** [comment]
Do you see any kind of error in the Chrome Devtools console?

**Comment by Puneethkumarsn** [comment]
I will capture it next time
