### ISSUE TITLE
Speaker

### ISSUE THREAD

**Issue by Ali34-rgb** [wokwi/wokwi-features#886]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when […]

**Describe the solution you'd like**

**Comment by Ali34-rgb** [comment]
> **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
> 
> **Describe the solution you'd like** A clear and concise description of what you want to happen.

**Comment by theahadev** [comment]
Hmm, whats going on here?
