### ISSUE TITLE
ESP32-S2 | Rust | no-std | Blinky not blinking

### ISSUE THREAD

**Issue by SergioGasquez** [wokwi/wokwi-features#891]
**Describe the bug**
The Rust blinky example of S2 for no-std Rust is not blinking. If I download the elf and run it on real hw, I see the gpio changing as expected, but on the simulation, the led is always turned on.

**To Reproduce**
Build and run https://wokwi.com/projects/341955297469792851

**Expected behavior**
The led blinks as in real hw:
![image](https://github.com/user-attachments/assets/a17e436e-87b0-4cee-aefb-7c699fd521b1)

**Environment (please complete the following information):**
 - OS: Arch Linux (`6.10.10-arch1-1`)
 - Browser: Brave-Chrome

**Comment by urish** [comment]
Thanks for reporting! Looks like the code hangs in `delay.delay_millis()` for some reason.

**Comment by urish** [comment]
Pushed a fix - can you please test again?

**Comment by SergioGasquez** [comment]
It's now working! Thanks for the fix!
