### ISSUE TITLE
[Translations] Translation update for pt-BR #221

### ISSUE THREAD

**Issue by djedu28** [wokwi/wokwi-features#894]
Continuing the work done on #221 #223. I've done the translation gradually by saving it in this repository: <https://github.com/djedu28/wokwi-i18n-translate>

The Wokwi interface allows integration with several languages, and in the future I intend to create a tool in this repository that will make it easier for the community to translate Wokwi into their native languages.

During the translation, I noticed that some components (parts) didn't have documentation. I'm very happy when I search for a component on Google and the wokwi documentation appears in the top 3 results (which happens very often). 

Given the great relevance of this documentation, I would be happy to contribute to the documentation of the missing items, is there any place informing the status of the documentation of each component?

@arcostasi agradeço tua revisão

>
> Continuando o trabalho feito em #223.  Realizei a atualização da tradução gradualmente salvando neste repositório: <https://github.com/djedu28/wokwi-i18n-translate>
> 
> A interface Wokwi permite a integração dom diversos idiomas, e pretendo futuramente criar neste repositório uma ferramenta que facilite a comunidade traduzir o wokwi para seus idiomas nativos, por hora realizei a tradução manual do jeito tradicional.
> 
> Durante a tradução, notei que alguns componentes não possuem documentação, fico muito feliz quando pesquiso sobre algum componente no Google e a documentação do wokwi aparece no top 3 resultados (o que acontece com muita frequência). 
> Dado a grande relevância dessa documentação, fiarei feliz em contribuir com a documentação dos itens que faltam, existe algum lugar informando o status da documentação de cada componente?

[pt-BR.zip](https://github.com/user-attachments/files/17219876/pt-BR.zip)

**Comment by urish** [comment]
Thank you very much, translations updated in the app.
