### ISSUE TITLE
Wokwi: Start Simulator and Wait for Debugger does not indicate that gdbServerPort was not configured in wokwi.toml

### ISSUE THREAD

**Issue by georgik** [wokwi/wokwi-features#898]
**Describe the bug**
When developer selects Start Simulator and Wait for Debugger and the `gdbServerPort` was not configured in wokwi.toml. There is no indication that the configuration is missing and Debugger just times out.

**To Reproduce**
- create `wokwi.toml` without `gdbServerPort=3333`
- VS Code: Start Simulator and Wait for Debugger
- VS Code: Start debugging
- result: timeout

**Expected behavior**
The Simulator should display warning and sugegestion how to correct it. E.g. by adding `gdbServerPort=3333` to `wokwi.toml`

**Comment by urish** [comment]
Excellent suggestion, thanks! Released this as part of version 2.5.4 of the extension.

**Comment by georgik** [comment]
Works very good. Thank you.
