### ISSUE TITLE
IR Receiver / Transmitter / Remote Control

### ISSUE THREAD

**Issue by jimf99** [wokwi/wokwi-features#90]
Would be nice to have an IR Receiver, Transmitter, Remote added.
Thank You!
Kind Regards,
JimFyyc Calgary Alberta Canada

**Comment by urish** [comment]
Thanks for suggesting! As I first step, I added the IRremote library to the simulation. 

What IR remote model should we add?

**Comment by jimf99** [comment]
1) NEC IR Remote Is popular and easy to understand the IR Codes and timings.
Once you have NEC then SAMSUNG Remotes are popular too.

Hope this helps.

**Comment by urish** [comment]
Thanks! Do you have a link to a drawing or photo?

**Comment by jimf99** [comment]
https://cdn-shop.adafruit.com/970x728/389-03.jpg

**Comment by jimf99** [comment]
Generic IR Remote

https://cdn-shop.adafruit.com/970x728/389-03.jpg

**Comment by urish** [comment]
Good news: IR Receiver + Remote control are ready!

* Quick demo: https://wokwi.com/arduino/projects/298922033226449421
* [IR Receiver Docs](https://docs.wokwi.com/parts/wokwi-ir-receiver)
* [IR Remote Docs](https://docs.wokwi.com/parts/wokwi-ir-remote)
