### ISSUE TITLE
Feature request: Keyboard shortcuts for start/stop/pause in the diagram

### ISSUE THREAD

**Issue by Koepel** [wokwi/wokwi-features#904]
It was mentioned in the Discord channel that there are no keyboard shortcuts in the diagram to start and stop and pause the simulation.

There are keyboard shortcuts for the editor: https://docs.wokwi.com/keyboard-shortcuts/
There are keyboard shortcuts for designing the diagram: https://docs.wokwi.com/guides/diagram-editor/#keyboard-shortcuts
But there are no keyboard shortcuts when the simulation is running and the diagram window is active.

The Ctrl+Enter to start would be nice, and also keyboard shortcuts to pause and stop.

**Comment by urish** [comment]
Good call - any suggestions for what the keyboard shortcuts would be?

**Comment by drf5n** [comment]
I'd think the command-Enter to start should match the command in the editor window.

And that it shouldn't conflict with the potential button hotkeys.  For example: 

<img width="455" alt="image" src="https://github.com/user-attachments/assets/607b39f4-0093-4713-8bbd-5b0957d989b7">

Interesting: the arrow keys move the sketch around unless they are bound to buttons.

The SerialMonitor window appears to be a separate context

Maybe . and , for stop and pause would seem natural and low-impact?

| Description | Windows/Linux | Mac |
|--|--|--|
| Start simulation | Ctrl + Enter | ⌘ Enter |
| Stop simulation | . | . |
| Pause Simulation | , | , |


Or Ctrl + . and Ctrl + , if they should also work in the edit window?  But the Control modifier key is on the button-shortcut list.

As are the other modifiers:

https://wokwi.com/projects/413109749162525697

**Comment by urish** [comment]
Thanks for the useful suggestion! 

I've pushed a version with these keyboard shortcuts - would love to get feedback (and if it works well, we can close the issue)

**Comment by Koepel** [comment]
The . and the , work but I can't start it.

**Comment by drf5n** [comment]
Command-Enter ',' and '.' work on a Mac in Chrome with https://wokwi.com/projects/384583073378554881

Cool.

However, Command-Enter does not restart a paused or already running script when focus is in the diagram.  If focus is in the Code window it unconditionally causes a restart, whether the script is running, paused, or stopped.

**Comment by urish** [comment]
Thanks @Koepel  - which browser do you use? I tested with Chrome / Firefox

**Comment by Koepel** [comment]
**Tested** with focus on different fields with different browsers and different settings:
- Start: with Ctrl+Enter
- Pauze: with ',' and Ctl+,
- Stop: with '.' and Ctrl+.

Browsers:
- Windows 11: Microsoft Edge, Firefox, Vivaldi, Chrome
- linux: Firefox, Chromium

**Good results:**
It works as expected.
The Firefox browser has a "search for text when you start typing" option. That messes up the ',' and the '.' as expected. But the Ctrl+, and Ctrl+. work normally.
The Vivaldi browser had always some compatibility issues with Wokwi, but it seems to work better now. The keyboard shortcuts do always work.

**One thing:**
I can not replicate the result where ',' and '.' work and Ctrl+Enter not.
But I can set the focus wrong.
When the focus is on the source code and then I click on the "Simulation" tab or the bar next to it, then the circuit field does not get the focus.
![afbeelding](https://github.com/user-attachments/assets/f70f5328-90d8-490c-8eee-0127f330ea0b)

**Comment by urish** [comment]
Thanks! Then I guess we can close this issue as complete. I'll look into the focus thing as well.
