### ISSUE TITLE
Autoformat in custom.chip.c files

### ISSUE THREAD

**Issue by drf5n** [wokwi/wokwi-features#906]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I try to edit a custom chip .c file and the autoformat doesn't work.  (I'm using Chrome on a Mac and Shift-Option-F simply inserts an Ï  )  Also, the other-click menu doesn't show formatting as an option:

<img width="816" alt="image" src="https://github.com/user-attachments/assets/1b5793d8-29b0-457d-a6c0-8824e1ce568b">

Here's a sample project with the issue:

https://wokwi.com/projects/413585628218621953

I would like the custom chip editor window on Wokwi to be able to autoformat custom chip.c files like it does for other .ino files and .json files.

There's a bit of discussion at:

https://discord.com/channels/787627282663211009/1302645970294673460/1302645970294673460

I think  the .chip.c suffix confuses something.

**Comment by urish** [comment]
Thanks for reporting! Pushed a fix - can you please test again now and report?

**Comment by drf5n** [comment]
It works for me.  Thanks!
