### ISSUE TITLE
No error message when wokwi.toml is malformed

### ISSUE THREAD

**Issue by HubertKoziolek** [wokwi/wokwi-features#913]
**Describe the bug**
A `[wowki]` typo in `wokwi.toml` didn't result in any visual error.

**To Reproduce**
Change `[wokwi]` in `wokwi.toml` to some malformed version f.e. `[wowki]` and try to Start Simulation.
Nothing happens.

**Expected behavior**
An error message/popup shows up informing about malformed `wokwi.toml` file.

**Environment (please complete the following information):**
 - OS: Windows 11 (22631.4317)
 - VSCode: v1.95.2
 - Wokwi Simulator Extension: v2.5.4

**Comment by urish** [comment]
Thanks for reporting! Fixed in version 2.5.5 of the extension.
