### ISSUE TITLE
wokwi-ci: not run rp2040 firmware

### ISSUE THREAD

**Issue by kassane** [wokwi/wokwi-features#915]
Hi, @urish :wave: 

**Describe the bug**

wokwi-ci not run rp2040 `.uf2` firmware, emit error:
```console
API Error: Connection to wss://wokwi.com/api/ws/beta closed unexpectedly: code 1006
```

**To Reproduce**

- https://github.com/kassane/rp2040-dlang/compare/main...wokwi-ci
- [running blinkly from RP2040-dlang](https://wokwi.com/experimental/viewer?diagram=https%3A%2F%2Fraw.githubusercontent.com%2Fkassane%2Frp2040-dlang%2Frefs%2Fheads%2Fmain%2Fdiagram.json&firmware=https%3A%2F%2Fgithub.com%2Fkassane%2Frp2040-dlang%2Freleases%2Fdownload%2Fv1.0.0%2Fd-blinky-rp2040.uf2) - wokwi experimental/viewer

**Expected behavior**

No error! Run, like experimental/viewer
- https://github.com/kassane/rp2040-dlang/releases/tag/v1.0.0 (wokwi-testing)

**Environment (please complete the following information):**
 - OS: Ubuntu 24.04
 - Browser: Firefox
 - Version: 132.0.1

## Reference
- https://github.com/kassane/rp2040-dlang/issues/1

**Comment by urish** [comment]
Hi @kassane,

Thanks for reporting!

Can you please try using the [wokwi-ci-server-action](https://github.com/wokwi/wokwi-ci-server-action) and see if it fixes the issue?

**Comment by kassane** [comment]
> Can you please try using the [wokwi-ci-server-action](https://github.com/wokwi/wokwi-ci-server-action) and see if it fixes the issue?

https://github.com/kassane/rp2040-dlang/actions/runs/12120844427/job/33790453083
```console
Run docker run -d -p 9177:3000 --name wokwi-ci-server wokwi/wokwi-ci-server
Unable to find image 'wokwi/wokwi-ci-server:latest' locally
latest: Pulling from wokwi/wokwi-ci-server
da9db072f522: Already exists
9f55c94602e4: Pulling fs layer
cd7875902382: Pulling fs layer
23b7f06a0560: Pulling fs layer
23b7f06a0560: Verifying Checksum
23b7f06a0560: Download complete
9f55c94602e4: Verifying Checksum
9f55c94602e4: Download complete
9f55c94602e4: Pull complete
cd7875902382: Verifying Checksum
cd7875902382: Download complete
cd7875902382: Pull complete
23b7f06a0560: Pull complete
Digest: sha256:eb4f70811fc63614fa4b2b077b7e2486aa21d7108ee2086a7d8f3ca060469a4a
Status: Downloaded newer image for wokwi/wokwi-ci-server:latest
cdd7682e3d56e8d786251d85abd53050790818b4a5d81f9a4f2cfa6ffbfb3c49

Run wokwi-cli --timeout "5000" --expect-text "$CI_EXPECT_TEXT" \
Wokwi CLI v0.14.5 (e69493bb8261)
Connected to Wokwi Simulation API 1.0.0-20241117-gdfc711df
Starting simulation...
Timeout: simulation did not finish in 5000ms
Hello, world from D!
Error: Process completed with exit code 42.
```

**Comment by urish** [comment]
looks like it's running now - the only question is why it didn't match the expected text.

Is the "Hello, world from D!" print followed by a newline?

**Comment by kassane** [comment]
> Is the "Hello, world from D!" print followed by a newline?

No! `\n` not added in https://github.com/kassane/rp2040-dlang/blob/53f704e247639964d0d20adeb3e4cb77a34df56f/sample/app.d#L8
impl: https://github.com/kassane/rp2040-dlang/blob/53f704e247639964d0d20adeb3e4cb77a34df56f/source/pico/newlib.d#L23

**Comment by kassane** [comment]
Solved!!
