### ISSUE TITLE
Allow more pages 

### ISSUE THREAD

**Issue by remaziero** [wokwi/wokwi-features#917]
Allow more pages for inserting components with interconnection points, enabling developments with more complete hardware.

**Comment by djedu28** [comment]
Hello,

I'd like to gather some additional information to better understand this feature request. Could you please provide more details?

Specifically:

1. Is this feature request intended for the `VS Code extension` or the `web version` of Wokwi?
2. Do you have any specific use cases or examples where this functionality would be particularly useful?
3. Are there any particular types of hardware projects you're working on that could benefit from this capability?

Any additional context or insights you can share would be greatly appreciated. This will help us assess the feasibility and priority of implementing this feature.

Thank you for your input!
