### ISSUE TITLE
Scratch coding for wokwi

### ISSUE THREAD

**Issue by ngkienlong** [wokwi/wokwi-features#921]
**Is your feature request related to a problem? Please describe.**
I'm teaching STEM using Arduino for the middle school students and usually use Scratch coding.

**Describe the solution you'd like**
The best solution for me is a toggle button that allow user change programming laguage from C to Scratch. Please take a look at mBlock 5 app.

**Comment by urish** [comment]
Thanks for filing the request. Scratch is out of scope for Wokwi, so we won't implement it.
