### ISSUE TITLE
Anti Spam Measure in Latest projects

### ISSUE THREAD

**Issue by DarwinWasWrong** [wokwi/wokwi-features#925]
The instances of spam in latest projects is increasing

It is noted that none of the spam entries actually can compile

Change the title **Latest projects** to  **Latest compiled projects**

1. do a syntax check or compile to test the project before adding to  Latest compiled projects
2. do not add projects that are created by new users - eg a few days old account.

This would also stop **Latest compiled projects** from having quick un-working examples.

**Comment by urish** [comment]
Thanks for reporting! 

I've started working on measures to significantly reduce spam, and deleted over 250,000 existing spam projects from the database. Please do let me know if you come across any spam projects on Wokwi.

**Comment by urish** [comment]
Still working on eliminating the spam projects, got 427,269 down so far.

It's challenging, as some of them are pretty sophisticated and actually look like legit projects, e.g. 

![image](https://github.com/user-attachments/assets/0a7e400c-7441-4ec4-a71e-6b5f75d3d49e)

**Comment by DarwinWasWrong** [comment]
Wow. 

Impressive spam kill tally 

 

but what lengths they go to.

I really didn't think they would make it able to compile.

 

Never underestimate 

 

Get Outlook for Android <https://aka.ms/AAb9ysg> 

 

  _____

**Comment by urish** [comment]
Yeah, never underestimate!

Removed total of 471,001 SPAM projects created by 3,887 different registered users, and put a bunch of measures to stop / slow down future SPAM raids. Closing - please do open a new issue if you notice another SPAM raid in the future.
