### ISSUE TITLE
TinyPICO projects no longer build online

### ISSUE THREAD

**Issue by vberthiaume** [wokwi/wokwi-features#928]
If you try to run an existing project containing a `wokwi-tinypico`, e.g., https://wokwi.com/projects/308012505806930496, it'll run fine. But if you edit the code you get this error and cannot build it:

![image](https://github.com/user-attachments/assets/31fabff7-fa25-4759-8dda-e5ec52702574)

Using the Wokwi extension in VSCode in conjunction with platformio _does_ build fine however.

**Comment by urish** [comment]
Fixed, thanks for reporting!

For future users seeing this: the Tiny Pico is not officially supported, and won't be maintained moving forward.
