### ISSUE TITLE
The sim diagram's default zoom level could be capped at some sensible maximum

### ISSUE THREAD

**Issue by sutaburosu** [wokwi/wokwi-features#94]
When starting from [a new sketch](https://wokwi.com/arduino/new), on some screens the new MCU is huge and dominates the diagram tab. 
![image](https://user-images.githubusercontent.com/20606/118721572-f42e3580-b822-11eb-9212-95b764a923ff.png)

Perhaps the default zoom level could be capped at some level,  so the size of the elements is never drastically bigger than in real life.

**Comment by urish** [comment]
Thanks for reporting!

Limited the default zoom level to x1.5. 

Is it still too big? Or perhaps too small now?

**Comment by sutaburosu** [comment]
This seems much better from my perspective. I didn't realise that I wanted this until it was suggested.

@Puneethkumarsn how is it for you?

**Comment by Puneethkumarsn** [comment]
It is awesome here :)

**Comment by sutaburosu** [comment]
Thanks for the feedback, and thanks, Uri, for the quick turnaround.
