### ISSUE TITLE
Including a wifi module-ESP8266 

### ISSUE THREAD

**Issue by vrishanka** [wokwi/wokwi-features#99]

**Comment by urish** [comment]
Would an ESP32 be useful too?

**Comment by vrishanka** [comment]
YES!

**Comment by urish** [comment]
Thanks for the feedback! What project are you currently working on?

How does it use the WiFi?

**Comment by vrishanka** [comment]
I was working on remote home automation . So by using the wifi module , I
can connect to the blynk app and switch off or on the applications by just
a tap
It can be made possible only if the wifi module is available

https://www.youtube.com/watch?v=HLokF4oPgGY
attaching the above link so that you can get a better picture on how the
blynk app can be used

wifi module has another major use , as it can used to visualize the
simulation on Thingspeak

**Comment by urish** [comment]
Closing as we now have ESP32 (with WiFi)
